mongodb/mongo-java-driver

bson/src/main/org/bson/json/JsonReader.java
bson/src/test/unit/org/bson/json/JsonReaderTest.java

implement "$date": "2015-04-14T14:55:57.626Z" and "$date": "2015-04-14T14:55:57+02:00" extended json parsing in JsonReader
See Jira ticket https://jira.mongodb.org/browse/JAVA-1768

parse datestrings under $date in JsonReader

---

driver/src/main/com/mongodb/gridfs/GridFS.java

Update the comment to make it consistent with the code.

Update the default chunk size in comment

---

driver-core/src/main/com/mongodb/WriteConcernResult.java
driver-core/src/main/com/mongodb/client/result/DeleteResult.java
driver-core/src/main/com/mongodb/client/result/UpdateResult.java

fix typos in javadocs

---

driver/src/main/com/mongodb/client/MongoCollection.java

The `@return` is slightly wrong for `MongoCollection.updateMany`.

Javadoc: Fix result of MongoCollection.updateMany

---

bson/src/main/org/bson/Document.java

Fixed JavaDoc copy/paste errors for getBoolean method

Fixed JavaDoc copy/paste errors for getBoolean method

---

driver-core/src/main/com/mongodb/WriteConcern.java

Javadoc: Update the WriteConcern majority definition

---

driver-core/src/main/com/mongodb/client/model/Filters.java

does --> doesn't
I _think_ this is what is actually meant... Apologies if I'm mistaken.

Fix javadoc

---

docs/reference/content/upgrading.md

Hello,
Table is not displaying properly at : 
http://mongodb.github.io/mongo-java-driver/3.6/upgrading/#compatibility
Farès

[docs] Fix Markdown table syntax

---

driver-core/src/main/com/mongodb/connection/ServerDescription.java

Alternative solution for 
https://jira.mongodb.org/browse/JAVA-2625
and
https://github.com/mongodb/mongo-java-driver/pull/419

[JAVA-2625] Set the character used for decimal separator

---

driver-embedded/src/main/com/mongodb/embedded/client/MongoDBCAPI.java
driver-embedded/src/main/com/mongodb/embedded/client/MongoDBCAPIHelper.java

Reference the MongoDB embedded v1 ABI symbols

---

THIRD-PARTY-NOTICES
bson/src/main/org/bson/assertions/Assertions.java
bson/src/main/org/bson/internal/UnsignedLongs.java
bson/src/main/org/bson/util/AbstractCopyOnWriteMap.java
bson/src/main/org/bson/util/CopyOnWriteMap.java
bson/src/test/unit/org/bson/internal/UnsignedLongsTest.java
driver-core/src/main/com/mongodb/annotations/Beta.java
driver-core/src/main/com/mongodb/annotations/Immutable.java
driver-core/src/main/com/mongodb/annotations/NotThreadSafe.java
driver-core/src/main/com/mongodb/annotations/ThreadSafe.java
driver-core/src/main/com/mongodb/assertions/Assertions.java
driver-core/src/main/com/mongodb/connection/netty/ReadTimeoutHandler.java
driver-core/src/main/com/mongodb/internal/authentication/SaslPrep.java

Reverted copyright changes

---

docs/reference/content/driver/tutorials/authentication.md

Looks like there is minor spelling mistake in package name.

typo in package name

---

docs/reference/content/bson/readers-and-writers.md

In driver 3.8 these are interfaces

BsonReader and BsonWriter are interfaces

---

docs/reference/content/driver-async/getting-started/quick-start.md

misspelled in describe Block<T> method

misspelled

---

driver-async/src/examples/tour/QuickTour.java
driver-async/src/examples/tour/QuickTourAdmin.java
driver/src/examples/tour/QuickTour.java
driver/src/examples/tour/QuickTourAdmin.java

@rozza it's not really a find and replace here so much as a real fix to broken links.  Assuming you're OK with this PR I'll be opening up 8 more (😦) with fixes to 3.2.x through 3.9.x

JAVA-3134 Point QuickTour links to correct github pages

---

driver-benchmarks/src/main/com/mongodb/benchmark/framework/Benchmark.java

Found some unused imports in the `Benchmark` class.

Remove unused imports

---

README.md

Found some minor typo's in the README.

Fix typo's in README

---

3.10/driver/getting-started/quick-start-pojo/index.html
3.7/driver/getting-started/quick-start-pojo/index.html
3.8/driver/getting-started/quick-start-pojo/index.html
3.9/driver/getting-started/quick-start-pojo/index.html

Sync the POJO quickstart doc with PojoQuickTour.java

---

docs/reference/content/driver/tutorials/perform-read-operations.md

JIRA:
https://jira.mongodb.org/browse/DOCS-13638

DOCS-13638: replace Block with Consumer

---

build.gradle
driver-scala/src/it/scala/org/mongodb/scala/BaseSpec.scala
driver-scala/src/it/scala/org/mongodb/scala/RequiresMongoDBISpec.scala
driver-scala/src/it/scala/org/mongodb/scala/documentation/DocumentationChangeStreamExampleSpec.scala
driver-scala/src/it/scala/org/mongodb/scala/documentation/DocumentationExampleSpec.scala
driver-scala/src/it/scala/org/mongodb/scala/documentation/DocumentationTransactionsExampleSpec.scala
driver-scala/src/it/scala/org/mongodb/scala/gridfs/GridFSObservableSpec.scala
driver-scala/src/it/scala/org/mongodb/scala/gridfs/GridFSSpec.scala
driver-scala/src/it/scala/org/mongodb/scala/syncadapter/SyncMongoClient.scala
driver-scala/src/it/scala/org/mongodb/scala/syncadapter/SyncMongoCursor.scala
driver-scala/src/it/scala/org/mongodb/scala/syncadapter/SyncMongoIterable.scala

* Configured gradle to set properties for Scala
* Added `@RunWith(classOf[JUnitRunner])` base trait for scala integration tests
* Normalized Scala time outs
https://spruce.mongodb.com/version/5f1feb5a3627e02b5ae72327/tasks

JAVA-3800: Scala: Ensure scalaTest tests are also run during integrationTest

---

build.gradle
driver-sync/src/test/functional/com/mongodb/client/JsonPoweredCrudTestHelper.java
driver-workload-executor/build.gradle
driver-workload-executor/src/main/com/mongodb/workload/WorkloadExecutor.java
driver-workload-executor/src/resources/logback.xml
gradle/publish.gradle

https://jira.mongodb.org/browse/JAVA-3201
Patch build in the drivers-atlas-testing project: https://spruce.mongodb.com/version/5f2b60bc850e611d15e2c51e/tasks
See also https://github.com/jyemin/drivers-atlas-testing/commit/fc8c05c39920583922396da031191a306228aafd for how it's invoked from Astrolabe

JAVA-3201: Add workload executor

---

docs/reference/content/bson/installation-guide.md
docs/reference/content/driver-reactive/getting-started/installation.md
docs/reference/content/driver-scala/getting-started/installation.md
docs/reference/content/driver/getting-started/installation.md
docs/reference/content/driver/tutorials/jndi.md

Docs: Delete beta from 4.1 install

---

driver-core/build.gradle

See issues :
- https://jira.mongodb.org/projects/JAVA/issues/JAVA-3829
- https://jira.mongodb.org/browse/JAVA-3656

JAVA-3829: Fix Import-Package entry for jdk.net 

---

driver-core/src/main/com/mongodb/client/model/Indexes.java

Hello
just some minor doc fix here, since i get a little confused about the descending index javadoc

Docs: fix descending and 2dsphere index Javadoc

---

.evergreen/.evg.yml
.evergreen/publish.sh
gradle/publish.gradle

Require ascii-armored signing key

---

docs/reference/content/upgrading.md

JAVA-3822 JAVA-3837
http://rozza.github.io/mongo-java-driver/3.12/upgrading/

Update compatibility for 3.12

---

driver-core/src/main/com/mongodb/WriteConcern.java
driver-core/src/test/unit/com/mongodb/WriteConcernSpecification.groovy

Removed unused fsync field from WriteConcern

---

.evergreen/run-gssapi-auth-test.sh
driver-core/src/main/com/mongodb/KerberosSubjectProvider.java
driver-core/src/main/com/mongodb/MongoCredential.java
driver-core/src/main/com/mongodb/SubjectProvider.java
driver-core/src/main/com/mongodb/internal/connection/GSSAPIAuthenticator.java
driver-core/src/main/com/mongodb/internal/connection/SaslAuthenticator.java
driver-core/src/test/functional/com/mongodb/KerberosSubjectProviderTest.java
driver-core/src/test/functional/com/mongodb/internal/connection/GSSAPIAuthenticationSpecification.groovy
driver-core/src/test/functional/com/mongodb/internal/connection/GSSAPIAuthenticatorSpecification.groovy
driver-scala/src/test/scala/org/mongodb/scala/ApiAliasAndCompanionSpec.scala

* Add SubjectProvider interface
* Add JAVA_SUBJECT_PROVIDER mechanism property
* Add KerberosSubjectProvider implementation
* Default to use KerberosSubjectProvider with "com.sun.security.jgss.krb5.initiate" LoginContext name
JAVA-3836

Support caching of Kerberos Subject

---

.evergreen/.evg.yml
.evergreen/run-tests.sh
build.gradle
docs/reference/content/driver-reactive/tutorials/client-side-encryption.md
docs/reference/content/driver/tutorials/client-side-encryption.md
driver-core/src/main/com/mongodb/AutoEncryptionSettings.java
driver-core/src/main/com/mongodb/ClientEncryptionSettings.java
driver-core/src/main/com/mongodb/client/model/vault/DataKeyOptions.java
driver-core/src/main/com/mongodb/internal/capi/MongoCryptHelper.java
driver-core/src/test/functional/com/mongodb/ClusterFixture.java
driver-core/src/test/functional/com/mongodb/internal/async/client/ClientSideEncryptionCorpusTest.java
driver-core/src/test/resources/client-side-encryption-corpus/corpus-encrypted.json
driver-core/src/test/resources/client-side-encryption-corpus/corpus-key-azure.json
driver-core/src/test/resources/client-side-encryption-corpus/corpus-key-gcp.json
driver-core/src/test/resources/client-side-encryption-corpus/corpus-schema.json
driver-core/src/test/resources/client-side-encryption-corpus/corpus.json
driver-core/src/test/resources/client-side-encryption/README.rst
driver-core/src/test/resources/client-side-encryption/azureKMS.json
driver-core/src/test/resources/client-side-encryption/gcpKMS.json
driver-core/src/test/resources/client-side-encryption/maxWireVersion.json
driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/ClientEncryptionCustomEndpointTest.java
driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/ClientEncryptionDataKeyAndDoubleEncryptionTest.java
driver-sync/src/test/functional/com/mongodb/client/AbstractClientSideEncryptionTest.java
driver-sync/src/test/functional/com/mongodb/client/ClientEncryptionCustomEndpointTest.java
driver-sync/src/test/functional/com/mongodb/client/ClientEncryptionDataKeyAndDoubleEncryptionTest.java
driver-sync/src/test/functional/com/mongodb/client/ClientSideEncryptionCorpusTest.java

Updated FLE spec tests to test Azure & Gcp

---

driver-core/src/main/com/mongodb/internal/operation/AsyncExplainableReadOperation.java
driver-core/src/main/com/mongodb/internal/operation/ExplainHelper.java
driver-core/src/main/com/mongodb/internal/operation/ExplainableReadOperation.java
driver-core/src/main/com/mongodb/internal/operation/FindOperation.java
driver-core/src/main/com/mongodb/internal/operation/SyncOperations.java
driver-core/src/test/functional/com/mongodb/internal/operation/FindOperationSpecification.groovy
driver-legacy/src/main/com/mongodb/DBCursor.java
driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/FindPublisher.java
driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/FindPublisherImpl.java
driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/ExplainTest.java
driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/syncadapter/SyncFindIterable.java
driver-scala/src/it/scala/org/mongodb/scala/syncadapter/SyncFindIterable.scala
driver-scala/src/main/scala/org/mongodb/scala/FindObservable.scala
driver-scala/src/test/scala/org/mongodb/scala/FindObservableSpec.scala
driver-sync/src/main/com/mongodb/client/FindIterable.java
driver-sync/src/main/com/mongodb/client/internal/FindIterableImpl.java
driver-sync/src/test/functional/com/mongodb/client/AbstractExplainTest.java
driver-sync/src/test/functional/com/mongodb/client/ExplainTest.java

Support is only for server versions 3.2+
JAVA-3909
Support for explain of aggregates will come in a subsequent PR

Support explain for find operations

---

docs/reference/content/driver-reactive/tutorials/aggregation.md
docs/reference/content/driver-reactive/tutorials/perform-read-operations.md
docs/reference/content/driver-scala/tutorials/aggregation.md
docs/reference/content/driver-scala/tutorials/perform-read-operations.md
docs/reference/content/driver/tutorials/aggregation.md
docs/reference/content/driver/tutorials/perform-read-operations.md

Add reference docs for explain of find and aggregate

---

docs/reference/content/driver/getting-started/quick-start-pojo.md
docs/reference/content/driver/getting-started/quick-start.md
docs/reference/content/driver/reference/monitoring.md
docs/reference/content/driver/tutorials/authentication.md
docs/reference/content/driver/tutorials/compression.md
docs/reference/content/driver/tutorials/connect-to-mongodb.md
docs/reference/content/driver/tutorials/ssl.md
docs/reference/content/upgrading.md

Update reference docs for legacy MongoClient API to use MongoClientSettings and ConnectionString

---

docs/reference/content/driver/getting-started/quick-start-pojo.md
docs/reference/content/driver/getting-started/quick-start.md
docs/reference/content/driver/tutorials/aggregation.md
docs/reference/content/driver/tutorials/change-streams.md
docs/reference/content/driver/tutorials/geospatial-search.md
docs/reference/content/driver/tutorials/gridfs.md
docs/reference/content/driver/tutorials/text-search.md

This class is no longer a part of the public API.
JAVA-3934

Remove mentions of the com.mongodb.Block class

---

docs/reference/content/driver-reactive/getting-started/quick-start-primer.md
docs/reference/content/driver-reactive/getting-started/quick-start.md
docs/reference/content/driver-scala/getting-started/quick-start.md

Docs: Reactive streams clarify cold publishers

---

driver-core/src/main/com/mongodb/ServerCursor.java

Document com.mongodb.ServerCursor with @Immutable

---

driver-core/src/main/com/mongodb/internal/binding/ReferenceCounted.java

Improve the documentation of the ReferenceCounted interface

---

driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/package-info.java
gradle/javadoc.gradle

Document publisher properties in API docs

---

driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/crypt/CryptBinding.java

Return `this` from CryptBinding.retain

---

driver-core/src/test/functional/com/mongodb/internal/binding/AsyncSessionBinding.java

Return `this` from retain methods in test code

---

driver-core/src/main/com/mongodb/internal/operation/AsyncChangeStreamBatchCursor.java
driver-core/src/main/com/mongodb/internal/operation/AsyncQueryBatchCursor.java
driver-core/src/test/functional/com/mongodb/internal/operation/AsyncQueryBatchCursorFunctionalSpecification.groovy
driver-core/src/test/unit/com/mongodb/internal/operation/AsyncQueryBatchCursorSpecification.groovy

Make implementations of AsyncAggregateResponseBatchCursor more responsive to close signals

---

driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/ChangeStreamsCancellationTest.java
driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/TestSubscriber.java

Ensures that all sessions are returned to the pool - and therefore the connections are released.
JAVA-3938 JAVA-3907

Regression test for change stream cancellation

---

.evergreen/.evg.yml
.evergreen/run-tests.sh
build.gradle
driver-core/src/test/functional/com/mongodb/ClusterFixture.java
driver-core/src/test/resources/client-side-encryption/README.rst
driver-core/src/test/resources/client-side-encryption/awsTemporary.json
driver-sync/src/test/functional/com/mongodb/client/AbstractClientSideEncryptionTest.java

Support AWS authentication with temporary credentials in CSFLE

---

driver-core/src/main/com/mongodb/internal/event/ConnectionPoolListenerMulticaster.java

Implement connectionCheckOutStarted in the ConnectionPoolListenerMulticaster

---

driver-core/src/main/com/mongodb/ClientEncryptionSettings.java

Javadoc: Update getKmsProviders description

---

driver-core/src/main/com/mongodb/internal/connection/SocketStreamHelper.java

This commit removes any assumptions that jdk.net.ExtendedSocketOptions
is available at all at runtime, since the jdk.net package is not actually
part of the standard library (though in practice it is usually available).
If it's not available, no TCP keep-alive options will be set, but socket
creation will proceed instead of failing with a ClassNotFoundException.
JAVA-4005

Remove assumption that jdk.net package is available

---

gradle.properties

Update Scala versions to latest patches

---

.evergreen/.evg.yml
driver-core/src/test/functional/com/mongodb/internal/connection/AwsAuthenticationSpecification.groovy

Re-enable AWS auth tests

---

driver-scala/src/main/scala/org/mongodb/scala/ListDatabasesObservable.scala
driver-scala/src/main/scala/org/mongodb/scala/MongoCollection.scala
driver-scala/src/main/scala/org/mongodb/scala/Observable.scala
driver-scala/src/main/scala/org/mongodb/scala/ObservableImplicits.scala
driver-scala/src/main/scala/org/mongodb/scala/model/Accumulators.scala
driver-scala/src/main/scala/org/mongodb/scala/model/Aggregates.scala
driver-scala/src/main/scala/org/mongodb/scala/model/MergeOptions.scala
driver-scala/src/main/scala/org/mongodb/scala/model/Projections.scala
driver-scala/src/main/scala/org/mongodb/scala/model/package.scala
driver-scala/src/main/scala/org/mongodb/scala/vault/ClientEncryption.scala
driver-scala/src/main/scala/org/mongodb/scala/vault/ClientEncryptions.scala
driver-scala/src/main/scala/org/mongodb/scala/vault/package.scala

Fix scaladoc warnings

---

driver-sync/src/examples/documentation/DocumentationSamples.java

Join the thread in DocumentationSamples.testWatch

---

driver-core/src/main/com/mongodb/BasicDBObject.java
driver-core/src/test/unit/com/mongodb/BasicDBObjectTest.java

Ensure BasicDBObject equals/hashCode works with UUID values

---

driver-core/src/main/com/mongodb/assertions/Assertions.java
driver-core/src/main/com/mongodb/internal/async/AsyncBatchCursor.java
driver-core/src/main/com/mongodb/internal/operation/AsyncChangeStreamBatchCursor.java
driver-core/src/main/com/mongodb/internal/operation/AsyncQueryBatchCursor.java
driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/internal/BatchCursorFluxTest.java

Guarantee that ChangeStreamPublisher for a collection completes after dropping the collection

---

driver-core/src/main/com/mongodb/internal/operation/CreateIndexesOperation.java
driver-core/src/test/resources/unified-test-format/valid-pass/poc-transactions.json

Stop including "ns" field in createIndex index specifications

---

driver-sync/src/test/functional/com/mongodb/client/unified/RunOnRequirementsMatcher.java

Fix NPE in RunOnRequirementsMatcher.runOnRequirementsMet

---

driver-core/src/test/resources/unified-test-format/valid-fail/assertNumberConnectionsCheckedOut.json
driver-core/src/test/resources/unified-test-format/valid-fail/entity-find-cursor.json
driver-core/src/test/resources/unified-test-format/valid-fail/ignoreResultAndError.json
driver-core/src/test/resources/unified-test-format/valid-pass/assertNumberConnectionsCheckedOut.json
driver-core/src/test/resources/unified-test-format/valid-pass/entity-client-cmap-events.json
driver-core/src/test/resources/unified-test-format/valid-pass/entity-find-cursor.json
driver-core/src/test/resources/unified-test-format/valid-pass/expectedEventsForClient-eventType.json
driver-core/src/test/resources/unified-test-format/valid-pass/ignoreResultAndError.json
driver-core/src/test/resources/unified-test-format/valid-pass/poc-retryable-writes.json
driver-core/src/test/unit/com/mongodb/internal/connection/TestConnectionPoolListener.java
driver-sync/src/test/functional/com/mongodb/client/unified/ContextElement.java
driver-sync/src/test/functional/com/mongodb/client/unified/Entities.java
driver-sync/src/test/functional/com/mongodb/client/unified/ErrorMatcher.java
driver-sync/src/test/functional/com/mongodb/client/unified/EventMatcher.java
driver-sync/src/test/functional/com/mongodb/client/unified/RunOnRequirementsMatcher.java
driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudHelper.java
driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java

Including support for some new operations as well as some missing arguments
for existing ones
Unified test runner spec change is here: https://github.com/mongodb/specifications/commit/ed4e62b48939378b814cbd7d9d4939a2c1076a6b#diff-79f3687b3ed70330328991908c1c47b9b3111be5c7629db524acbfb395c4ff7a
JAVA-4077

Support unified test runner schema version 1.3

---

.evergreen/run-mongodb-aws-ecs-test.sh

Update the package information before installing software in `run-mongodb-aws-ecs-test.sh`

---

driver-core/src/main/com/mongodb/ConnectionString.java
driver-core/src/test/resources/initial-dns-seedlist-discovery/load-balanced/loadBalanced-directConnection-errors.json
driver-core/src/test/resources/initial-dns-seedlist-discovery/load-balanced/loadBalanced-directConnection.json
driver-core/src/test/resources/uri-options/connection-options.json
driver-core/src/test/unit/com/mongodb/AbstractConnectionStringTest.java

Support directConnection=false with loadBalanced=true

---

driver-core/src/main/com/mongodb/internal/operation/AsyncChangeStreamBatchCursor.java
driver-core/src/main/com/mongodb/internal/operation/ChangeStreamBatchCursor.java

And also after extracting `resumeToken` from the received change stream documents; at least, this is consistent with the behaviour of `ChangeStreamBatchCursor`.
JAVA-4165

`AsyncChangeStreamBatchCursor` must cache `resumeToken` after completion of the async `cursor.next`/`tryNext` operation

---

driver-core/src/main/com/mongodb/internal/operation/AsyncChangeStreamBatchCursor.java
driver-core/src/main/com/mongodb/internal/operation/ChangeStreamBatchCursor.java

And also after extracting `resumeToken` from the received change stream documents (this is also consistent with the behaviour of `ChangeStreamBatchCursor`). Both updates to `resumeToken` must happen before completing the callback supplied to `AsyncChangeStreamBatchCursor.next`/`tryNext`.
A backport of https://github.com/mongodb/mongo-java-driver/pull/713 (all merge conflicts were resolved automatically).
JAVA-4166

`AsyncChangeStreamBatchCursor` must cache `resumeToken` after completion of the async `cursor.next`/`tryNext` operation (#713)

---

driver-core/src/test/functional/com/mongodb/internal/operation/QueryOperationHelper.groovy
driver-legacy/src/test/functional/com/mongodb/DBCursorFunctionalSpecification.groovy

JAVA-4169
This accounts for four of the tests now failing against latest

Update integration tests to account for new explain command reply format

---

driver-core/src/main/com/mongodb/connection/ServerDescription.java
driver-core/src/main/com/mongodb/internal/connection/CommandMessage.java
driver-core/src/main/com/mongodb/internal/connection/DefaultServerMonitor.java
driver-core/src/main/com/mongodb/internal/connection/DescriptionHelper.java
driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnectionInitializer.java
driver-core/src/test/resources/connection-monitoring-and-pooling/pool-checkout-maxConnecting-is-enforced.json
driver-core/src/test/resources/connection-monitoring-and-pooling/pool-checkout-maxConnecting-timeout.json
driver-core/src/test/resources/connection-monitoring-and-pooling/pool-checkout-returned-connection-maxConnecting.json
driver-core/src/test/resources/server-discovery-and-monitoring-integration/connectTimeoutMS.json
driver-core/src/test/resources/server-discovery-and-monitoring-integration/isMaster-command-error.json
driver-core/src/test/resources/server-discovery-and-monitoring-integration/isMaster-network-error.json
driver-core/src/test/resources/server-discovery-and-monitoring-integration/isMaster-timeout.json
driver-core/src/test/unit/com/mongodb/internal/connection/InternalStreamConnectionInitializerSpecification.groovy
driver-core/src/test/unit/com/mongodb/internal/connection/MessageHelper.java
driver-core/src/test/unit/com/mongodb/internal/connection/NativeAuthenticatorUnitTest.java
driver-core/src/test/unit/com/mongodb/internal/connection/PlainAuthenticatorUnitTest.java
driver-core/src/test/unit/com/mongodb/internal/connection/X509AuthenticatorNoUserNameTest.java
driver-core/src/test/unit/com/mongodb/internal/connection/X509AuthenticatorUnitTest.java
driver-sync/src/test/functional/com/mongodb/client/ServerDiscoveryAndMonitoringProseTests.java

There are two scenarios where "hello" command can be used:
1. When the application declares an API version
3. When the response to "ismaster" contains helloOk: true
Additionally, use OP_MSG when the application declares an API version,
even when maxWireVersion is unknown during the handshake
JAVA-4092
JAVA-4157

Use "hello" command where possible

---

.evergreen/.evg.yml

Add 5.0 to test matrix

---

driver-core/src/main/com/mongodb/MongoWriteException.java
driver-sync/src/test/functional/com/mongodb/client/CrudProseTest.java

Implement new CRUD specification prose test for write error details
JAVA-3993

Ensure write error is included in exception message

---

driver-core/src/main/com/mongodb/client/model/CreateCollectionOptions.java
driver-core/src/main/com/mongodb/client/model/TimeSeriesGranularity.java
driver-core/src/main/com/mongodb/client/model/TimeSeriesOptions.java
driver-core/src/main/com/mongodb/internal/operation/CreateCollectionOperation.java
driver-core/src/test/resources/unified-test-format/collection-management/timeseries-collection.json
driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/MongoOperationPublisher.java
driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/unified/CollectionManagementTest.java
driver-scala/src/main/scala/org/mongodb/scala/model/package.scala
driver-sync/src/main/com/mongodb/client/internal/MongoDatabaseImpl.java
driver-sync/src/test/functional/com/mongodb/client/unified/CollectionManagementTest.java
driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudHelper.java

Support creation of time-series collections

---

driver-core/src/test/resources/unified-test-format/command-monitoring/redacted-commands.json
driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/unified/CommandMonitoringTest.java
driver-sync/src/test/functional/com/mongodb/client/unified/CommandMonitoringTest.java

Implement command monitoring redaction tests

---

driver-core/src/main/com/mongodb/internal/async/AsyncBatchCursor.java
driver-core/src/main/com/mongodb/internal/operation/AsyncChangeStreamBatchCursor.java
driver-core/src/main/com/mongodb/internal/operation/AsyncQueryBatchCursor.java
driver-core/src/main/com/mongodb/internal/operation/AsyncSingleBatchQueryCursor.java
driver-core/src/main/com/mongodb/internal/operation/ListCollectionsOperation.java
driver-core/src/test/functional/com/mongodb/OperationFunctionalSpecification.groovy
driver-core/src/test/functional/com/mongodb/internal/operation/AggregateOperationSpecification.groovy
driver-core/src/test/functional/com/mongodb/internal/operation/ChangeStreamOperationSpecification.groovy
driver-core/src/test/functional/com/mongodb/internal/operation/ListCollectionsOperationSpecification.groovy
driver-core/src/test/unit/com/mongodb/internal/operation/AsyncChangeStreamBatchCursorSpecification.groovy
driver-core/src/test/unit/com/mongodb/internal/operation/AsyncQueryBatchCursorSpecification.groovy
driver-core/src/test/unit/com/mongodb/internal/operation/AsyncSingleBatchQueryCursorSpecification.groovy
driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/BatchCursor.java

Remove unused async cursor tryNext support 

---

driver-core/src/main/com/mongodb/internal/connection/tlschannel/ServerTlsChannel.java
driver-core/src/main/com/mongodb/internal/connection/tlschannel/async/AsynchronousTlsChannelGroup.java
driver-core/src/main/com/mongodb/internal/connection/tlschannel/impl/BufferHolder.java
driver-core/src/main/com/mongodb/internal/connection/tlschannel/impl/TlsChannelImpl.java
driver-core/src/main/com/mongodb/internal/connection/tlschannel/util/DirectBufferDeallocator.java
driver-core/src/main/com/mongodb/internal/connection/tlschannel/util/Util.java

Fixed Logging in vendored tlschannel

---

driver-core/src/test/resources/uri-options/connection-pool-options.json
driver-core/src/test/unit/com/mongodb/AbstractConnectionStringTest.java

Two commits:
1. Implement the new spec tests
2. Clean up the numerous warnings in the test class 
JAVA-4160
This PR is pretty low priority, as it's not required for the 4.3 release

Add URI options spec tests for minPoolSize/maxPoolSize of 0 

---

driver-legacy/src/main/com/mongodb/MongoClient.java
driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/MongoClientImpl.java
driver-sync/src/main/com/mongodb/client/internal/MongoClientDelegate.java

Ensure MongoClient#close only actions on first call

---

docs/reference/content/driver-scala/tutorials/client-side-encryption.md
driver-core/src/main/com/mongodb/MongoClientSettings.java
driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/vault/ClientEncryption.java
driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/vault/ClientEncryptions.java
driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/vault/package-info.java
driver-scala/src/main/scala/org/mongodb/scala/vault/ClientEncryption.scala
driver-scala/src/main/scala/org/mongodb/scala/vault/ClientEncryptions.scala
driver-scala/src/main/scala/org/mongodb/scala/vault/package.scala
driver-sync/src/main/com/mongodb/client/vault/package-info.java

JAVA-4226
I grepped for "beta" in the entire project so I think I found everything.

Remove Beta annotation from remaining client side encryption-related classes

---

driver-core/src/test/resources/unified-test-format/command-monitoring/redacted-commands.json
driver-sync/src/test/functional/com/mongodb/client/unified/Entities.java
driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java

Test redaction of replies to security-sensitive commands

---

docs/reference/themes/mongodb/layouts/partials/header.html
docs/reference/themes/mongodb/layouts/partials/header/newSiteNotice.html

fix template syntax and url

---

docs/reference/themes/mongodb/layouts/partials/header.html

to all top level pages other than the index, apidocs, driver-scala, driver-reactive

Extend notice scope

---

docs/reference/content/driver-reactive/tutorials/compression.md
docs/reference/content/driver-scala/tutorials/compression.md
docs/reference/content/driver/tutorials/compression.md
docs/reference/content/driver/tutorials/gridfs.md
docs/reference/content/whats-new.md
docs/reference/themes/mongodb/static/js/navbar.js
docs/reference/themes/mongodb/static/js/underscore.js

Remove use of master/whitelist/blacklist from reference docs

---

bson/src/main/org/bson/codecs/pojo/LazyPropertyModelCodec.java

To avoid race conditions `LazyPropertyModelCodec#getPropertyModelCodec` is made synchronized earlier. But all that it does is caching a codec on a first invocation. On subsequent calls it just returns the cached value. In case when the same POJO is requested from Mongo DB very often by different threads, having the whole method synchronized might be a bit excessive or rather wasteful (too many context switches, time spent in locks, etc). 
A simple solution with double check locking should help here and can improve total performance of the method in case concurrent requests
Here is just an example from JFR report for one of our applications

Relax synchronized block in LazyPropertyModelCodec when a codec is retrieved

---

driver-reactive-streams/build.gradle
driver-reactive-streams/src/test/tck/com/mongodb/reactivestreams/client/ListDatabasesPublisherVerification.java
driver-reactive-streams/src/test/tck/com/mongodb/reactivestreams/client/PublishersVerification.java
driver-reactive-streams/src/test/tck/com/mongodb/reactivestreams/client/gridfs/GridFSDownloadPublisherVerification.java
driver-reactive-streams/src/test/tck/com/mongodb/reactivestreams/client/gridfs/GridFSFindPublisherVerification.java
driver-reactive-streams/src/test/tck/com/mongodb/reactivestreams/client/gridfs/GridFSUploadPublisherVerification.java

Ensure tckTests run

---

driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnection.java
driver-core/src/test/functional/com/mongodb/internal/connection/TestCommandListener.java
driver-core/src/test/resources/unified-test-format/valid-pass/observeSensitiveCommands.json
driver-sync/src/test/functional/com/mongodb/client/unified/Entities.java

Support observeSensitiveCommands config in unified test runner

---

.evergreen/.evg.yml
.evergreen/run-kms-tls-tests.sh
driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/ClientSideEncryptionKmsTlsTest.java
driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/syncadapter/SyncClientEncryption.java
driver-scala/src/test/scala/org/mongodb/scala/ApiAliasAndCompanionSpec.scala
driver-sync/src/test/functional/com/mongodb/client/AbstractClientSideEncryptionKmsTlsTest.java
driver-sync/src/test/functional/com/mongodb/client/ClientSideEncryptionKmsTlsTest.java

Implement tests for invalid KMS TLS certificates

---

driver-core/src/main/com/mongodb/internal/connection/ScramShaAuthenticator.java
driver-core/src/test/unit/com/mongodb/internal/connection/InternalStreamConnectionInitializerSpecification.groovy
driver-core/src/test/unit/com/mongodb/internal/connection/ScramShaAuthenticatorSpecification.groovy

Ensure speculative auth uses the credentials auth source.

---

bson/src/test/resources/bson/code.json
bson/src/test/resources/bson/symbol.json
bson/src/test/unit/org/bson/GenericBsonTest.java

Enhance check for UTF-8 replacement character to include more BSON types
JAVA-4263

Update BSON specification tests

---

bson/src/main/org/bson/BsonDocument.java
bson/src/test/resources/bson/document.json
bson/src/test/resources/bson/regex.json
bson/src/test/resources/bson/top.json
bson/src/test/unit/org/bson/BsonBinaryWriterTest.java
bson/src/test/unit/org/bson/BsonWriterSpecification.groovy
bson/src/test/unit/org/bson/GenericBsonTest.java

The driver already has the necessary checks. This is just adding tests
JAVA-4236

Test for null byte in BSON cstring

---

driver-scala/src/main/scala/org/mongodb/scala/Observable.scala
driver-scala/src/main/scala/org/mongodb/scala/internal/CollectObservable.scala
driver-scala/src/test/scala/org/mongodb/scala/internal/CollectObservableTest.scala

[JAVA-4312](https://jira.mongodb.org/browse/JAVA-4312)

[JAVA-4312] Add standard Scala collections collect method

---

.evergreen/run-mongodb-aws-test.sh
driver-core/src/main/com/mongodb/AwsCredential.java
driver-core/src/main/com/mongodb/MongoCredential.java
driver-core/src/main/com/mongodb/internal/connection/AwsAuthenticator.java
driver-core/src/test/functional/com/mongodb/internal/connection/AwsAuthenticationSpecification.groovy
driver-scala/src/test/scala/org/mongodb/scala/ApiAliasAndCompanionSpec.scala

Support callback for AWS credentials

---

driver-scala/src/main/scala/org/mongodb/scala/internal/FilterObservable.scala
driver-scala/src/main/scala/org/mongodb/scala/internal/FlatMapObservable.scala
driver-scala/src/main/scala/org/mongodb/scala/internal/FoldLeftObservable.scala
driver-scala/src/main/scala/org/mongodb/scala/internal/MapObservable.scala
driver-scala/src/test/scala/org/mongodb/scala/internal/FlatMapObservableTest.scala
driver-scala/src/test/scala/org/mongodb/scala/internal/ObservableImplementationSpec.scala

Should handle errors from user functions gracefully
JAVA-4304

Scala Observables fix

---

gradle/publish.gradle

Fix mongodb-driver-legacy MANIFEST.MF

---

.evergreen/.evg.yml
.evergreen/compile.sh
.evergreen/publish.sh
.evergreen/run-ocsp-test.sh
.evergreen/run-scala-tests.sh

* Mostly testing with Java 8 and 17 now
* Limited testing with Java 11
JAVA-4358
Full patch build: https://spruce.mongodb.com/version/6176b137a4cf47118a95b640/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

Test with Java 17

---

driver-core/src/main/com/mongodb/internal/selector/ReadPreferenceWithFallbackServerSelector.java
driver-core/src/test/unit/com/mongodb/internal/selector/ReadPreferenceWithFallbackServerSelectorTest.java

Update and test server selection logic for $out/$merge aggregation pipelines

---

driver-core/src/test/resources/connection-monitoring-and-pooling/pool-checkout-custom-maxConnecting-is-enforced.json
driver-core/src/test/resources/uri-options/connection-pool-options.json
driver-core/src/test/unit/com/mongodb/AbstractConnectionStringTest.java
driver-core/src/test/unit/com/mongodb/internal/connection/AbstractConnectionPoolTest.java

The implementation of the `maxConnecting` options was done in JAVA-4390.
JAVA-4405

Implement `maxConnecting` tests from DRIVERS-1943

---

.evergreen/.evg.yml
.evergreen/run-gssapi-auth-test.sh
build.gradle
driver-core/src/main/com/mongodb/KerberosSubjectProvider.java
driver-core/src/test/functional/com/mongodb/ClusterFixture.java
driver-core/src/test/functional/com/mongodb/KerberosSubjectProviderTest.java
driver-core/src/test/functional/com/mongodb/internal/connection/GSSAPIAuthenticationSpecification.groovy
driver-core/src/test/functional/com/mongodb/internal/connection/GSSAPIAuthenticatorSpecification.groovy

JAVA-4391
Straightforward change except for testing it.

Support "com.sun.security.jgss.initiate" as Kerberos login context name

---

driver-scala/src/it/scala/org/mongodb/scala/ClientSideEncryptionBypassAutoEncryptionSpec.scala
driver-scala/src/it/scala/org/mongodb/scala/RequiresMongoDBISpec.scala
driver-scala/src/it/scala/org/mongodb/scala/TestMongoClientHelper.scala
driver-scala/src/it/scala/org/mongodb/scala/documentation/DocumentationExampleSpec.scala
driver-scala/src/it/scala/org/mongodb/scala/documentation/DocumentationTransactionsExampleSpec.scala
driver-scala/src/it/scala/org/mongodb/scala/gridfs/GridFSObservableSpec.scala

Ensure MongoClient instances are closed in Scala tests

---

.evergreen/.evg.yml

Remove unnecessary S3 uploads in Evergreen variants

---

config/checkstyle/suppressions.xml
driver-core/src/main/com/mongodb/ConnectionString.java
driver-core/src/main/com/mongodb/connection/ClusterSettings.java
driver-core/src/main/com/mongodb/internal/connection/DefaultDnsSrvRecordMonitor.java
driver-core/src/main/com/mongodb/internal/connection/DefaultDnsSrvRecordMonitorFactory.java
driver-core/src/main/com/mongodb/internal/connection/DnsMultiServerCluster.java
driver-core/src/main/com/mongodb/internal/connection/DnsSrvRecordMonitorFactory.java
driver-core/src/main/com/mongodb/internal/connection/LoadBalancedCluster.java
driver-core/src/main/com/mongodb/internal/dns/DefaultDnsResolver.java
driver-core/src/main/com/mongodb/internal/dns/DnsResolver.java
driver-core/src/test/unit/com/mongodb/AbstractConnectionStringTest.java
driver-core/src/test/unit/com/mongodb/UriOptionsTest.java
driver-core/src/test/unit/com/mongodb/connection/ClusterSettingsSpecification.groovy
driver-core/src/test/unit/com/mongodb/internal/connection/DefaultDnsSrvRecordMonitorSpecification.groovy
driver-core/src/test/unit/com/mongodb/internal/connection/DnsMultiServerClusterSpecification.groovy
driver-core/src/test/unit/com/mongodb/internal/connection/LoadBalancedClusterTest.java
driver-core/src/test/unit/com/mongodb/internal/connection/SrvPollingProseTests.java
driver-legacy/src/main/com/mongodb/MongoClientOptions.java
driver-legacy/src/main/com/mongodb/MongoClientURI.java
driver-legacy/src/test/unit/com/mongodb/MongoClientOptionsSpecification.groovy
driver-legacy/src/test/unit/com/mongodb/MongoClientURISpecification.groovy
driver-sync/src/test/functional/com/mongodb/client/InitialDnsSeedlistDiscoveryTest.java

Support srvServiceName option for SRV lookups

---

driver-core/src/main/com/mongodb/internal/connection/tlschannel/async/AsynchronousTlsChannelGroup.java

See the bug report https://github.com/marianobarrios/tls-channel/issues/34
and the two PRs from which the changes were manually merged:
- https://github.com/marianobarrios/tls-channel/pull/35/
- https://github.com/marianobarrios/tls-channel/pull/36
JAVA-4417

Merge changes from tls-channel for race condition manifested when closing async sockets right after creation

---

driver-sync/src/main/com/mongodb/client/gridfs/GridFSBucket.java

Document flush-related behavior of GridFSBucket.downloadToStream

---

driver-legacy/src/main/com/mongodb/CommandResult.java
driver-legacy/src/main/com/mongodb/DB.java
driver-legacy/src/main/com/mongodb/DBCollection.java
driver-legacy/src/test/functional/com/mongodb/DBTest.java
driver-legacy/src/test/unit/com/mongodb/CommandResultTest.java
driver-legacy/src/test/unit/com/mongodb/DBSpecification.groovy

Apply configured uuid representation to DB#command encoding and decoding

---

.evergreen/.evg.yml
driver-core/src/main/com/mongodb/internal/connection/DescriptionHelper.java
driver-core/src/test/functional/com/mongodb/ClusterFixture.java

Remove serviceId hack for load balancer testing

---

driver-sync/src/test/functional/com/mongodb/client/ServerDiscoveryAndMonitoringProseTests.java

The changes in this PR change the test such that it does not rely on non-existing ordering relations. However, we still have to disable the test because sone ordering relations expected by the corresponding SDAM prose scenario are not expressed in the specs and do not currently exist in the driver. See JAVA-4483 for more details.
JAVA-4483
P.S. I run the modified test before disabling it, and it mostly works, unless I introduce an artificial delay that makes it fail as a result of the aforementioned lack of ordering that is checked by the test scenario.

Fix ServerDiscoveryAndMonitoringProseTests.testConnectionPoolManagement and disable it

---

driver-core/src/main/com/mongodb/internal/connection/CommandMessage.java
driver-core/src/test/unit/com/mongodb/internal/connection/CommandMessageSpecification.groovy

Use OP_MSG when connecting to load balancer

---

driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnection.java

This change was extracted from https://github.com/mongodb/mongo-java-driver/pull/883.

Refactor buffer cleaning in `InternalStreamConnection.sendAndReceive`

---

driver-core/src/main/com/mongodb/internal/connection/AbstractMultiServerCluster.java
driver-core/src/test/resources/server-discovery-and-monitoring/rs/electionId_precedence_setVersion.json
driver-core/src/test/resources/server-discovery-and-monitoring/rs/electionId_setVersion.json
driver-core/src/test/resources/server-discovery-and-monitoring/rs/null_election_id.json
driver-core/src/test/resources/server-discovery-and-monitoring/rs/set_version_can_rollback.json
driver-core/src/test/resources/server-discovery-and-monitoring/rs/setversion_equal_max_without_electionid.json
driver-core/src/test/resources/server-discovery-and-monitoring/rs/setversion_greaterthan_max_without_electionid.json
driver-core/src/test/resources/server-discovery-and-monitoring/rs/setversion_without_electionid.json

Prioritize electionId over setVersion when updating topology

---

driver-core/src/main/com/mongodb/internal/connection/SocketStream.java

Ensure buffer is released on exception in SocketStream#read

---

driver-benchmarks/src/main/com/mongodb/benchmark/benchmarks/AbstractBsonDocumentBenchmark.java
driver-core/src/main/com/mongodb/connection/AsynchronousSocketChannelStreamFactory.java
driver-core/src/main/com/mongodb/connection/SocketStreamFactory.java
driver-core/src/main/com/mongodb/connection/TlsChannelStreamFactoryFactory.java
driver-core/src/main/com/mongodb/internal/connection/PowerOfTwoBufferPool.java
driver-core/src/test/unit/com/mongodb/internal/connection/PowerOfTwoBufferPoolTest.java
driver-legacy/src/main/com/mongodb/DB.java
driver-legacy/src/main/com/mongodb/DBCollection.java
driver-legacy/src/main/com/mongodb/DBCursor.java
driver-legacy/src/main/com/mongodb/MongoClient.java

Make buffer pool shared and support pruning

---

driver-core/src/main/com/mongodb/internal/dns/DefaultDnsResolver.java

Ignore NXDomain errors when looking up a TXT record

---

driver-core/src/main/com/mongodb/internal/operation/BaseFindAndModifyOperation.java
driver-core/src/main/com/mongodb/internal/operation/FindAndDeleteOperation.java
driver-core/src/main/com/mongodb/internal/operation/FindAndReplaceOperation.java
driver-core/src/main/com/mongodb/internal/operation/FindAndUpdateOperation.java

Reduced duplication in the FindAndModify operations

---

driver-core/src/main/com/mongodb/internal/operation/AsyncQueryBatchCursor.java
driver-core/src/main/com/mongodb/internal/operation/QueryBatchCursor.java
driver-core/src/test/resources/unified-test-format/crud/aggregate.json
driver-core/src/test/resources/unified-test-format/crud/find-comment.json

JAVA-4507
DRIVERS-2214
DRIVERS-2243

Ensure getMore comments only sent if server >= 4.4.0

---

driver-core/src/main/com/mongodb/internal/dns/DefaultDnsResolver.java
driver-core/src/main/com/mongodb/internal/dns/JndiDnsClient.java
driver-core/src/main/com/mongodb/spi/dns/DnsClient.java
driver-core/src/main/com/mongodb/spi/dns/DnsClientProvider.java
driver-core/src/main/com/mongodb/spi/dns/DnsException.java
driver-core/src/main/com/mongodb/spi/dns/DnsWithResponseCodeException.java
driver-core/src/main/com/mongodb/spi/dns/package-info.java
driver-scala/src/test/scala/org/mongodb/scala/ApiAliasAndCompanionSpec.scala

Default to existing JNDI-based implementation
JAVA-4512

Lookup DnsClientProvider via ServiceLoader

---

driver-core/src/main/com/mongodb/internal/connection/AbstractMultiServerCluster.java

Remove redundant logging of maxElectionId/maxSetVersion

---

driver-sync/src/examples/tour/ClientSideEncryptionAutoEncryptionSettingsTour.java
driver-sync/src/examples/tour/ClientSideEncryptionSimpleTour.java

[DOCSP-21585](https://jira.mongodb.org/browse/DOCSP-21585), remove admin database from CSFLE samples.

Update Key Vault Namespace

---

README.md

1. Replace "Settings" with "Settings/Preferences"
* Reference: https://www.jetbrains.com/help/idea/settings-preferences-dialog.html
2. Update the procedure of generating a build config
* Reference: https://www.jetbrains.com/help/idea/work-with-gradle-projects.html#delegate_build_gradle

Update REAME.md to adapt the latest version of IDEA

---

.evergreen/.evg.yml

Add 6.0 to testing matrix

---

driver-core/src/test/resources/unified-test-format/crud/bulkWrite-comment.json
driver-core/src/test/resources/unified-test-format/crud/countDocuments-comment.json
driver-core/src/test/resources/unified-test-format/crud/deleteMany-comment.json
driver-core/src/test/resources/unified-test-format/crud/deleteOne-comment.json
driver-core/src/test/resources/unified-test-format/crud/insertMany-comment.json
driver-core/src/test/resources/unified-test-format/crud/insertOne-comment.json
driver-core/src/test/resources/unified-test-format/crud/replaceOne-comment.json
driver-core/src/test/resources/unified-test-format/crud/updateMany-comment.json
driver-core/src/test/resources/unified-test-format/crud/updateOne-comment.json
driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudHelper.java

Update comment-related spec tests

---

driver-scala/src/main/scala/org/mongodb/scala/model/package.scala
driver-scala/src/test/scala/org/mongodb/scala/model/ModelSpec.scala

Add missing constructors for Scala write model classes

---

driver-core/src/main/com/mongodb/client/model/ClusteredIndexOptions.java
driver-core/src/main/com/mongodb/client/model/CreateCollectionOptions.java
driver-core/src/main/com/mongodb/internal/operation/CreateCollectionOperation.java
driver-core/src/test/resources/unified-test-format/collection-management/clustered-indexes.json
driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/MongoOperationPublisher.java
driver-scala/src/main/scala/org/mongodb/scala/model/package.scala
driver-sync/src/main/com/mongodb/client/internal/MongoDatabaseImpl.java
driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudHelper.java

Support clustered index on a collection

---

driver-core/src/main/com/mongodb/client/model/ChangeStreamPreAndPostImagesOptions.java
driver-core/src/main/com/mongodb/client/model/CreateCollectionOptions.java
driver-core/src/main/com/mongodb/internal/operation/CreateCollectionOperation.java
driver-core/src/test/resources/unified-test-format/collection-management/createCollection-pre_and_post_images.json
driver-core/src/test/resources/unified-test-format/collection-management/modifyCollection-pre_and_post_images.json
driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/MongoOperationPublisher.java
driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/unified/CollectionManagementTest.java
driver-scala/src/main/scala/org/mongodb/scala/model/package.scala
driver-sync/src/main/com/mongodb/client/internal/MongoDatabaseImpl.java
driver-sync/src/test/functional/com/mongodb/client/unified/CollectionManagementTest.java
driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudHelper.java

The only option at this time is "enabled".
JAVA-4592

Support change stream pre- and post- images options

---

driver-sync/src/main/com/mongodb/client/MongoCollection.java

This PR addresses JAVA-2499 and is my first contribution to open source!

[JAVA-2499] Add additional Javadoc comments to MongoCollection#insertMany

---

driver-core/src/test/resources/client-side-encryption/noSchema.json
driver-sync/src/test/functional/com/mongodb/client/AbstractClientSideEncryptionTest.java

CSFLE - Added noSchema test

---

driver-core/src/main/com/mongodb/client/model/changestream/ChangeStreamDocument.java
driver-core/src/test/resources/unified-test-format/change-streams/change-streams.json
driver-core/src/test/unit/com/mongodb/client/model/changestream/ChangeStreamDocumentCodecSpecification.groovy
driver-core/src/test/unit/com/mongodb/client/model/changestream/ChangeStreamDocumentSpecification.groovy

Add wallTime property to ChangeStreamDocument

---

driver-core/src/main/com/mongodb/internal/connection/IdHoldingBsonWriter.java

Remove unnecessary buffer allocation in IdHoldingBsonWriter

---

config/checkstyle/suppressions.xml
driver-core/src/main/com/mongodb/client/model/changestream/ChangeStreamDocument.java
driver-core/src/test/unit/com/mongodb/client/model/changestream/ChangeStreamDocumentCodecSpecification.groovy
driver-core/src/test/unit/com/mongodb/client/model/changestream/ChangeStreamDocumentSpecification.groovy

Support extra elements in ChangeStreamDocument

---

driver-core/src/test/functional/com/mongodb/JsonTestServerVersionChecker.java
driver-core/src/test/resources/client-side-encryption/fle2-Compact.json
driver-legacy/src/test/functional/com/mongodb/ClientSideEncryptionLegacyTest.java
driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/ClientSideEncryptionTest.java
driver-scala/src/it/scala/org/mongodb/scala/ClientSideEncryptionTest.scala
driver-sync/src/test/functional/com/mongodb/client/AbstractClientSideEncryptionTest.java
driver-sync/src/test/functional/com/mongodb/client/ClientSideEncryptionTest.java

Added test for compactStructuredEncryptionData

---

driver-core/src/test/unit/com/mongodb/client/model/search/SearchFuzzyTest.java
driver-core/src/test/unit/com/mongodb/client/model/search/SearchHighlightTest.java
driver-core/src/test/unit/com/mongodb/client/model/search/SearchOperatorTest.java
driver-core/src/test/unit/com/mongodb/client/model/search/SearchScoreExpressionTest.java
driver-core/src/test/unit/com/mongodb/client/model/search/SearchScoreTest.java

I missed the concerns expressed in https://github.com/mongodb/mongo-java-driver/pull/928#pullrequestreview-956423461, this PR addressed them.

Improve/fix search API tests

---

driver-core/src/main/com/mongodb/internal/connection/PowerOfTwoBufferPool.java

Lock free buffer pool

---

driver-legacy/src/test/functional/com/mongodb/MongoClientSessionSpecification.groovy
driver-sync/src/test/functional/com/mongodb/client/MongoClientSessionSpecification.groovy

To avoid interference between tests, poll the database until
the unacknowledged write is present in the collection. This
is intended to avoid SnapshotUnavailable errors from being
reported by the server.
JAVA-4637

Wait for unacknowledged write to complete

---

bson/src/test/unit/org/bson/codecs/pojo/entities/ConventionModel.java

https://jira.mongodb.org/browse/JAVA-4655

Fix ConventionModel constructor

---

driver-core/src/main/com/mongodb/ConnectionString.java
driver-legacy/src/main/com/mongodb/MongoClientOptions.java
driver-legacy/src/main/com/mongodb/MongoClientURI.java

Clarify that `socketTimeoutMS` affects only reads

---

driver-core/src/main/com/mongodb/internal/operation/DistinctOperation.java
driver-core/src/test/resources/unified-test-format/crud/distinct-comment.json
driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudHelper.java

JAVA-4627
Based on https://github.com/mongodb/mongo-php-library/pull/940/files

Add comment option tests for distinct helper

---

driver-scala/src/it/scala/org/mongodb/scala/syncadapter/SyncChangeStreamIterable.scala

Add missing showExpandedEvents to .scala

---

driver-core/src/main/com/mongodb/client/model/Aggregates.java
driver-core/src/main/com/mongodb/client/model/MongoTimeUnit.java
driver-core/src/main/com/mongodb/client/model/WindowOutputField.java
driver-core/src/main/com/mongodb/client/model/WindowOutputFields.java
driver-core/src/main/com/mongodb/client/model/Windows.java
driver-core/src/main/com/mongodb/client/model/fill/FillConstructibleBsonElement.java
driver-core/src/main/com/mongodb/client/model/fill/FillOptions.java
driver-core/src/main/com/mongodb/client/model/fill/FillOutputField.java
driver-core/src/main/com/mongodb/client/model/fill/LinearFillOutputField.java
driver-core/src/main/com/mongodb/client/model/fill/LocfFillOutputField.java
driver-core/src/main/com/mongodb/client/model/fill/ValueFillOutputField.java
driver-core/src/main/com/mongodb/client/model/fill/package-info.java
driver-core/src/test/functional/com/mongodb/client/model/AggregatesFunctionalSpecification.groovy
driver-core/src/test/unit/com/mongodb/client/model/AggregatesSpecification.groovy
driver-core/src/test/unit/com/mongodb/client/model/TestWindowOutputFields.java
driver-core/src/test/unit/com/mongodb/client/model/fill/FillOutputFieldTest.java
driver-scala/src/main/scala/org/mongodb/scala/model/Aggregates.scala
driver-scala/src/main/scala/org/mongodb/scala/model/WindowOutputFields.scala
driver-scala/src/main/scala/org/mongodb/scala/model/Windows.scala
driver-scala/src/main/scala/org/mongodb/scala/model/fill/FillOutputField.scala
driver-scala/src/main/scala/org/mongodb/scala/model/fill/fill.scala
driver-scala/src/main/scala/org/mongodb/scala/model/package.scala
driver-scala/src/test/scala/org/mongodb/scala/model/AggregatesSpec.scala

Renamed to closer match the documentation terminology
for the fields.
JAVA-4665
See: 
- https://www.mongodb.com/docs/manual/reference/operator/aggregation/setWindowFields/#syntax
- https://www.mongodb.com/docs/upcoming/reference/operator/aggregation/fill/#syntax

Renamed Computation interfaces / classes

---

driver-core/src/test/functional/com/mongodb/client/test/CollectionHelper.java
driver-core/src/test/resources/server-discovery-and-monitoring-integration/hello-command-error.json
driver-core/src/test/resources/server-discovery-and-monitoring-integration/hello-network-error.json
driver-core/src/test/resources/server-discovery-and-monitoring-integration/hello-timeout.json
driver-core/src/test/resources/server-discovery-and-monitoring-integration/rediscover-quickly-after-step-down.json
driver-sync/src/test/functional/com/mongodb/client/AbstractUnifiedTest.java

Add support for readPreference argument to runAdminCommand
JAVA-4677

Sync server discovery integration spec tests

---

.evergreen/.evg.yml

Write empty prepare_mongodb_aws so no auth environment variables are set

---

driver-core/src/main/com/mongodb/client/model/vault/RewrapManyDataKeyOptions.java
driver-core/src/main/com/mongodb/internal/capi/MongoCryptHelper.java
driver-core/src/test/functional/com/mongodb/internal/capi/MongoCryptHelperTest.java
driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/vault/ClientEncryptionImpl.java
driver-sync/src/main/com/mongodb/client/internal/ClientEncryptionImpl.java

Ensure that the provider exists if a master key has been provided.
JAVA-4717

Validate RewrapManyDataKeyOptions

---

build.gradle

Update project dependencies

---

driver-core/src/main/com/mongodb/AutoEncryptionSettings.java
driver-core/src/main/com/mongodb/MongoClientSettings.java
driver-core/src/main/com/mongodb/client/model/CreateCollectionOptions.java
driver-core/src/main/com/mongodb/client/model/DropCollectionOptions.java
driver-scala/src/main/scala/org/mongodb/scala/AutoEncryptionSettings.scala
driver-scala/src/main/scala/org/mongodb/scala/package.scala

JAVA-4749
I didn't find any other obvious places to make the requested change.

Update encryption terminology

---

driver-core/src/test/resources/unified-test-format/sessions/implicit-sessions-default-causal-consistency.json

Sync spec tests

---

driver-reactive-streams/src/examples/reactivestreams/tour/ClientSideEncryptionExplicitEncryptionAndDecryptionTour.java
driver-sync/src/examples/tour/ClientSideEncryptionExplicitEncryptionAndDecryptionTour.java

Fix explicit decryption code in tour

---

.evergreen/.evg.yml

Add noauth/nossl variants for replica sets and sharded clusters

---

driver-core/src/main/com/mongodb/internal/connection/ZstdCompressor.java

Use default compression level for zstd

---

driver-core/build.gradle

Update mongodb-driver-core POM description

---

.evergreen/compile.sh
driver-scala/src/test/scala/org/mongodb/scala/model/AggregatesSpec.scala

Turn off automatic running of spotlessApply when
running the static analysis checks.
JAVA-5033

Build: Ensure spotless checks are run

---

build.gradle

The reasoning behind is in JAVA-5038.
JAVA-5038

Upgrade Netty from 4.1.84.Final to 4.1.87.Final

---

driver-scala/src/test/scala/org/mongodb/scala/model/AggregatesSpec.scala

Remove hidden import
Remove parentheses
JAVA-5039

Scala: Fix tests

---

driver-sync/src/test/functional/com/mongodb/client/ChangeStreamProseTest.java

Run changeStreamSplitLargeEvent test on >= 6.0.9

---

driver-core/src/main/com/mongodb/connection/ClusterSettings.java

Please see if this PR can be merged

Fixed JAVA-5183

---

bson-kotlin/build.gradle.kts
bson-kotlinx/build.gradle.kts
bson-scala/build.gradle
bson/build.gradle
driver-kotlin-coroutine/build.gradle.kts
driver-kotlin-sync/build.gradle.kts
driver-scala/build.gradle
gradle/publish.gradle

Original PR #1232
[JAVA-5213](https://jira.mongodb.org/browse/JAVA-5213)
[JAVA-5202](https://jira.mongodb.org/browse/JAVA-5202)

Backport a fix of 'Add explicit automatic module name configuration'

---

driver-core/src/main/com/mongodb/internal/connection/DefaultClusterFactory.java
driver-core/src/test/unit/com/mongodb/internal/connection/DefaultClusterFactoryTest.java

[JAVA-5210](https://jira.mongodb.org/browse/JAVA-5210)

Backport of an improvement 'Update logger name to align with naming conventions'

---

driver-core/src/main/com/mongodb/internal/TimeoutSettings.java
driver-core/src/test/functional/com/mongodb/ClusterFixture.java
driver-core/src/test/functional/com/mongodb/internal/connection/DefaultConnectionPoolTest.java
driver-core/src/test/unit/com/mongodb/internal/connection/AbstractConnectionPoolTest.java
driver-core/src/test/unit/com/mongodb/internal/connection/BaseClusterSpecification.groovy
driver-core/src/test/unit/com/mongodb/internal/connection/ConnectionPoolAsyncTest.java
driver-core/src/test/unit/com/mongodb/internal/connection/ConnectionPoolTest.java
driver-core/src/test/unit/com/mongodb/internal/connection/DefaultConnectionPoolSpecification.groovy
driver-core/src/test/unit/com/mongodb/internal/connection/InternalStreamConnectionSpecification.groovy
driver-core/src/test/unit/com/mongodb/internal/connection/LoadBalancedClusterTest.java
driver-core/src/test/unit/com/mongodb/internal/connection/TimeoutTrackingConnectionGetter.java
driver-reactive-streams/src/test/unit/com/mongodb/reactivestreams/client/internal/ClientSessionBindingSpecification.groovy

Apply test server selection timeouts to OperationContext instead of ClusterSettings

Fix server selection test performance

---

4.11/driver-reactive/tutorials/perform-write-operations/index.html
4.11/driver-scala/tutorials/perform-write-operations/index.html

JIRA: https://jira.mongodb.org/browse/DOCSP-33759

DOCSP-33759: remove callout about replace efficiency

---

driver-sync/src/test/functional/com/mongodb/client/ClientSideOperationTimeoutTest.java

Enable socketTimeoutMS tests

---

driver-core/src/test/resources/unified-test-format/index-management/createSearchIndex.json
driver-core/src/test/resources/unified-test-format/index-management/createSearchIndexes.json
driver-core/src/test/resources/unified-test-format/index-management/dropSearchIndex.json
driver-core/src/test/resources/unified-test-format/index-management/listSearchIndexes.json
driver-core/src/test/resources/unified-test-format/index-management/searchIndexIgnoresReadWriteConcern.json
driver-core/src/test/resources/unified-test-format/index-management/updateSearchIndex.json

Update Atlas search spec tests

---

driver-kotlin-coroutine/src/main/kotlin/com/mongodb/kotlin/client/coroutine/MongoDatabase.kt
driver-kotlin-sync/src/main/kotlin/com/mongodb/kotlin/client/MongoDatabase.kt
driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/MongoDatabase.java
driver-scala/src/main/scala/org/mongodb/scala/MongoDatabase.scala
driver-sync/src/main/com/mongodb/client/MongoDatabase.java

Now uses the language of the Spec. Which will fall into line with JAVA-5322 delayed setting of maxtimems.
JAVA-5098

Updated the javadoc for runCommand.

---

.evergreen/.evg.yml
.evergreen/run-serverless-tests.sh

JAVA-5234
https://spruce.mongodb.com/version/65e8f455d6d80a47ad28cccb/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

Test against serverless proxy

---

.evergreen/.evg.yml

Use ec2.assume_role

---

driver-core/src/main/com/mongodb/ClientEncryptionSettings.java
driver-core/src/main/com/mongodb/ClientSessionOptions.java
driver-core/src/main/com/mongodb/MongoClientSettings.java
driver-core/src/main/com/mongodb/TransactionOptions.java
driver-core/src/main/com/mongodb/assertions/Assertions.java
driver-core/src/main/com/mongodb/internal/TimeoutSettings.java
driver-core/src/main/com/mongodb/internal/session/BaseClientSessionImpl.java
driver-core/src/test/functional/com/mongodb/ClusterFixture.java
driver-core/src/test/unit/com/mongodb/ClientEncryptionSettingsSpecification.groovy
driver-core/src/test/unit/com/mongodb/ClientSessionOptionsSpecification.groovy
driver-core/src/test/unit/com/mongodb/MongoClientSettingsSpecification.groovy
driver-core/src/test/unit/com/mongodb/TransactionOptionsSpecification.groovy
driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/MongoOperationPublisher.java
driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/gridfs/GridFSBucketImpl.java
driver-reactive-streams/src/test/unit/com/mongodb/reactivestreams/client/internal/MongoOperationPublisherTest.java
driver-sync/src/main/com/mongodb/client/gridfs/GridFSBucketImpl.java
driver-sync/src/main/com/mongodb/client/internal/MongoClusterImpl.java
driver-sync/src/main/com/mongodb/client/internal/MongoCollectionImpl.java
driver-sync/src/main/com/mongodb/client/internal/MongoDatabaseImpl.java
driver-sync/src/test/unit/com/mongodb/client/internal/MongoClusterSpecification.groovy
driver-sync/src/test/unit/com/mongodb/client/internal/MongoCollectionSpecification.groovy
driver-sync/src/test/unit/com/mongodb/client/internal/MongoDatabaseSpecification.groovy

Ensure that users can't accidently set a 0 value
which in CSOT represents infinite timeouts.
JAVA-5351

Validate timeout and timeunit values

---

driver-core/src/main/com/mongodb/internal/operation/AbortTransactionOperation.java
driver-core/src/main/com/mongodb/internal/operation/FindOperation.java
driver-core/src/test/functional/com/mongodb/client/test/CollectionHelper.java
driver-core/src/test/resources/unified-test-format/client-side-operation-timeout/README.md
driver-core/src/test/resources/unified-test-format/client-side-operation-timeout/change-streams.json
driver-core/src/test/resources/unified-test-format/client-side-operation-timeout/close-cursors.json
driver-core/src/test/resources/unified-test-format/client-side-operation-timeout/convenient-transactions.json
driver-core/src/test/resources/unified-test-format/client-side-operation-timeout/deprecated-options.json
driver-core/src/test/resources/unified-test-format/client-side-operation-timeout/gridfs-download.json
driver-core/src/test/resources/unified-test-format/client-side-operation-timeout/non-tailable-cursors.json
driver-core/src/test/resources/unified-test-format/client-side-operation-timeout/retryability-timeoutMS.json
driver-core/src/test/resources/unified-test-format/client-side-operation-timeout/sessions-inherit-timeoutMS.json
driver-core/src/test/resources/unified-test-format/client-side-operation-timeout/sessions-override-operation-timeoutMS.json
driver-core/src/test/resources/unified-test-format/client-side-operation-timeout/sessions-override-timeoutMS.json
driver-core/src/test/resources/unified-test-format/client-side-operation-timeout/tailable-awaitData.json
driver-core/src/test/resources/unified-test-format/client-side-operation-timeout/tailable-non-awaitData.json
driver-sync/src/test/functional/com/mongodb/client/AbstractClientSideEncryptionTest.java
driver-sync/src/test/functional/com/mongodb/client/ClientSideOperationTimeoutTest.java
driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java

- Added createOptions support for collection creation 
- Fixed error with awaitable tailable cursors
JAVA-5374

Updated the unified specs tests

---

driver-core/src/test/resources/connection-monitoring-and-pooling/cmap-format/pool-checkout-maxConnecting-is-enforced.json

Alleviate the race condition in the `pool-checkout-maxConnecting-is-enforced` test

---

driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudTest.java

Disable failing unified CRUD tests

---

.evergreen/.evg.yml

Add MongoDB 8.0 to testing matrix

---

build.gradle
driver-benchmarks/build.gradle
driver-workload-executor/build.gradle
graalvm-native-image-app/build.gradle

Note that logback-classic is only used for testing.
JAVA-5482

Upgrade to logback-classic 1.3.14

---

driver-core/src/main/com/mongodb/ConnectionString.java
driver-core/src/main/com/mongodb/MongoCredential.java
driver-core/src/test/resources/auth/legacy/connection-string.json
driver-core/src/test/resources/connection-string/valid-options.json
driver-core/src/test/unit/com/mongodb/ConnectionStringUnitTest.java

Disallow comma character in authMechanismProperties

---

.evergreen/.evg.yml

Backport allow-empty

---

driver-core/src/test/resources/unified-test-format/command-logging/unacknowledged-write.json
driver-core/src/test/resources/unified-test-format/command-monitoring/unacknowledgedBulkWrite.json

Test updates

---

.github/workflows/release.yml

This is a backport of https://github.com/mongodb/mongo-java-driver/pull/1437.

Attribute release commit and tag to user triggering the workflow (#1437)

---

.github/workflows/bump-and-tag.sh
.github/workflows/bump-version.sh
.github/workflows/release.yml

This is a backport of https://github.com/mongodb/mongo-java-driver/pull/1425.

Support pre-releases in release tooling (#1425)

---

driver-core/src/main/com/mongodb/connection/ServerDescription.java
driver-core/src/test/unit/com/mongodb/internal/operation/OperationUnitSpecification.groovy

Bump maxWireVersion for MongoDB 8.0

---

bson-kotlinx/src/test/kotlin/org/bson/codecs/kotlinx/KotlinSerializerCodecTest.kt
bson-kotlinx/src/test/kotlin/org/bson/codecs/kotlinx/samples/DataClasses.kt

Original test added in: 0c679b9
JAVA-5365

Port bson-kotlin test to bson-kotlinx

---

.evergreen/.evg.yml

Remove testing of serverless terminating proxy

---

driver-kotlin-coroutine/src/main/kotlin/com/mongodb/kotlin/client/coroutine/MongoClient.kt
driver-kotlin-sync/src/main/kotlin/com/mongodb/kotlin/client/MongoClient.kt

Kotlin Spotless fix

---

driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnection.java
driver-core/src/test/unit/com/mongodb/internal/connection/InternalStreamConnectionSpecification.groovy

Ensure exception propagation in async try-catch block.

---

bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/BsonDecoder.kt
bson-kotlinx/src/test/kotlin/org/bson/codecs/kotlinx/KotlinSerializerCodecTest.kt
bson/src/main/org/bson/codecs/AtomicIntegerCodec.java
bson/src/main/org/bson/codecs/AtomicLongCodec.java
bson/src/main/org/bson/codecs/ByteCodec.java
bson/src/main/org/bson/codecs/CharacterCodec.java
bson/src/main/org/bson/codecs/DoubleCodec.java
bson/src/main/org/bson/codecs/FloatCodec.java
bson/src/main/org/bson/codecs/IntegerCodec.java
bson/src/main/org/bson/codecs/LongCodec.java
bson/src/main/org/bson/codecs/ShortCodec.java
bson/src/main/org/bson/internal/NumberCodecHelper.java
bson/src/main/org/bson/internal/StringCodecHelper.java
config/spotbugs/exclude.xml

This is a backport of https://github.com/mongodb/mongo-java-driver/pull/1301.
JAVA-5303

Enhance KotlinSerializer with value codecs for widening primitive conversion.

---

driver-core/src/test/resources/unified-test-format/client-side-operation-timeout/close-cursors.json

Update unified CSOT tests.

---

.github/workflows/release.yml

Update branch name from master to main in GH action workflow

---

bson/src/main/org/bson/BsonBinarySubType.java
bson/src/test/resources/bson/binary.json
bson/src/test/unit/org/bson/BsonBinarySubTypeSpecification.groovy

https://jira.mongodb.org/browse/JAVA-5092

Add BSON binary subtype 8

---

driver-kotlin-extensions/src/main/kotlin/com/mongodb/kotlin/client/model/Updates.kt
driver-kotlin-extensions/src/test/kotlin/com/mongodb/kotlin/client/model/ExtensionsApiTest.kt
driver-kotlin-extensions/src/test/kotlin/com/mongodb/kotlin/client/model/UpdatesTest.kt

Adding Kotlin extensions methods for updates  

---

driver-core/src/test/resources/unified-test-format/crud/aggregate-write-readPreference.json
driver-core/src/test/resources/unified-test-format/crud/db-aggregate-write-readPreference.json

JAVA-5481
spec sync up stuff.
complicated history (tooling error) but syncing up with upstream files suffice

Server 8.0+ requires tests for aggregation with $out to not pre-create output collection

---

driver-kotlin-extensions/build.gradle.kts

Format Gradle script to comply with static checks.

---

driver-core/src/main/com/mongodb/ConnectionString.java

Remove deprecation warnings.

---

driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/gridfs/GridFSBucketImpl.java

Stop ignoring id parameter (#1622)

---

driver-core/src/test/resources/server-discovery-and-monitoring/rs/secondary_ipv6_literal.json

Added secondary_ipv6_literal.json test
JAVA-5810

Test IPv6 literal in SDAM

---

driver-core/src/test/resources/unified-test-format/load-balancers/non-lb-connection-establishment.json
driver-core/src/test/resources/unified-test-format/load-balancers/transactions.json

Updated unified tests
JAVA-5805 - revert skip test
JAVA-5228 - Unpin session test

Test Load balancers

---

.evergreen/.evg.yml

Start running benchmarks against 8.0

---

driver-core/src/test/functional/com/mongodb/internal/connection/ClientMetadataHelperProseTest.java

https://jira.mongodb.org/browse/JAVA-5541

Record both FaaS and container metadata when both are present

---

driver-core/src/main/com/mongodb/internal/connection/StreamFactoryHelper.java
driver-legacy/src/main/com/mongodb/MongoClient.java
driver-legacy/src/test/unit/com/mongodb/MongoClientSpecification.groovy
driver-sync/src/main/com/mongodb/client/MongoClients.java
driver-sync/src/main/com/mongodb/client/internal/Clusters.java
driver-sync/src/main/com/mongodb/client/internal/MongoClientImpl.java
driver-sync/src/test/functional/com/mongodb/client/MongoClientTest.java
driver-sync/src/test/unit/com/mongodb/client/MongoClientSpecification.groovy

Backport of https://github.com/mongodb/mongo-java-driver/pull/1646
JAVA-5812

Fix Netty event loop resource leak on MongoClient close. (#1646)

---

driver-core/src/test/functional/com/mongodb/internal/operation/ChangeStreamOperationSpecification.groovy

Should be updated as part of JAVA-5835
JAVA-5835

Skip test for latest

---

driver-core/src/main/com/mongodb/internal/connection/Authenticator.java
driver-sync/src/test/functional/com/mongodb/internal/connection/OidcAuthenticationProseTests.java

This is a backport of https://github.com/mongodb/mongo-java-driver/pull/1719.
JAVA-5880

Fix OIDC reauthentication when a session is involved (#1719)

---

.evergreen/publish.sh
build.gradle.kts

Due to the number of artifacts this can take a long time.
JAVA-5881

Update waiting times for the transition stage

---

.evergreen/publish.sh

Automate closing and releasing maven artifacts when publishing

---

driver-core/src/main/resources/META-INF/native-image/reflect-config.json

This PR fixes a native imagine build failure reported in the GraalVM test.
JAVA-5769

Add parameter type in reflect-config.json for ChangeStreamDocument.
