driver/src/main/com/mongodb/MongoCollectionImpl.java
A minor thing I noticed during reading the code.
All parameters are passed to the validation accompanied with their actual name as a string.
=> Argument for validation method changed according to the conventions

bson/src/main/org/bson/codecs/DocumentCodec.java
The right side is known at compile time.
And it's a tiny tiny tiny bit faster
http://stackoverflow.com/questions/496928/what-is-the-difference-between-instanceof-and-class-isassignablefrom
=> instanceof can be used here instead of isAssignableFrom

driver-core/src/main/com/mongodb/ServerAddress.java, driver-core/src/test/unit/com/mongodb/ServerAddressSpecification.groovy, driver-core/src/test/unit/com/mongodb/connection/JMXConnectionPoolListenerSpecification.groovy
=> correct ipv6 address handling when building MongoClients

CONTRIBUTING.md, README.md
Update the documentation to explicitly mention the mongod parameter that must be for the mongod used for test runs to be properly configured. (CONTRIBUTING.md did not mention the requirement.)
=> update documentation for running tests to explicitly mention required mongod parameter

bson/build.gradle, build.gradle, driver-core/build.gradle, driver-core/src/main/com/mongodb/connection/ClientMetadataHelper.java, mongo-java-driver/build.gradle
https://jira.mongodb.org/browse/JAVA-2308
Version: 3.4.0.SNAPSHOT
ClientMetadataHelper tries to get DriverVersion using
```
Class<InternalStreamConnectionInitializer> clazz = InternalStreamConnectionInitializer.class;
URL versionPropertiesFileURL = clazz.getResource("/version.properties");
```
but there is another **"version.properties"** file in classpath - it leads to **IllegalArgumentException("Value can not be null")** in BsonString constructor
Proposal: read version from jar MANIFEST.MF file
=> JAVA-2308: unable to start MongoClient

docs/reference/content/driver-async/reference/crud/index.md
remove extra 'g' in getSettings() call.
=> Fix typo in in async-driver crud documentation 

driver-core/src/main/com/mongodb/ConnectionString.java, driver/src/main/com/mongodb/MongoClientURI.java
Both `MongoClientURI` and `ConnectionString` support `/database.collection` format in uri but it's not in javadoc (previously fixed by #116)
=> Added `collection` back to `MongoClientURI` and `ConnectionString` javadocs

driver-core/src/main/com/mongodb/bulk/BulkWriteError.java
This fixes small error in `com.mongodb.bulk.BulkWriteError.hashCode()` (`index` field was effectively not used in hash code), which was introduced during parent class extraction.
=> Fix typo in BulkWriteError.hashCode()

driver/src/main/com/mongodb/util/JSONCallback.java, driver/src/test/unit/com/mongodb/util/JSONCallbackTest.java
Fixed jira issue [JAVA-1796](https://jira.mongodb.org/browse/JAVA-1796).
I had the same problem as in this ticket, where the value for $type for $binary data was in a hexadecimal string. This specification can be found [here](https://docs.mongodb.com/v3.2/reference/mongodb-extended-json/#data_binary).
=> JAVA-1796 accept hexadecimal string for value of $type in binary data

driver/src/main/com/mongodb/client/model/DBCollectionDistinctOptions.java
Updated class level javadoc for DBCollectionDistinctOptions.java
Previously stated it was for count operations, which applies to a different class: DBCollectionCountOptions.java
=> Correct class level javadoc

docs/reference/content/driver/tutorials/ssl.md
This patch fixes some broken links on the `driver/tutorials/ssl` page by replacing `.`'s with `/`'s for links to the javadocs.
=> Fix reference docs for driver/tutorials/ssl

driver-core/src/main/com/mongodb/connection/DefaultConnectionPool.java, driver-core/src/main/com/mongodb/internal/thread/DaemonThreadFactory.java, driver/src/main/com/mongodb/Mongo.java
Make sure all threads created by driver have descriptive names, also not conflicting with JVM's built-in thread pools.
=> Named thread pools

docs/reference/content/builders/aggregation.md, docs/reference/content/builders/filters.md, docs/reference/content/builders/indexes.md, docs/reference/content/builders/sorts.md, docs/reference/content/builders/updates.md
This PR fixes wrong import statements in the following builder documentation pages:
* aggregation
* filters
* indexes
* sorts
* updates
=> Fixed wrong static imports in builders documentation

bson/src/main/org/bson/codecs/FloatCodec.java, bson/src/test/unit/org/bson/codecs/FloatCodecTest.java
in Java, the most negative number for a float is  -Float.MAX_VALUE, not Float.MIN_VALUE.   The original code would not parse any negative numbers are smaller than Float.MIN_VALUE.   Float.MIN_VALUE is the smallest positive number.
I have also updated the unit test to properly check negative bounds using -Double.MAX_VALUE as opposed to Double.MIN_VALUE.   Added a test to check for passing of a negative number properly
=> Update to FloatCodec to support negative numbers

driver-core/src/main/com/mongodb/DBRef.java
No bug here, jus a typo : a missing quote for the id value in the toString method.
=> Typo : missing quote in toString method's result

driver-core/src/main/com/mongodb/operation/AsyncQueryBatchCursor.java
This can happen if close and next are called on two different threads. It can result in IllegalStateException triggered by decrementing the reference count below 0.
=> Fix a racing condition during cursor closing.

driver-core/src/main/com/mongodb/client/model/Aggregates.java, driver-core/src/main/com/mongodb/client/model/Variable.java, driver-core/src/test/functional/com/mongodb/client/model/AggregatesFunctionalSpecification.groovy, driver-core/src/test/unit/com/mongodb/client/model/AggregatesSpecification.groovy
thanks to @csarrazi who helped me for this contribution
=> JAVA-2715: Query builder for new lookup stage

bson/src/main/org/bson/codecs/pojo/CollectionPropertyCodecProvider.java, bson/src/main/org/bson/codecs/pojo/MapPropertyCodecProvider.java
There is 1 warning i haven't fixed when i build with Oracle JDK 9 : 
D:\github\mongo-java-driver\driver-legacy\src\main\com\mongodb\DBCursor.java:980: warning: [deprecation] finalize() in Object has been deprecated
protected void finalize() {
^
1 warning
Use close() method...
=> JAVA-2523: Remove use of methods deprecated in Java 9

docs/reference/content/driver-async/getting-started/quick-start-pojo.md
This commit changes MongoClient to MongoClients to call getgetDefaultCodecRegistry() and adds value 'true' to automatic().
=> Fix incorrect use of async driver in code sample creating CodecRegistry

util/src/main/DocTaglet.java
The `<dd>` element is block level element : https://www.w3.org/TR/html401/struct/lists.html#edef-DD
So, we don't need `\n` or `%`, or `<br/>`  : 
With `%n`:
- http://mongodb.github.io/mongo-java-driver/3.7/javadoc/?com/mongodb/client/model/Accumulators.html 
Without  `%n`:
=> JAVA-2724 : Remove %n in String.format call in DocTaglet

driver-core/src/main/com/mongodb/client/model/Accumulators.java, driver-legacy/src/main/com/mongodb/BulkWriteRequestBuilder.java
Replace #467 
Fix link to MongoDB documentation.
- http://mongodb.github.io/mongo-java-driver/3.7/javadoc/?com/mongodb/client/model/Accumulators.html
- http://mongodb.github.io/mongo-java-driver/3.7/javadoc/com/mongodb/BulkWriteRequestBuilder.html
I will do another fix for `%n` introduced by 8331079
=> fix url path for documentation

build.gradle, driver-core/src/main/com/mongodb/operation/ChangeStreamOperation.java, driver-core/src/test/functional/com/mongodb/operation/ChangeStreamOperationSpecification.groovy, driver-sync/src/main/com/mongodb/client/ChangeStreamIterable.java, driver-sync/src/main/com/mongodb/client/internal/ChangeStreamIterableImpl.java, driver-sync/src/test/unit/com/mongodb/client/internal/ChangeStreamIterableSpecification.groovy
This exposes the new internal `showMigrationEvents` option that may be passed to change streams. Setting this option to true will make change streams show insert, update, and delete events generated by chunk migrations. This option may only be used for a change stream opened against a mongod.
=> Cloudp 42881

driver-core/src/test/resources/client-side-encryption-corpus/corpus-schema.json, driver-core/src/test/resources/client-side-encryption-corpus/corpus.json, driver-sync/src/test/functional/com/mongodb/client/ClientSideEncryptionProseTestSpecification.groovy
I think I got tripped up before because updating the JSON files in:
```
driver-core/src/test/resources/client-side-encryption
```
Didn't update the ones that the test runner seemed to use:
```
driver-core/out/test/resources/client-side-encryption/
```
I think this is the correct fix, but I'm can't fully run the prose test – creating a data key isn't adding the key alt name, and I think I'm not picking up the fix from [keyAltName fix](https://github.com/mongodb/libmongocrypt/commit/feceb84e0ef4305d3ab6b7d3e3552955491c6f67) though I'm publishing to maven local after that commit. I must be doing something wrong locally.
@jyemin would you be able to validate this fix works? If so, I'll make the corresponding change in the specifications repo.
=> Fix FLE tests

docs/reference/content/driver/getting-started/quick-start-pojo.md
MongoClient.getDefaultCodecRegistry() no longer seems to exist
=> Fix getDefaultCodecRegistry() example

docs/reference/content/bson/pojos.md
Currently, `enum Membership` is declared, and used as a constructor argument, but the field is of type `Member`.
Just changed the field to `Membership` to make it consistent.
=> Fix typo in enum code example

driver-core/src/main/com/mongodb/operation/BulkWriteBatch.java, driver-legacy/src/test/functional/com/mongodb/DBCollectionOldTest.java, driver-legacy/src/test/functional/com/mongodb/DBCollectionTest.java
This change switches inserts to use a `NoopFieldNameValidator`, instead of a `CollectibleDocumentFieldNameValidator`, allowing us to insert documents with `.` and `$` in their field names.
This should circumvent the issue in CLOUDP-51586.
=> CLOUDP-51586 - use NoopFieldNameValidator for inserts

docs/reference/content/bson/pojos.md
Currently, the hyperlink `FieldSerialization` redirect to 404 Not Found page.
It should be `PropertySerialization`.
Someone is suffering now by this. Check this out:
https://stackoverflow.com/q/61915336
=> Fix typo in POJOs doc

driver-core/src/main/com/mongodb/internal/operation/FindAndUpdateOperation.java
Signed-off-by: Gaspard Petit <gaspard.petit@eidosmontreal.com>
Minor fix for a misleading exception when `update` if null in FindAndUpdateOperation
=> Fix: when the update is null, the exception thrown in FindAndUpdateOperation should not mention that decoder is null

docs/reference/content/bson/codecs.md, docs/reference/content/bson/pojos.md, docs/reference/content/builders/filters.md, docs/reference/content/builders/projections.md, docs/reference/content/driver-scala/builders/filters.md, docs/reference/content/driver-scala/builders/projections.md
JIRA: 
https://github.com/ccho-mongodb/mongo-java-driver/pull/new/DOCSP-11515-typo-fixes
Fixes to typos in current reference documents.
=> DOCSP-11515: fix typos

driver-scala/src/main/scala/org/mongodb/scala/MongoCollection.scala
The old documentation seems to have been copied from `updateOne`. This makes the docs match the docs from `driver-reactive-streams`.
=> Fix scala documentation for updateMany

docs/reference/content/apidocs.md
JAVA-3803
http://rozza.github.io/mongo-java-driver/4.1/apidocs/
I opted not to merge the sources for each areas java docs, as that makes the index page very hard to read - losing the initial benefits of splitting out the docs. It also significantly increases the size of the docs - from 45mb to 110mb
=> Docs: Added a link to the shared core

driver-core/src/test/resources/server-discovery-and-monitoring-monitoring/discovered_standalone.json, driver-core/src/test/resources/server-discovery-and-monitoring-monitoring/standalone_suppress_equal_description_changes.json, driver-core/src/test/unit/com/mongodb/internal/connection/AbstractServerDiscoveryAndMonitoringTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/ServerDiscoveryAndMonitoringMonitoringTest.java
https://jira.mongodb.org/browse/JAVA-3824
No patch build since it's just a change to unit tests, which I ran locally.
=> Update server discovery monitoring tests with directConnection URI option

bson/src/main/org/bson/json/JsonReader.java, bson/src/test/resources/bson/binary.json, bson/src/test/unit/org/bson/GenericBsonTest.java, bson/src/test/unit/org/bson/json/JsonReaderTest.java
$uuid is a synonym for a subtype 4 $binary, and is typically found in MongoDB 4.4+ server logs
JAVA-3834
=> Support parsing $uuid in JSON

.evergreen/publish.sh, build.gradle
Use the latest scala multiversion plugin
Split out the publishing steps
JAVA-3843
Patch: https://spruce.mongodb.com/version/5f6b310a1e2d17450be4b41e/tasks
Snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/mongodb/scala/
=> Fix scala publishing

build.gradle, driver-core/src/main/com/mongodb/AutoEncryptionSettings.java, driver-core/src/main/com/mongodb/internal/capi/MongoCryptHelper.java, driver-sync/src/main/com/mongodb/client/internal/Crypt.java
Added calls to the new CAPI's:
* mongocrypt_setopt_kms_providers - to support new KMS provider options.
* mongocrypt_ctx_setopt_key_encryption_key - to support new data key options.
* mongocrypt_setopt_crypto_hook_sign_rsaes_pkcs1_v1_5 - to support signature callback for GCP.
JAVA-3841
=> Added MongoCrypt support for Azure and GCP

bson/src/main/org/bson/types/ObjectId.java, bson/src/test/unit/org/bson/types/ObjectIdTest.java
The existing serialization format for ObjectId is the default format provided by the
ObjectOutputStream specification, which just serializes each field of the class.  But
in the 3.8.0 release we changed the fields, but neglected to even change the
serialVersionUID of the class, which makes any instances of ObjectId serialized prior
to 3.8.0 dangerously incompatible with subsequent driver releases.
This change updates the serialVersionUID for ObjectId, and also defines the serialized
form using a proxy via the writeReplace method.  This means that serialized instances
of ObjectId prior to this change will be incompatible, but at least an exception
will be thrown indicating the incompatibility. And now we have the freedom to change
the private representation of ObjectId without affecting …
=> Update serialization of ObjectId to a stable interchange format

docs/reference/content/driver/tutorials/ssl.md, docs/reference/content/whats-new.md
JIRA:
https://jira.mongodb.org/browse/DOCSP-12704
This change may apply to other branches depending on when MongoClientOptions was moved to the legacy library
=> DOCSP-12704: fix the link to MongoClientOptions api doc

bson/src/main/org/bson/json/DateTimeFormatter.java, bson/src/main/org/bson/json/JsonParseException.java, bson/src/main/org/bson/json/JsonReader.java, bson/src/test/unit/org/bson/json/JsonReaderTest.java
The JsonReader class already uses java.time.format.DateTimeFormatter for parsing
date strings from relaxed extended JSON. But for historical reasons it still
used the older java.text.SimpleDateFormat for parsing ISODate strings from shell
mode JSON.
This patch replaces the SimpleDateFormat usage with DateTimeFormatter, which will
preserve the existing behavior, but also remove a dependency on Locale.ENGLISH
time zones, which has caused problems for some users of GraalVM (which in some
configurations does not include any of the resources associated with Locale.ENGLISH.
Note that SimpleDateFormat is still used when parsing date strings for the shell-mode
Date constructor, but that is less commonly used and in addition the current shell
support is not localizable and is tied to …
=> Replace SimpleDateFormat with DateDateFormatter for ISODate string parsing

driver-sync/src/test/functional/com/mongodb/client/unified/AssertionContext.java, driver-sync/src/test/functional/com/mongodb/client/unified/ContextElement.java, driver-sync/src/test/functional/com/mongodb/client/unified/ErrorMatcher.java, driver-sync/src/test/functional/com/mongodb/client/unified/EventMatcher.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/ValueMatcher.java
It's too hard to debug failing unified tests.  The assertions don't provide enough context to see what the failure is, so the only way to figure it out is to look at the JSON test to see what it looks like and then set breakpoints to get some context on the assertion failure.
This patch adds context to the messages that are printed by Junit whenever an assertion fails.  Here's an example:
```
Expected BSON numbers to be equal
Assertion Context:
Value Matching Context:
Key: $gt
Expected value:
BsonInt32{value=2}
Actual value:
BsonInt32{value=1}
Value Matching Context:
Key: _id
Expected value:
{"$gt": 2}
Actual value:
{"$gt": 1}
Value Matching Context:
Key: $match
Expected value:
{"_id": {"$gt": 2}}
Actual value:
{"_id": {"$gt": 1}}
Value Matching Context:
Key: pipeline
Array position: 0 …
```
=> Add assertion context to the unified test runner

driver-sync/src/test/functional/com/mongodb/client/unified/ContextElement.java, driver-sync/src/test/functional/com/mongodb/client/unified/EventMatcher.java, driver-sync/src/test/functional/com/mongodb/client/unified/OperationResult.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java
Sorry for the noise on this.  But I found a number of places where the assertion context was insufficient to debug test failures in the versioned API and thought it best to fix it in a small, separate PR.
JAVA-3495
=> Improve assertion error context in unified test runner

bson-scala/src/main/scala/org/mongodb/scala/bson/codecs/ImmutableDocumentCodec.scala, bson-scala/src/main/scala/org/mongodb/scala/bson/collection/BaseDocument.scala, bson/src/main/org/bson/RawBsonDocument.java, bson/src/main/org/bson/conversions/Bson.java, bson/src/test/unit/org/bson/DocumentTest.java, driver-core/src/main/com/mongodb/internal/connection/AbstractByteBufBsonDocument.java, driver-core/src/main/com/mongodb/internal/connection/ByteBufBsonDocument.java, driver-core/src/main/com/mongodb/internal/connection/CommandMessage.java
The default implementation simply calls Bson#toBsonDocument(Class<T>, CodecRegistry)
JAVA-3885
=> Add Bson#toBsonDocument() overload with a default implementation

driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnection.java
Currently DNS lookups happen synchronously in the reactive streams
driver.  This isn't good, but with this change at least DNS errors
will be properly reported.
JAVA-3852
=> Ensure DNS errors bubble up as errors in reactive streams

bson-scala/src/main/scala/org/mongodb/scala/bson/annotations/BsonIgnore.scala, bson-scala/src/main/scala/org/mongodb/scala/bson/codecs/macrocodecs/CaseClassCodec.scala, bson-scala/src/test/scala/org/mongodb/scala/bson/codecs/MacrosSpec.scala
Link to JIRA issue [here](https://jira.mongodb.org/browse/JAVA-3814?filter=-2)
Goal is to support `BsonIgnore` annotation for scala driver in order to ignore some fields during bson serialization which are not meant to be `Option`s
ie: 
```scala
case class Person(firstname: String, lastname: String, @BsonIgnore metadata: Seq[Metadata] = Vector())
```
Tests have been added to the `MacrosSpec`
=> [JAVA-3814] Supports BsonIgnore annotation for scala driver

docs/reference/content/driver/tutorials/aggregation.md
From Slack:
> 
> Hey all, quick question. On the aggregation page it gives this helper to print out the contents
> ```
>         Block<Document> printBlock = new Block<Document>() {
>             @Override
>             public void apply(final Document document) {
>                 System.out.println(document.toJson());
>             }
>         };
> ```
> This doesn't seem to work. When I try to use it it I get the error
> ```
> intro.collection.aggregate(Arrays.asList(Aggregates.match(Filters.in("color", "red", "blue"))))
>     .forEach(printBlock)
>      ^^^^^^^
> The method forEach(Consumer<? super Document>) in the type Iterable<Document> is not applicable for the arguments (Block<Document>)
> ```
> 
> Since we're on Java 1.8 and above, can we use a lambda or is there a more …
=> docs: print using lambda in aggregation page

driver-scala/src/main/scala/org/mongodb/scala/internal/SingleItemObservable.scala
Hi MongoDB, @rozza,
I observed what seems to be a tiny bug.
It is about the `SingleItemObservable` class.
This class is called in `SingleObservable.scala` file
```scala
object SingleObservable {
/**
* Creates an SingleObservable from an item.
*
* Convenient for testing and or debugging.
*
* @param item the item to create an observable from
* @tparam A the type of the SingleObservable
* @return an Observable that emits the item
*/
def apply[A](item: A): SingleObservable[A] = SingleItemObservable(item)
}
```
I figured it out when adding tests and mocking some DB calls, and returning `SingleObservable(aTestValue)`, I always got an exception :
```
java.lang.IllegalStateException: SingleObservable.onNext cannot be called with multiple results.
at …
```
=> Fixes SingleItemObservable to emit item only once

driver-scala/src/main/scala/org/mongodb/scala/package.scala, driver-scala/src/test/scala/org/mongodb/scala/ScalaPackageSpec.scala
When converting from a BsonDocument to org.bson.Document
the scala driver previously used json. The implementation
should not rely on the json output format, but rather use
the Codecs to do the conversion.
JAVA-3916
=> Scala: Ensure implicit conversion keeps type fidelity

driver-core/src/main/com/mongodb/internal/operation/ChangeStreamBatchCursor.java, driver-core/src/main/com/mongodb/internal/operation/QueryBatchCursor.java, driver-core/src/test/functional/com/mongodb/OperationFunctionalSpecification.groovy, driver-core/src/test/functional/com/mongodb/internal/operation/ChangeStreamOperationProseTestSpecification.groovy, driver-sync/src/test/functional/com/mongodb/client/ChangeStreamProseTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTestValidator.java
=> Ensure that resumeToken is included on resume attempts

driver-core/src/test/functional/com/mongodb/internal/operation/AsyncQueryBatchCursorFunctionalSpecification.groovy
=> Disable test that fails against some pre-3.2 MongoDB sharded clusters

driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java
A unified test should fail in the following circumstance:
* The operation specification defines neither expectResult nor expectError
* The operation throws an exception
JAVA-3960
A test for this is forthcoming in the spec test validator, but wanted to get the fix in now while it was fresh in my mind.
=> Fail unified test if an operation throws an exception

driver-core/src/main/com/mongodb/internal/client/model/FindOptions.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/AggregatePublisherImpl.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/BatchCursorFlux.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/BatchCursorPublisher.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/ChangeStreamPublisherImpl.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/DistinctPublisherImpl.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/FindPublisherImpl.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/ListCollectionsPublisherImpl.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/ListDatabasesPublisherImpl.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/ListIndexesPublisherImpl.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/MapReducePublisherImpl.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/TestSubscriber.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/internal/BatchCursorFluxTest.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/internal/BatchCursorPublisherTest.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/internal/ConnectionsSurvivePrimaryStepDownProseTest.java, driver-reactive-streams/src/test/unit/com/mongodb/reactivestreams/client/internal/AggregatePublisherImplTest.java, driver-reactive-streams/src/test/unit/com/mongodb/reactivestreams/client/internal/ChangeStreamPublisherImplTest.java, driver-reactive-streams/src/test/unit/com/mongodb/reactivestreams/client/internal/FindPublisherImplTest.java, driver-reactive-streams/src/test/unit/com/mongodb/reactivestreams/client/internal/ListCollectionsPublisherImplTest.java, driver-reactive-streams/src/test/unit/com/mongodb/reactivestreams/client/internal/ListIndexesPublisherImplTest.java
The BatchCursorPublisher now waits for demand to be signalled before
creating the cursor.
The batch cursor publisher also internally respects the batch size.
Its either the configured batch size if set or the amount requested.
JAVA-3973
=> Fix reactive streams batch cursor regression.

driver-core/src/main/com/mongodb/internal/operation/AsyncChangeStreamBatchCursor.java, driver-core/src/main/com/mongodb/internal/operation/AsyncQueryBatchCursor.java, driver-core/src/test/functional/com/mongodb/internal/operation/AsyncQueryBatchCursorFunctionalSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/operation/AsyncQueryBatchCursorSpecification.groovy
This is a backport of a3ef19b171cdbfaa4677486fb43a2e8877d36d3a.
Evergreen patch: https://spruce.mongodb.com/version/601c2b582fbabe23aea4ed69.
=> Make implementations of AsyncAggregateResponseBatchCursor more responsive to close signals

docs/reference/content/builders/indexes.md, docs/reference/content/driver-reactive/tutorials/indexes.md, docs/reference/content/driver-scala/builders/indexes.md, docs/reference/content/driver-scala/tutorials/indexes.md, docs/reference/content/driver/tutorials/indexes.md, driver-core/src/main/com/mongodb/client/model/IndexOptions.java, driver-core/src/main/com/mongodb/client/model/Indexes.java, driver-core/src/main/com/mongodb/internal/bulk/IndexRequest.java, driver-scala/src/main/scala/org/mongodb/scala/model/Indexes.scala
This removes mention of geoHaystack from the docs and marks methods as deprecated.
=> JAVA-3684: deprecate geohaystack

docs/reference/content/driver-scala/getting-started/quick-start.md
Add missing closing parenthesis on `Document` link
=> Add missing closing parenthesis on `Document` link

driver-core/src/main/com/mongodb/internal/operation/CountDocumentsOperation.java, driver-core/src/main/com/mongodb/internal/operation/EstimatedDocumentCountOperation.java, driver-core/src/main/com/mongodb/internal/operation/Operations.java, driver-core/src/main/com/mongodb/internal/operation/ServerVersionHelper.java, driver-core/src/main/com/mongodb/internal/operation/SyncOperations.java, driver-core/src/test/functional/com/mongodb/client/test/CollectionHelper.java, driver-core/src/test/functional/com/mongodb/internal/operation/CountDocumentsOperationSpecification.groovy, driver-core/src/test/resources/retryable-reads/estimatedDocumentCount-4.9.json, driver-core/src/test/resources/retryable-reads/estimatedDocumentCount-pre4.9.json, driver-core/src/test/resources/retryable-reads/estimatedDocumentCount-serverErrors-4.9.json, driver-core/src/test/resources/retryable-reads/estimatedDocumentCount-serverErrors-pre4.9.json, driver-core/src/test/resources/unified-test-format/crud/estimatedDocumentCount.json, driver-core/src/test/resources/versioned-api/crud-api-version-1.json, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/MongoOperationPublisher.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/ReadConcernTest.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/unified/UnifiedCrudTest.java, driver-sync/src/main/com/mongodb/client/internal/MongoCollectionImpl.java, driver-sync/src/test/functional/com/mongodb/client/ReadConcernTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/ErrorMatcher.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudHelper.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudTest.java, driver-sync/src/test/unit/com/mongodb/client/internal/MongoCollectionSpecification.groovy
There are three commits, which I'll summarize here:
1. Refactor CountOperation into three operations: CountOperation was already complex in that it was supporting three different use cases.  One for estimatedDocumentCount, one for countDocuments, and one for the legacy DBCollection.count.  Trying to add the $collStats support into this class was going to make it even messier, as now there would be two different aggregation pipelines.  It was just too much, so I split it out, which allowed me to get rid of all the conditional logic.  
2. Add support for errorCode to unified test runner.  This was just a small missing piece that was needed by the new tests
3. The last commit is the functional change required by the spec, plus all the new tests.
JAVA-3989
=> Use $collStats for estimatedDocumentCount on 5.0+ servers

driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/BatchCursorPublisherErrorTest.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/TestSubscriber.java
Ensure sessions are returned if the batch cursor onNext call results in
an error.
JAVA-3976
=> BatchCursor close regression tests

driver-core/src/test/resources/unified-test-format/valid-fail/entity-bucket-database-undefined.json, driver-core/src/test/resources/unified-test-format/valid-fail/entity-client-apiVersion-unsupported.json, driver-core/src/test/resources/unified-test-format/valid-fail/entity-collection-database-undefined.json, driver-core/src/test/resources/unified-test-format/valid-fail/entity-database-client-undefined.json, driver-core/src/test/resources/unified-test-format/valid-fail/entity-session-client-undefined.json, driver-core/src/test/resources/unified-test-format/valid-fail/operation-failure.json, driver-core/src/test/resources/unified-test-format/valid-fail/returnDocument-enum-invalid.json, driver-core/src/test/resources/unified-test-format/valid-fail/schemaVersion-unsupported.json, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTestFailureValidator.java
This runner is strange because we actually want the test to pass only if the
actual unified test runner fails.  Due to the nature of the tests the failure
can happen either in the setup method or in the actual test, so we have to
handle both cases.
JAVA-4003
I hadn't done this with the original batch of valid-fail tests, but with JAVA-4003 being a test for something the Java driver got wrong in the original implementation, I decided to find a way to run all of the valid-fail tests, which are included in this patch as well as the one specific to JAVA-4003.
This seems like a pretty hacky way to run these tests, so please let me know if you have any other ideas.
=> Add specialized unified test runner for valid-fail tests

driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/OperationExecutorImpl.java
Previously the driver assumed that Mono#doOnTerminate is executed
prior to the subscriber being notified of completion.  But it turns
out that behavior is not guaranteed in the Californium release of
Project Reactor (though it is in later releases).  So instead,
now the SingleResultCallback that is used to notify the Mongo of
completion is wrapped by one that first releases the binding, and
Mono#doOnTerminate is no longer used.
JAVA-4027
=> Ensure that AsyncReadWriteBinding is released prior to subscriber notification

driver-sync/src/test/functional/com/mongodb/client/AbstractRetryableWritesTest.java
Also, ensure that the stack trace of the unexpected exception is
included in build output by re-throwing the exception.
JAVA-4025
=> Ensure retryable writes tests fail when unexpected exception is thrown

driver-core/src/main/com/mongodb/event/ConnectionCheckOutFailedEvent.java, driver-core/src/test/unit/com/mongodb/internal/connection/AbstractConnectionPoolTest.java
JAVA-4038
Somehow this was missed in the initial commit.  I noticed it when doing the workload executor for planned maintenance.
=> Add getReason method to ConnectionCheckOutFailedEvent

driver-core/src/main/com/mongodb/internal/connection/ProtocolHelper.java, driver-core/src/test/resources/server-discovery-and-monitoring/errors/non-stale-topologyVersion-greater-LegacyNotPrimary.json, driver-core/src/test/resources/server-discovery-and-monitoring/errors/non-stale-topologyVersion-missing-LegacyNotPrimary.json, driver-core/src/test/resources/server-discovery-and-monitoring/errors/non-stale-topologyVersion-proccessId-changed-LegacyNotPrimary.json, driver-core/src/test/resources/server-discovery-and-monitoring/errors/post-42-LegacyNotPrimary.json, driver-core/src/test/resources/server-discovery-and-monitoring/errors/pre-42-LegacyNotPrimary.json, driver-core/src/test/resources/server-discovery-and-monitoring/errors/prefer-error-code.json, driver-core/src/test/resources/server-discovery-and-monitoring/errors/stale-generation-afterHandshakeCompletes-LegacyNotPrimary.json, driver-core/src/test/resources/server-discovery-and-monitoring/errors/stale-generation-afterHandshakeCompletes-network.json, driver-core/src/test/resources/server-discovery-and-monitoring/errors/stale-generation-afterHandshakeCompletes-timeout.json, driver-core/src/test/resources/server-discovery-and-monitoring/errors/stale-generation-beforeHandshakeCompletes-LegacyNotPrimary.json, driver-core/src/test/resources/server-discovery-and-monitoring/errors/stale-generation-beforeHandshakeCompletes-network.json, driver-core/src/test/resources/server-discovery-and-monitoring/errors/stale-topologyVersion-LegacyNotPrimary.json
Update logic for throwing MongoNotPrimaryException or MongoNodeIsRecoveringException:
* Add 10058 to the list of error codes that cause MongoNotPrimaryException
to be thrown.
* Only examine error messages when no error code is included in the reply.
JAVA-3986
=> Update error handling logic

build.gradle, driver-workload-executor/build.gradle, driver-workload-executor/src/main/com/mongodb/workload/WorkloadExecutor.java, driver-workload-executor/src/resources/logback.xml
JAVA-3952
Not really worth looking at the diff.  It's essentially a new implementation.
[This patch build](https://evergreen.mongodb.com/version/604902a23e8e865aca63dd8c) is actually what proves it works, since the workload executor doesn't run in the driver's own Evergreen configuration.
=> Update workload executor to use unified test runner

driver-core/src/main/com/mongodb/assertions/Assertions.java, driver-core/src/main/com/mongodb/internal/async/AsyncBatchCursor.java, driver-core/src/main/com/mongodb/internal/operation/AsyncChangeStreamBatchCursor.java, driver-core/src/main/com/mongodb/internal/operation/AsyncQueryBatchCursor.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/ChangeStreamsCancellationTest.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/TestSubscriber.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/internal/BatchCursorFluxTest.java
JAVA-4044/https://github.com/mongodb/mongo-java-driver/pull/689, JAVA-3938 & JAVA-3907 / https://github.com/mongodb/mongo-java-driver/pull/661.
Both commits were cherry-picked without resolving conflicts manually.
=> Backport to 4.2.x JAVA-4044/PR#689 and the changes it depends on (JAVA-3938 & JAVA-3907 / PR#661)

build.gradle, config/findbugs-exclude.xml, driver-core/src/main/com/mongodb/MongoException.java, driver-core/src/main/com/mongodb/MongoInterruptedException.java, driver-core/src/main/com/mongodb/event/ConnectionPoolListener.java, driver-core/src/main/com/mongodb/internal/Timeout.java, driver-core/src/main/com/mongodb/internal/connection/ConcurrentPool.java, driver-core/src/main/com/mongodb/internal/connection/ConnectionPool.java, driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java, driver-core/src/main/com/mongodb/internal/connection/PowerOfTwoBufferPool.java, driver-core/src/main/com/mongodb/internal/connection/UsageTrackingInternalConnection.java, driver-core/src/main/com/mongodb/internal/session/ServerSessionPool.java, driver-core/src/test/functional/com/mongodb/internal/connection/DefaultConnectionPoolTest.java, driver-core/src/test/resources/connection-monitoring-and-pooling/pool-checkout-maxConnecting-is-enforced.json, driver-core/src/test/resources/connection-monitoring-and-pooling/pool-checkout-maxConnecting-timeout.json, driver-core/src/test/resources/connection-monitoring-and-pooling/pool-checkout-returned-connection-maxConnecting.json, driver-core/src/test/unit/com/mongodb/internal/TimeoutTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/AbstractConnectionPoolTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/ConcurrentPoolTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/ConnectionPoolAsyncTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/ConnectionPoolTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/DefaultConnectionPoolSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/TestConnectionPoolListener.java
=> Rate limit new connection creations (maxConnecting)

driver-core/src/test/unit/com/mongodb/internal/connection/AbstractConnectionPoolTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/ConnectionPoolAsyncTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/ConnectionPoolTest.java
Also log exceptions that happen while tests run
JAVA-4104
=> Support TLS in AbstractConnectionPoolTest and its subclasses

driver-core/src/test/resources/unified-test-format/transactions/java-only-mongos-unpin.json, driver-core/src/test/resources/unified-test-format/transactions/mongos-unpin.json, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/ClientSession.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/ClientSessionPublisherImpl.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/OperationExecutorImpl.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/syncadapter/SyncClientSession.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/unified/UnifiedTransactionsTest.java, driver-scala/src/it/scala/org/mongodb/scala/syncadapter/SyncClientSession.scala, driver-sync/src/main/com/mongodb/client/ClientSession.java, driver-sync/src/main/com/mongodb/client/internal/ClientSessionImpl.java, driver-sync/src/main/com/mongodb/client/internal/MongoClientDelegate.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudHelper.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTransactionsTest.java
This change is a required precursor for load balancing support.  It fixes a couple of bugs in the pinning behavior of the driver for transactions that were uncovered by the new tests.
1. Server should be unpinned on successful abort of txn
2. Server should be unpinned on the first operation in a session after transaction has been committed 
JAVA-4096
=> Unpin server from session on abort or first non-transactional operation 

config/findbugs-exclude.xml, driver-core/src/main/com/mongodb/internal/connection/ConcurrentPool.java, driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java, driver-core/src/test/functional/com/mongodb/internal/connection/DefaultConnectionPoolTest.java
I discovered 3 problems in `DefaultConnectionPool` and `ConcurrentPool` introduced by me in https://github.com/mongodb/mongo-java-driver/pull/685.
1. [deadlock] See this [commit message](https://github.com/mongodb/mongo-java-driver/pull/699/commits/9e7348281b27be21288783330e6d0e9cdeac9e7d) for the details.
2. [not expecting an exception where it may happen] Removing from `OpenConcurrencyLimiter.desiredConnectionSlots` despite not putting anything there previously. See this [commit message](https://github.com/mongodb/mongo-java-driver/pull/699/commits/9e7348281b27be21288783330e6d0e9cdeac9e7d) for the details.
3. [double release on exception] The method `ConcurrentPool.ensureMinSize` explicitly requires a caller to release resources if `initialize` throws an exception, but then releases the …
=> Fix deadlock and couple more problems in `DefaultConnectionPool`

driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java
TODO: rebase on top of `master` after merging https://github.com/mongodb/mongo-java-driver/pull/699, then request for review.
JAVA-3927
=> Simplify `DefaultConnectionPool.OpenConcurrencyLimiter.tryLock`

driver-sync/src/test/functional/com/mongodb/client/JsonPoweredCrudTestHelper.java
The change stream cursors were not being closed, which was
causing problems in downstream tests
JAVA-4153
=> Fix JsonPoweredCrudTestHelper

driver-sync/src/test/functional/com/mongodb/client/unified/ContextElement.java, driver-sync/src/test/functional/com/mongodb/client/unified/OperationAsserter.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudHelper.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java
* Add a context for operation execution.  This provides context when the
operation itself asserts
* Include the index of the operation in the operations array.  This helps
when there are multiple operations that are identical and you want to
be able to determine which one failed
JAVA-4152
=> Improve assertion messages in unified test runner

driver-core/src/main/com/mongodb/internal/connection/CommandMessage.java, driver-core/src/main/com/mongodb/internal/operation/AsyncQueryBatchCursor.java, driver-core/src/main/com/mongodb/internal/operation/QueryBatchCursor.java, driver-core/src/test/resources/versioned-api/crud-api-version-1-strict.json, driver-core/src/test/resources/versioned-api/crud-api-version-1.json, driver-core/src/test/resources/versioned-api/transaction-handling.json
Previously they were excluded from getMore and transaction-continuing
commands. Now they are included.
JAVA-4128
=> Include versioned API options in all commands

driver-core/src/main/com/mongodb/internal/connection/LoadBalancedCluster.java, driver-core/src/main/com/mongodb/internal/connection/LoadBalancedServer.java, driver-core/src/test/unit/com/mongodb/internal/connection/LoadBalancedClusterTest.java
=> Close server/pool in `LoadBalancedCluster` and `LoadBalancedServer` respectively

driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/syncadapter/SyncMongoClient.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/syncadapter/SyncMongoCursor.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/unified/LoadBalancerTest.java
Turns out sleeping too much can cause problems...
The reason some transaction tests were failing is because, on Evergreen, we set `transactionLifetimeLimitSeconds` server parameter to something like 2 seconds.  And some of the transaction tests in pin-mongos.json open like 7 cursors in a single transaction.  Since we sleep for half a second per cursor, the transactions were timing out.
The solution, suggested by Valentin, is to only do the sleeps where necessary, for specific Load Balancer tests that require them.
JAVA-4176
=> Only sleep when necessary in SyncMongoCursor construction or close

driver-core/src/main/com/mongodb/internal/connection/ConcurrentPool.java, driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java, driver-core/src/test/functional/com/mongodb/internal/connection/DefaultConnectionPoolTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/TestInternalConnectionFactory.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/MainTransactionsTest.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/syncadapter/SyncClientSession.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/syncadapter/SyncMongoClient.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/unified/LoadBalancerTest.java, driver-scala/build.gradle, driver-scala/src/it/scala/org/mongodb/scala/MainTransactionsTest.scala, driver-scala/src/it/scala/org/mongodb/scala/syncadapter/SyncClientSession.scala, driver-scala/src/test/scala/org/mongodb/scala/ApiAliasAndCompanionSpec.scala, driver-sync/src/test/functional/com/mongodb/client/AbstractUnifiedTest.java
This PR is a successor of https://github.com/mongodb/mongo-java-driver/pull/719, and uses a different, much more resource-effective approach: we are back to using a single worker for async check outs, which, given that all check out operations currently have the same timeout, puts us back to a situation when async timeouts are handled correctly. Please see the commit messages for more details.
With CSOT different check out operations will have different timeouts, and we will have to change the `DefaultConnectionPool` code to handle timeouts correctly. However, that's a task for future. We can either do the same thing I did in https://github.com/mongodb/mongo-java-driver/pull/719, or we can mix the logic handling timeouts into existing blocking calls done by the (now single) async worker …
=>  Refactor `DefaultConnectionPool` to use single worker thread when checking out asynchronously

bson/src/main/org/bson/Document.java, bson/src/test/unit/org/bson/DocumentTest.java, driver-core/src/main/com/mongodb/BasicDBObject.java, driver-core/src/test/unit/com/mongodb/BasicDBObjectTest.java
Change the behavior of the following methods:
* Document.toJson
* BasicDBObject.toJson
* BasicDBObject.toString
to use standard UUID representation when generating JSON.  Prior to this change,
an exception would be thrown when the document contains a UUID value.
JAVA-4140
=> Use standard UUID representation for JSON generation

driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java
Previously it was info, and it's the only connection pool-related
log message at that high a level.
JAVA-4189
=> Change connection-closed log message to debug

driver-core/src/test/resources/connection-monitoring-and-pooling/wait-queue-timeout.json, driver-core/src/test/resources/unified-test-format/load-balancers/wait-queue-timeouts.json
=> Increase `waitQueueTimeoutMS` in some tests to reduce the probability of timing out accidentally

driver-core/src/main/com/mongodb/client/model/geojson/Polygon.java, driver-core/src/main/com/mongodb/client/model/geojson/PolygonCoordinates.java, driver-core/src/test/unit/com/mongodb/client/model/geojson/PolygonSpecification.groovy, driver-core/src/test/unit/com/mongodb/client/model/geojson/codecs/GeometryCodecSpecification.groovy, driver-core/src/test/unit/com/mongodb/client/model/geojson/codecs/GeometryCollectionCodecSpecification.groovy, driver-core/src/test/unit/com/mongodb/client/model/geojson/codecs/MultiPolygonCodecSpecification.groovy
Adds alternate constructors to Polygon and PolygonCoordinates that make it possible to construct a Mongo Polygon given a Polygon from some other library with a similar API.
Posting this PR to demonstrate what it would be nice to have, but this was a breaking change if consuming the driver using Groovy as can be seen in a few tests I changed. I would assume this exact solution won't work, so open to any ideas.
Basically just want to be able to convert a Polygon with this type of API to the Java Driver's Polygon:
```
class Coordinate {
double[] getCoords();
}
class Polygon {
List<Coordinate> getExterior();
List<List<Coordinate>> getHoles();
}
```
which currently is not possible as converting the above Polygon holes to the Java Driver's would require instantiating and populating a …
=> Add alternate constructor to Polygon and PolygonCoordinates

.evergreen/.evg.yml, .evergreen/run-tests.sh, docs/reference/config.toml, docs/reference/content/driver-reactive/tutorials/ssl.md, docs/reference/content/driver-scala/tutorials/ssl.md, docs/reference/content/driver/tutorials/ssl.md, docs/reference/content/whats-new.md, docs/reference/layouts/shortcodes/nettyapiref.html, driver-core/build.gradle, driver-core/src/main/com/mongodb/connection/SslSettings.java, driver-core/src/main/com/mongodb/connection/netty/NettyStream.java, driver-core/src/main/com/mongodb/connection/netty/NettyStreamFactory.java, driver-core/src/main/com/mongodb/connection/netty/NettyStreamFactoryFactory.java, driver-core/src/test/functional/com/mongodb/ClusterFixture.java, driver-reactive-streams/build.gradle, driver-scala/build.gradle, driver-sync/build.gradle
This may be used as a convenient way to utilize OpenSSL as an alternative to the TLS/SSL protocol implementation in a JDK.
JAVA-4177
=> Add support for setting `io.netty.handler.ssl.SslContext`

driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnection.java, driver-core/src/main/com/mongodb/internal/connection/LoggingCommandEventSender.java, driver-core/src/test/unit/com/mongodb/internal/connection/InternalStreamConnectionSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/LoggingCommandEventSenderSpecification.groovy, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/unified/CommandMonitoringTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/CommandMonitoringTest.java
* Ensure command event for hello with speculativeAuthenticate is elided
* Ensure redacted commands are logged with elision (The fact that we don't currently elide redacted commands when logging is enabled is not currently a big problem, since we don't log commands executed during the handshake at all.  But there is a ticket which is going to change this behavior, and I'm concerned that once we start logging these commands we may forget to elide them.  So just taking care of it now.)
JAVA-4195
=> Redaction improvements

driver-core/src/main/com/mongodb/MongoWriteException.java, driver-core/src/test/unit/com/mongodb/MongoWriteExceptionTest.java
Ensure that the error code from the single WriteError is propagated to the
exception error code.
JAVA-4219
=> Fix regression in MongoWriteException error code

driver-core/src/main/com/mongodb/connection/ConnectionDescription.java, driver-core/src/main/com/mongodb/internal/connection/DescriptionHelper.java, driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnectionInitializer.java, driver-core/src/test/resources/transactions/read-concern.json, driver-core/src/test/unit/com/mongodb/internal/connection/DescriptionHelperSpecification.groovy
The current load balancing code doesn't support an actual reply from a load-balanced cluster that contains a serviceId, as required by the specification. This patch adds it. 
JAVA-4218
=> Support serviceId in reply from load balanced cluster

docs/reference/themes/mongodb/layouts/partials/header.html, docs/reference/themes/mongodb/layouts/partials/header/newSiteNotice.html
JIRA: https://jira.mongodb.org/browse/DOCSP-16312
These changes place a notice at the top of Java 4.3 reference documentation pages (not API documentation) that link to the new Java reference documentation site. Do not merge until the new documentation site is published.
=> DOCSP-16312: Link to new Java sync 4.3 docs site

driver-legacy/src/main/com/mongodb/MongoClientURI.java
This query parameter has been deprecated for many years and
superseded by the readPreference query parameter.  Removing
the Javadoc for the parameter, with support to be removed in
the next major release
JAVA-4144
=> Remove documentation of legacy slaveok URI parameter

driver-core/src/main/com/mongodb/internal/connection/ProtocolHelper.java, driver-core/src/test/resources/unified-test-format/retryable-writes/bulkWrite-serverErrors.json, driver-core/src/test/resources/unified-test-format/retryable-writes/insertOne-serverErrors.json, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/unified/UnifiedRetryableWritesTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedRetryableWritesTest.java
This will allow the driver to properly retry writes that the server
has labeled as a RetryableWriteError.
JAVA-4244
=> Add top-level error labels to write concern error

driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/AggregatePublisherImpl.java, driver-reactive-streams/src/test/unit/com/mongodb/reactivestreams/client/internal/AggregatePublisherImplTest.java, driver-sync/src/main/com/mongodb/client/internal/AggregateIterableImpl.java, driver-sync/src/test/unit/com/mongodb/client/internal/AggregateIterableSpecification.groovy
=> Support aggregation with $merge as a string

driver-core/src/main/com/mongodb/connection/ConnectionPoolSettings.java, driver-core/src/main/com/mongodb/internal/connection/ConcurrentPool.java, driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java, driver-core/src/main/com/mongodb/internal/connection/PowerOfTwoBufferPool.java, driver-core/src/main/com/mongodb/internal/session/ServerSessionPool.java, driver-core/src/test/functional/com/mongodb/internal/connection/DefaultConnectionPoolTest.java, driver-core/src/test/unit/com/mongodb/connection/ConnectionPoolSettingsSpecification.groovy, driver-legacy/src/main/com/mongodb/MongoClientOptions.java, driver-legacy/src/test/unit/com/mongodb/MongoClientOptionsSpecification.groovy
See also JAVA-4160 and [CMAP Connection Pool Options]( https://github.com/mongodb/specifications/blob/master/source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst#connection-pool-options-1).
JAVA-4216
=> Handle 0 maxSize in `DefaultConnectionPool` and allow passing 0 to `MongoClientOptions.Builder.maxSize`

.evergreen/run-load-balancer-tests.sh, driver-core/src/main/com/mongodb/assertions/Assertions.java, driver-core/src/main/com/mongodb/internal/async/AsyncBatchCursor.java, driver-core/src/main/com/mongodb/internal/binding/ConnectionSource.java, driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java, driver-core/src/main/com/mongodb/internal/connection/DefaultServer.java, driver-core/src/main/com/mongodb/internal/connection/LoadBalancedServer.java, driver-core/src/main/com/mongodb/internal/operation/BatchCursor.java, driver-core/src/main/com/mongodb/internal/operation/ChangeStreamBatchCursor.java, driver-core/src/main/com/mongodb/internal/operation/QueryBatchCursor.java, driver-core/src/test/functional/com/mongodb/internal/connection/ServerHelper.java, driver-core/src/test/functional/com/mongodb/internal/operation/AggregateOperationSpecification.groovy, driver-core/src/test/functional/com/mongodb/internal/operation/CountDocumentsOperationSpecification.groovy, driver-core/src/test/functional/com/mongodb/internal/operation/DistinctOperationSpecification.groovy, driver-core/src/test/functional/com/mongodb/internal/operation/FindOperationSpecification.groovy, driver-core/src/test/functional/com/mongodb/internal/operation/MapReduceWithInlineResultsOperationSpecification.groovy, driver-core/src/test/functional/com/mongodb/internal/operation/QueryBatchCursorFunctionalSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/operation/AsyncQueryBatchCursorSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/operation/FindOperationUnitSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/operation/QueryBatchCursorSpecification.groovy, driver-sync/src/main/com/mongodb/client/MongoChangeStreamCursor.java, driver-sync/src/main/com/mongodb/client/MongoCursor.java
Run `QueryBatchCursor` integration tests (`QueryBatchCursorFunctionalSpecification`) with load balancer.
The high-level implementation idea is described in the documentation of the class `QueryBatchCursor.ResourceManager`. Only `QueryBatchCursor` required a change as per this [analysis](https://jira.mongodb.org/browse/JAVA-4183?focusedCommentId=3950629&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-3950629).
JAVA-4183
=> Support calling `QueryBatchCursor.close` concurrently with other `QueryBatchCursor` methods

build.gradle, driver-core/src/test/functional/com/mongodb/internal/connection/AsyncStreamTimeoutsSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/DefaultConnectionPoolSpecification.groovy, driver-sync/src/test/functional/com/mongodb/client/ClientSideEncryptionBsonSizeLimitsSpecification.groovy
JAVA-4145
https://spruce.mongodb.com/version/610bebf90ae606191fe957b7 - for the slow tests
=> Build: Fix slow tests

driver-core/src/main/com/mongodb/client/model/MapReduceAction.java, driver-core/src/main/com/mongodb/internal/operation/Operations.java, driver-core/src/main/com/mongodb/internal/operation/SyncOperations.java, driver-legacy/src/main/com/mongodb/MapReduceCommand.java, driver-legacy/src/main/com/mongodb/MapReduceOutput.java, driver-legacy/src/test/functional/com/mongodb/DBCollectionTest.java, driver-legacy/src/test/functional/com/mongodb/MapReduceTest.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/MapReducePublisher.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/MongoCollection.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/MapReducePublisherImpl.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/MongoCollectionImpl.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/BatchCursorPublisherErrorTest.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/syncadapter/SyncMapReduceIterable.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/syncadapter/SyncMongoCollection.java, driver-reactive-streams/src/test/tck/com/mongodb/reactivestreams/client/MapReducePublisherVerification.java, driver-reactive-streams/src/test/unit/com/mongodb/reactivestreams/client/PublisherApiTest.java, driver-reactive-streams/src/test/unit/com/mongodb/reactivestreams/client/internal/MapReducePublisherImplTest.java, driver-reactive-streams/src/test/unit/com/mongodb/reactivestreams/client/internal/MongoCollectionImplTest.java, driver-scala/src/main/scala/org/mongodb/scala/MapReduceObservable.scala, driver-scala/src/main/scala/org/mongodb/scala/MongoCollection.scala, driver-scala/src/main/scala/org/mongodb/scala/model/MapReduceAction.scala, driver-sync/src/main/com/mongodb/client/MapReduceIterable.java, driver-sync/src/main/com/mongodb/client/MongoCollection.java, driver-sync/src/main/com/mongodb/client/internal/MapReduceIterableImpl.java, driver-sync/src/main/com/mongodb/client/internal/MongoCollectionImpl.java, driver-sync/src/test/functional/com/mongodb/client/JsonPoweredCrudTestHelper.java, driver-sync/src/test/functional/com/mongodb/client/MongoCollectionTest.java
Deprecate all public API related to the mapReduce command, which has been
deprecated in MongoDB server as superseded by the aggregate command.
See https://docs.mongodb.com/manual/reference/command/mapReduce/ for more
information.
JAVA-4235
=> Deprecate mapReduce

bson-scala/build.gradle, driver-core/build.gradle, driver-reactive-streams/build.gradle, driver-scala/build.gradle, driver-sync/build.gradle
Refs: #771 Using the suggested method by @stbischof
Fixes imports in `mongo-scala-bson`, `mongodb-driver-sync`, `mongodb-driver-reactivestreams`, `mongodb-driver-core`.
JAVA-4274
=> Fix manifest import-package imports

driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnection.java
=> Close `InternalStreamConnection` when `stream.openAsync`/`writeAsync` fails or completes abruptly

driver-core/src/main/com/mongodb/connection/ServerDescription.java, driver-core/src/test/unit/com/mongodb/internal/operation/OperationUnitSpecification.groovy
This is the maxWireVersion reported by MongoDB 5.1.
JAVA-4306
=> Bump maximum supported driver wire version to 14.

driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnection.java, driver-core/src/test/unit/com/mongodb/internal/connection/InternalStreamConnectionSpecification.groovy
This fixed a bug in the synchronous driver in which the driver sends a CommandSucceededEvent,
followed by a CommandFailedEvent (for the same command) in the case were the server replied
successfully but the Decoder configured to decode the response throws an exception.
JAVA-4321
=> Ensure that either CommandFailedEvent or CommandSucceededEvent is published, but not both

.evergreen/.evg.yml, .evergreen/run-serverless-tests.sh, driver-core/src/test/resources/unified-test-format/load-balancers/cursors.json, driver-core/src/test/resources/unified-test-format/load-balancers/sdam-error-handling.json, driver-core/src/test/resources/unified-test-format/load-balancers/transactions.json, driver-sync/src/test/functional/com/mongodb/client/Fixture.java, driver-sync/src/test/functional/com/mongodb/client/InitialDnsSeedlistDiscoveryTest.java, driver-sync/src/test/functional/com/mongodb/client/RetryableWritesProseTest.java, driver-sync/src/test/functional/com/mongodb/client/ServerDiscoveryAndMonitoringProseTests.java, driver-sync/src/test/functional/com/mongodb/client/unified/Entities.java
JAVA-4279
I disabled a few prose spec tests that don't properly run in serverless.  I think some of them could be made to run given the time none of them seem like they are testing anything that is necessary to prove serverless is working.
There is also one change to the unified test runner, which required a change to the Fixture class.  I'll discuss that in an inline comment.
=> Run serverless tests against a load balancer

driver-core/src/main/com/mongodb/internal/operation/BatchCursor.java, driver-core/src/main/com/mongodb/internal/operation/ChangeStreamBatchCursor.java, driver-core/src/main/com/mongodb/internal/operation/ListCollectionsOperation.java, driver-core/src/main/com/mongodb/internal/operation/QueryBatchCursor.java, driver-core/src/test/functional/com/mongodb/internal/operation/QueryBatchCursorFunctionalSpecification.groovy, driver-legacy/src/test/functional/com/mongodb/DBCursorFunctionalSpecification.groovy, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/syncadapter/SyncChangeStreamIterable.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/syncadapter/SyncMongoCursor.java, driver-scala/src/it/scala/org/mongodb/scala/syncadapter/SyncChangeStreamIterable.scala, driver-scala/src/it/scala/org/mongodb/scala/syncadapter/SyncMongoCursor.scala, driver-sync/src/main/com/mongodb/client/MongoCursor.java, driver-sync/src/main/com/mongodb/client/internal/MongoBatchCursorAdapter.java, driver-sync/src/main/com/mongodb/client/internal/MongoChangeStreamCursorImpl.java, driver-sync/src/main/com/mongodb/client/internal/MongoMappingCursor.java, driver-sync/src/test/unit/com/mongodb/client/internal/MongoBatchCursorAdapterSpecification.groovy, driver-sync/src/test/unit/com/mongodb/client/internal/MongoChangeStreamCursorSpecification.groovy
JAVA-4167
Putting this in draft review to get feedback on the API, before writing any tests.  I went with adding an `available` method, as mentioned in my last comment on the ticket:
> Maybe instead of a new method to get documents from the cursor, we can have a new method that reports how many are currently available. This would be similar to the java.io.InputStream#available method in the JDK.
Here's what the reporter's code would look like with this API:
```
public static List<ChangeStreamDocument<Document>> getThingsToDo(MongoCollection<Document> collection) {
var changeStreamIterable = collection
.watch()
.batchSize(100)
.maxAwaitTime(5000, TimeUnit.MILLISECONDS);
List<ChangeStreamDocument<Document>> thingsToDo = new ArrayList<>();
try (var cursor = changeStreamIterable.cursor()) { …
```
=> Add MongoCursor#available

bson/src/main/org/bson/Document.java, bson/src/main/org/bson/codecs/ContainerCodecHelper.java, bson/src/main/org/bson/codecs/DocumentCodec.java, bson/src/main/org/bson/codecs/IterableCodec.java, bson/src/main/org/bson/codecs/MapCodec.java, bson/src/test/unit/org/bson/codecs/DocumentCodecSpecification.groovy
* Instead of using private methods within DocumentCodec to encode instances
of Iterable and Map, instead look up the Codec in the registry as with
any other instance.
* Instead of using a private method within DocumentCodec to decode BSON arrays,
instead lookup up the Codec in the registry according to the type mapped to
array in the BsonTypeClassMap.
JAVA-3925
I added a second commit as well to deduplicate the horrendous UUID-related code that exists in the three affected Codec implementations.
=> Use CodecRegistry in DocumentCodec for Iterable and Map instances

driver-core/src/main/com/mongodb/internal/connection/QueryResult.java, driver-core/src/main/com/mongodb/internal/operation/AsyncQueryBatchCursor.java, driver-core/src/main/com/mongodb/internal/operation/QueryBatchCursor.java
* The logger name is "org.mongodb.driver.operation"
* The message is "Received batch of %s documents with cursorId %d from server %s"
* It logs the initial results and results from each getMore
JAVA-4377
=> Log cursor results at debug level

driver-core/src/main/com/mongodb/AutoEncryptionSettings.java, driver-core/src/main/com/mongodb/ClientEncryptionSettings.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/crypt/Crypts.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/crypt/KeyManagementService.java, driver-sync/src/main/com/mongodb/client/internal/Crypt.java, driver-sync/src/main/com/mongodb/client/internal/Crypts.java, driver-sync/src/main/com/mongodb/client/internal/KeyManagementService.java, driver-sync/src/test/functional/com/mongodb/client/AbstractClientSideEncryptionKmsTlsTest.java
=> Add SSLContext configuration per KMS provider

driver-core/src/main/com/mongodb/ConnectionString.java, driver-core/src/main/com/mongodb/connection/ConnectionPoolSettings.java, driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java, driver-core/src/test/functional/com/mongodb/internal/connection/DefaultConnectionPoolTest.java, driver-core/src/test/unit/com/mongodb/ConnectionStringSpecification.groovy, driver-core/src/test/unit/com/mongodb/connection/ConnectionPoolSettingsSpecification.groovy, driver-legacy/src/main/com/mongodb/MongoClientOptions.java, driver-legacy/src/main/com/mongodb/MongoClientURI.java, driver-legacy/src/test/unit/com/mongodb/MongoClientOptionsSpecification.groovy, driver-legacy/src/test/unit/com/mongodb/MongoClientURISpecification.groovy
The changes in this PR that affect public API are conditional on the reviewers of https://github.com/mongodb/specifications/pull/1098 accepting the `maxConnection` option name. This PR also does not include specification tests, which may appear in the aforementioned PR as a result of the review process. The PR is submitter prematurely in case we want to include it in release 4.4 despite the corresponding [DRIVERS-1943](https://jira.mongodb.org/browse/DRIVERS-1943) not being ready for implementation.
JAVA-4390
=> Make maxConnecting configurable

driver-core/src/main/com/mongodb/internal/operation/FindAndModifyHelper.java, driver-core/src/main/com/mongodb/internal/operation/WriteConcernHelper.java
The error labels are at the top level of the response
document, and the code was assuming that they were
embedded in the writeConcernError document.  This fix
ensures that error labels at the top level are properly
added to MongoWriteConcernException
JAVA-4419
Note: this change is tested in scope of JAVA-4382 spec test changes, which will follow in a separate PR
=> Add error labels to MongoWriteConcernException

driver-core/src/test/resources/unified-test-format/command-monitoring/pre-42-server-connection-id.json, driver-core/src/test/resources/unified-test-format/command-monitoring/server-connection-id.json, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/unified/CommandMonitoringTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/CommandMonitoringTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/EventMatcher.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java
The driver already supports the feature, so this is just test changes.
It includes support for version 1.6 of the unified test format.
JAVA-4238
=> Add command monitoring unified tests for serverConnectionId

driver-core/src/main/com/mongodb/internal/connection/ConnectionPool.java, driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java, driver-core/src/main/com/mongodb/internal/connection/DefaultSdamServerDescriptionManager.java, driver-core/src/test/functional/com/mongodb/internal/connection/DefaultConnectionPoolTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/AbstractConnectionPoolTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/DefaultConnectionPoolSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/DefaultServerSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/TestConnectionPool.java
After this [Slack discussion](https://mongodb.slack.com/archives/G016S9LLKU2/p1638376906000700), I realized that there is no reason for us to have both `ConnectionPool.invalidate()` and `ConnectionPool.invalidate(Throwable)`. Moreover, I noticed that there are situations when `DefaultSdamServerDescriptionManager` calls `invalidate` without specifying the cause despite it being known. This PR fixes the discovered issue and removes the unnecessary method.
=> Always specify the known cause when calling `ConnectionPool.invalidate`

driver-legacy/src/main/com/mongodb/Cursor.java, driver-legacy/src/main/com/mongodb/DBCursor.java, driver-legacy/src/main/com/mongodb/MongoCursorAdapter.java, driver-legacy/src/test/functional/com/mongodb/DBCollectionAggregationTest.java, driver-legacy/src/test/functional/com/mongodb/DBCursorTest.java, driver-sync/src/main/com/mongodb/client/MongoCursor.java
The new methods are
* com.mongodb.DBCursor#available
* com.mongodb.Cursor#available
with the same semantics as the recently added
* com.mongodb.client.MongoCursor#available
JAVA-4422
=> Add #available method to legacy cursor API

driver-core/src/main/com/mongodb/connection/ClusterSettings.java, driver-core/src/main/com/mongodb/connection/ConnectionPoolSettings.java, driver-core/src/main/com/mongodb/connection/ServerSettings.java, driver-core/src/test/unit/com/mongodb/connection/ClusterSettingsSpecification.groovy, driver-core/src/test/unit/com/mongodb/connection/ConnectionPoolSettingsSpecification.groovy, driver-core/src/test/unit/com/mongodb/connection/ServerSettingsSpecification.groovy
[JAVA-4317](https://jira.mongodb.org/browse/JAVA-4317)
This PR adds the ability to override listeners in `ClusterSettings`, `ServerSettings` and `ConnectionPoolSettings` by allowing the user to provide a list of listeners. These changes have been modeled after `MongoClientSettings.Builder#commandListenerList`.
QA Performed: Amended unit tests where appropriate.
=> JAVA-4317: Add methods to override listeners in ClusterSettings, ServerSettings and ConnectionPoolSettings

driver-core/src/main/com/mongodb/internal/operation/BulkWriteBatch.java, driver-core/src/test/unit/com/mongodb/internal/operation/BulkWriteBatchSpecification.groovy
The previous code was incorrect because it was comparing absolute write indexes
with indexes that are relative to the current batch. This patch avoids that
by using the insertedId map from SplittablePayload directly, which already
contains absolute write indexes.
JAVA-4436
=> Ensure insertedIds contain ids from all batches

driver-core/src/main/com/mongodb/internal/connection/tlschannel/async/AsynchronousTlsChannelGroup.java
This is a backport of https://github.com/mongodb/mongo-java-driver/pull/848
JAVA-4417
=> Merge changes from tls-channel for race condition manifested when closing async sockets right after creation

bson/src/main/org/bson/codecs/EnumCodec.java, bson/src/main/org/bson/codecs/EnumCodecProvider.java, bson/src/main/org/bson/codecs/pojo/EnumPropertyCodecProvider.java, bson/src/main/org/bson/conversions/Bson.java, bson/src/test/unit/org/bson/codecs/CodecTestCase.java, bson/src/test/unit/org/bson/codecs/EnumCodecProviderTest.java, bson/src/test/unit/org/bson/codecs/EnumCodecTest.java, bson/src/test/unit/org/bson/codecs/SimpleEnum.java, bson/src/test/unit/org/bson/codecs/pojo/PojoCustomTest.java, bson/src/test/unit/org/bson/codecs/pojo/PojoRoundTripTest.java, bson/src/test/unit/org/bson/codecs/pojo/PojoTestCase.java, bson/src/test/unit/org/bson/codecs/pojo/entities/SimpleEnumModel.java, driver-core/src/main/com/mongodb/MongoClientSettings.java
JAVA-4440
One question I have is whether to keep `org.bson.codecs.pojo.EnumPropertyCodecProvider` around, or just remove it.  I'm comfortable with leaving it, but wonder what others think.
=> Add codec provider for enums

config/spotbugs/exclude.xml, driver-core/src/main/com/mongodb/internal/connection/ConcurrentPool.java, driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java
Another tiny change is moving `pool.release(openConnection)` out of the guarded section
in `DefaultConnectionPool.OpenConcurrencyLimiter.tryHandOverOrRelease`:
it does not have to be guarded, and when not only fair locking is used,
this change has a significant positive measurable effect
on the connection cycle (check out/check in) throughput.
JAVA-4452
=> Alternate fair/unfair lock modes in the connection pool to improve throughput

bson/src/main/org/bson/types/ObjectId.java
The javadoc for `ObjectId(timestamp, counter)` states that it "Creates an ObjectId using the given time, machine identifier, process identifier, and counter", but the constructor only takes two parameters, `timestamp` and `counter`.
The exception message in ObjectId(timestamp, randomValue1, randomValue2, counter) states that "The machine identifier must be between 0 and 16777215", although the exception is thrown when `(randomValue1 & 0xff000000) != 0`.
When running tests the following two failed: 
```
> Task :driver-scala:integrationTest
Running Test task using scala version: 2.13.6
org.mongodb.scala.gridfs.GridFSObservableSpec > The Scala driver should not create indexes if the files collection is not empty FAILED
org.scalatest.concurrent.Futures$FutureConcept$$anon$1 at …
```
=> Fixed javadoc for ObjectId(timestamp, counter) and exception message for ObjectId(timestamp, randomValue1, randomValue2, counter)

bson/src/main/org/bson/codecs/pojo/PojoBuilderHelper.java, bson/src/main/org/bson/codecs/pojo/PropertyReflectionUtils.java
`getParameterTypes().length` is inefficient because it creates an array clone, while `getParameterCount()` directly returns the number of parameters.
=> Replace getParameterTypes().length with getParameterCount()

driver-core/src/main/com/mongodb/internal/connection/AbstractMultiServerCluster.java, driver-core/src/main/com/mongodb/internal/connection/BaseCluster.java, driver-core/src/main/com/mongodb/internal/connection/Cluster.java, driver-core/src/main/com/mongodb/internal/connection/ClusterableServerFactory.java, driver-core/src/main/com/mongodb/internal/connection/DefaultClusterableServerFactory.java, driver-core/src/main/com/mongodb/internal/connection/DefaultSdamServerDescriptionManager.java, driver-core/src/main/com/mongodb/internal/connection/LoadBalancedCluster.java, driver-core/src/main/com/mongodb/internal/connection/LoadBalancedClusterableServerFactory.java, driver-core/src/main/com/mongodb/internal/connection/SingleServerCluster.java, driver-core/src/test/unit/com/mongodb/internal/connection/AbstractConnectionPoolTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/DefaultServerSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/DefaultTestClusterableServerFactory.java, driver-core/src/test/unit/com/mongodb/internal/connection/LoadBalancedClusterTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/SrvPollingProseTests.java, driver-core/src/test/unit/com/mongodb/internal/connection/TestClusterableServerFactory.java
See this [comment](https://jira.mongodb.org/browse/JAVA-4471?focusedCommentId=4336655&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4336655) for the details on what this PR fixes. The idea is to guard the action of pausing/unpausing a pool with the same cluster-wide lock that is used to guard the cluster state.
There will be one more PR that tries to get rid of some fields and params that duplicate the information that can be accessed via `Cluster`.
JAVA-4471
=> Introduce and use `Cluster.withLock` to achieve cluster-wide locking

driver-core/src/main/com/mongodb/internal/async/client/ClientSessionBinding.java, driver-core/src/main/com/mongodb/internal/binding/AbstractReferenceCounted.java, driver-core/src/main/com/mongodb/internal/binding/AsyncClusterAwareReadWriteBinding.java, driver-core/src/main/com/mongodb/internal/binding/AsyncClusterBinding.java, driver-core/src/main/com/mongodb/internal/binding/ClusterBinding.java, driver-core/src/main/com/mongodb/internal/binding/ReferenceCounted.java, driver-core/src/main/com/mongodb/internal/binding/SingleServerBinding.java, driver-core/src/main/com/mongodb/internal/binding/TransactionContext.java, driver-core/src/main/com/mongodb/internal/connection/AbstractReferenceCounted.java, driver-core/src/main/com/mongodb/internal/connection/DefaultServer.java, driver-core/src/main/com/mongodb/internal/connection/DefaultServerConnection.java, driver-core/src/test/functional/com/mongodb/client/syncadapter/SyncConnection.java, driver-core/src/test/functional/com/mongodb/internal/binding/AsyncSessionBinding.java, driver-core/src/test/functional/com/mongodb/internal/binding/AsyncSingleConnectionBinding.java, driver-core/src/test/functional/com/mongodb/internal/binding/SessionBinding.java, driver-core/src/test/functional/com/mongodb/internal/binding/SingleConnectionBinding.java, driver-core/src/test/unit/com/mongodb/internal/async/client/ClientSessionBindingSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/TestConnection.java, driver-core/src/test/unit/com/mongodb/internal/operation/AsyncQueryBatchCursorSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/operation/QueryBatchCursorSpecification.groovy, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/crypt/CryptBinding.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/crypt/CryptConnection.java, driver-sync/src/main/com/mongodb/client/internal/ClientSessionBinding.java, driver-sync/src/main/com/mongodb/client/internal/CryptBinding.java, driver-sync/src/main/com/mongodb/client/internal/CryptConnection.java
=> Make reference count check atomic with release

driver-core/src/main/com/mongodb/internal/async/client/ClientSessionBinding.java, driver-core/src/main/com/mongodb/internal/connection/Cluster.java
Getting the description from a cluster can throw a
MongoTimeoutException or a MongoInterruptedException.
So in that case the exception should be passed to
the callback.
JAVA-4432
=> Ensure callback using cluster description is guarded

driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnection.java
Hey Mongo team.
My team experienced an increased number of failures caused by latency recently. Further investigation showed that InternalStreamConnection doesn't close buffers returned by PowerOfTwoBufferPool when compression is enabled. It leads to permits leakage. After INTEGER_MAX buffer retrievals buffer pool is fully exhausted and all following requests would be blocked indefinitely unless the thread gets interrupted. 
JAVA-4510
=> ByteBuffer is not released when compression is enabled, causing pool leakage

driver-core/src/main/com/mongodb/internal/operation/CommandOperationHelper.java, driver-core/src/test/resources/unified-test-format/retryable-reads/handshakeError.json, driver-core/src/test/resources/unified-test-format/retryable-writes/handshakeError.json, driver-core/src/test/resources/unified-test-format/transactions/retryable-abort-handshake.json, driver-core/src/test/resources/unified-test-format/transactions/retryable-commit-handshake.json, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/unified/UnifiedRetryableReadsTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedRetryableReadsTest.java
=> Drivers should retry operations if connection handshake fails

.evergreen/.evg.yml, .evergreen/run-csfle-aws-from-environment.sh, build.gradle, driver-core/src/main/com/mongodb/internal/capi/MongoCryptHelper.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/crypt/Crypt.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/crypt/Crypts.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/ClientSideEncryptionAwsCredentialFromEnvironmentTest.java, driver-sync/src/main/com/mongodb/client/internal/Crypt.java, driver-sync/src/main/com/mongodb/client/internal/Crypts.java, driver-sync/src/test/functional/com/mongodb/client/AbstractClientSideEncryptionAwsCredentialFromEnvironmentTest.java, driver-sync/src/test/functional/com/mongodb/client/ClientSideEncryptionAwsCredentialFromEnvironmentTest.java
Links useful for reviewers:
- [Summary of changes for bindings and drivers to add support for on-demand credentials in AWS](https://jira.mongodb.org/browse/MONGOCRYPT-382?focusedCommentId=4401229&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4401229).
- [New mongodb-crypt API](https://github.com/mongodb/libmongocrypt/commit/a6a17a052e86a21910d9e924923c183919797fc7).
JAVA-4503
=> Support NEED_KMS_CREDENTIALS state for CSFLE

driver-core/build.gradle
JAVA-4505
Examined the MANIFEST.MF after publishing to Maven local and no longer see `javax.annotation`.
=> Exclude javax.annotation.* from OSGi imports

bson/src/main/org/bson/codecs/BsonCodecProvider.java, bson/src/main/org/bson/codecs/BsonValueCodecProvider.java, bson/src/main/org/bson/codecs/DocumentCodecProvider.java, bson/src/main/org/bson/codecs/EnumCodecProvider.java, bson/src/main/org/bson/codecs/IterableCodecProvider.java, bson/src/main/org/bson/codecs/JsonObjectCodecProvider.java, bson/src/main/org/bson/codecs/MapCodecProvider.java, bson/src/main/org/bson/codecs/ValueCodecProvider.java, bson/src/main/org/bson/codecs/configuration/MapOfCodecsProvider.java, bson/src/main/org/bson/codecs/jsr310/Jsr310CodecProvider.java, bson/src/main/org/bson/internal/OverridableUuidRepresentationCodecRegistry.java, bson/src/main/org/bson/internal/ProvidersCodecRegistry.java, driver-core/src/main/com/mongodb/AutoEncryptionSettings.java, driver-core/src/main/com/mongodb/DBObjectCodecProvider.java, driver-core/src/main/com/mongodb/DBRefCodecProvider.java, driver-core/src/main/com/mongodb/MongoClientSettings.java, driver-core/src/main/com/mongodb/ReadConcern.java, driver-core/src/main/com/mongodb/WriteConcern.java, driver-core/src/main/com/mongodb/client/gridfs/codecs/GridFSFileCodecProvider.java, driver-core/src/main/com/mongodb/client/model/geojson/codecs/GeoJsonCodecProvider.java, driver-core/src/main/com/mongodb/internal/connection/AbstractMultiServerCluster.java, driver-core/src/main/com/mongodb/internal/connection/SingleServerCluster.java, driver-legacy/src/main/com/mongodb/MongoClient.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/MongoClients.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/MongoClientImpl.java, driver-reactive-streams/src/test/unit/com/mongodb/reactivestreams/client/internal/MongoClientImplTest.java, driver-sync/src/main/com/mongodb/client/internal/MongoClientImpl.java
- Fix/update/add toString methods for classes referenced by MongoClientSettings
- include client metadata document as JSON
- include MongoClientSettings#toString
JAVA-4439
Sample log message with default settings:
```
10:48:53.340 [Test worker] INFO  org.mongodb.driver.client - MongoClient with metadata 
{"driver": {"name": "mongo-java-driver|sync", "version": "4.5.0"}, "os": {"type": "Darwin", "name": "Mac OS X", "architecture": "x86_64", "version": "11.6.4"}, "platform": "Java/Oracle Corporation/17+35-LTS-2724"} 
created with settings 
MongoClientSettings{readPreference=ReadPreference{name=secondary, hedgeOptions=null}, writeConcern=WriteConcern{w=majority, wTimeout=null ms, journal=null}, retryWrites=true, retryReads=true, readConcern=ReadConcern{level=MAJORITY}, credential=null, …
```
=> Improve info-level logging for MongoClient construction 

driver-core/src/main/com/mongodb/AutoEncryptionSettings.java, driver-core/src/main/com/mongodb/ClientEncryptionSettings.java, driver-core/src/main/com/mongodb/internal/capi/MongoCryptHelper.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/crypt/Crypt.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/crypt/Crypts.java, driver-sync/src/main/com/mongodb/client/internal/Crypt.java, driver-sync/src/main/com/mongodb/client/internal/Crypts.java, driver-sync/src/test/functional/com/mongodb/client/AbstractClientSideEncryptionAwsCredentialFromEnvironmentTest.java
=> Support configuration of KMS provider credentials with a Supplier

driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/SessionsProseTest.java, driver-sync/src/test/functional/com/mongodb/client/AbstractSessionsProseTest.java, driver-sync/src/test/functional/com/mongodb/client/SessionsProseTest.java
JAVA-4531
This prose test was originally reviewed as part of the [JAVA-4365 PR](https://github.com/mongodb/mongo-java-driver/pull/865/commits/49f6b172a3fd390589e375d9af73b57277e8376f), but was then removed as it was found to be flaky.  The updated prose test is intended to minimize the flakiness of the previous test.
=> Add client session re-use prose test

driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java, driver-core/src/test/functional/com/mongodb/internal/connection/DefaultConnectionPoolTest.java
=> Tolerate `DefaultConnectionPool.invalidate` being called after or concurrently with `close`

driver-core/src/test/resources/unified-test-format/change-streams/change-streams.json, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudHelper.java
Requires support for absent saveResultAsEntity, which is optional
JAVA-4369
This test was missed in the initial PR for comment support, and requires a few changes in the runner
=> Add unified change stream test for comment

README.md
I found a little problem in the build part of README.
The mongod can not start unless the data directory starts. So I think a `mkdir -p data/db` command should be added in README.
>The test suite requires mongod to be running with [`enableTestCommands`]>>(https://www.mongodb.com/docs/manual/reference/parameters/#param.enableTestCommands), which may be set with the `--setParameter enableTestCommands=1`
command-line parameter:
> ```
> $ mongod --dbpath ./data/db --logpath ./data/mongod.log --port 27017 --logappend --fork --setParameter  enableTestCommands=1
> ```
=> The data directory must be created before a mongod starts

driver-core/src/test/resources/unified-test-format/change-streams/change-streams.json, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/unified/ChangeStreamsTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/EventMatcher.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java
* Add support for ignoreExtraEvents in unified test runner. (note: this is a new option and not yet out of spec review, but looks like this is what it's going to look like)
* Update change stream tests to specify ignoreExtraEvents
* Update reactive change stream test runner to skip tests where extra getMore events occur between required events
* Update reactive change stream test runner to skip tests that require change stream initialization to report an error
* Enable artificial delay for change stream tests that expect an event when change stream is initialized
JAVA-4369
=> Fix or skip new failing unified change stream tests

driver-core/src/main/com/mongodb/internal/connection/ConcurrentPool.java
This PR mostly replaces `ReentrantReadWriteLock` in `ConcurrentPool.StateAndPermits.lock` with `ReentrantLock`, and simplifies `StateAndPermits.throwIfClosedOrPaused`.
Originally `throwIfClosedOrPaused` was called by threads that do not necessary held an exclusive lock, so the method had to make sure it cannot be executed concurrently with the code that modifies the `StateAndPermits.paused` field (we don't have the same care about the `closed` field because unlike `paused`, it is flipped at most once). However, in order to allow `throwIfClosedOrPaused` to be executed concurrently with itself, it acquired a shared lock.
Then I noticed that each time `throwIfClosedOrPaused` is called by a thread that does not hold an exclusive lock, the thread then calls another method of `StateAndPermits` …
=> Simplify `ConcurrentPool`

bson-record-codec/build.gradle, bson-record-codec/src/test/unit/org/bson/codecs/record/RecordCodecProviderTest.java, driver-core/build.gradle, driver-core/src/main/com/mongodb/Jep395RecordCodecProvider.java, driver-core/src/main/com/mongodb/MongoClientSettings.java, driver-core/src/test/unit/com/mongodb/Jep395RecordCodecProviderTest.java, driver-scala/src/test/scala/org/mongodb/scala/ApiAliasAndCompanionSpec.scala
Add dependency in core to bson-record-codec
Wrap the RecordCodecProvider with a canary check so support is only added if the JDK version supports it.
JAVA-3567
=> Add Java record support to the default registry

driver-sync/src/main/com/mongodb/client/internal/ClientSessionImpl.java
catching RuntimeException all other subclasses of Exception are not caught and don't abort the transaction
=> fix: abort transaction in all cases

driver-core/src/test/resources/unified-test-format/crud/bulkWrite-comment.json, driver-core/src/test/resources/unified-test-format/crud/bulkWrite-replaceOne-let.json, driver-core/src/test/resources/unified-test-format/crud/replaceOne-comment.json, driver-core/src/test/resources/unified-test-format/crud/replaceOne-let.json, driver-core/src/test/resources/unified-test-format/crud/updateMany-comment.json, driver-core/src/test/resources/unified-test-format/crud/updateMany-let.json, driver-core/src/test/resources/unified-test-format/crud/updateOne-comment.json, driver-core/src/test/resources/unified-test-format/crud/updateOne-let.json
* Modifications made in a previous commit of bulkWrite-comment.json
had to be preserved, so this is not an exact copy of the spec tests
* Modifications to require minServerVersion of 3.6 also had to be preserved,
since Java driver still supports older server versions
JAVA-4568
=> Use $$unsetOrMatches for upsert and multi in spec tests

driver-core/src/main/com/mongodb/client/model/changestream/ChangeStreamDocument.java, driver-core/src/main/com/mongodb/client/model/changestream/ChangeStreamDocumentCodec.java, driver-core/src/main/com/mongodb/client/model/changestream/FullDocument.java, driver-core/src/main/com/mongodb/client/model/changestream/FullDocumentBeforeChange.java, driver-core/src/main/com/mongodb/internal/operation/ChangeStreamOperation.java, driver-core/src/test/functional/com/mongodb/internal/operation/ChangeStreamOperationProseTestSpecification.groovy, driver-core/src/test/functional/com/mongodb/internal/operation/ChangeStreamOperationSpecification.groovy, driver-core/src/test/resources/unified-test-format/change-streams/change-streams-pre_and_post_images.json, driver-core/src/test/unit/com/mongodb/client/model/changestream/ChangeStreamDocumentCodecSpecification.groovy, driver-core/src/test/unit/com/mongodb/client/model/changestream/ChangeStreamDocumentSpecification.groovy, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/ChangeStreamPublisher.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/ChangeStreamPublisherImpl.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/syncadapter/SyncChangeStreamIterable.java, driver-reactive-streams/src/test/unit/com/mongodb/reactivestreams/client/internal/ChangeStreamPublisherImplTest.java, driver-scala/src/it/scala/org/mongodb/scala/syncadapter/SyncChangeStreamIterable.scala, driver-scala/src/main/scala/org/mongodb/scala/ChangeStreamObservable.scala, driver-scala/src/main/scala/org/mongodb/scala/model/changestream/FullDocument.scala, driver-scala/src/main/scala/org/mongodb/scala/model/changestream/FullDocumentBeforeChange.scala, driver-scala/src/main/scala/org/mongodb/scala/model/changestream/package.scala, driver-scala/src/test/scala/org/mongodb/scala/ApiAliasAndCompanionSpec.scala, driver-sync/src/main/com/mongodb/client/ChangeStreamIterable.java, driver-sync/src/main/com/mongodb/client/internal/ChangeStreamIterableImpl.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudHelper.java, driver-sync/src/test/unit/com/mongodb/client/internal/ChangeStreamIterableSpecification.groovy
Change stream watch helpers now accept "whenAvailable" and "required" for the fullDocument option.
Additionally, a new fullDocumentBeforeChange option is introduced, which accepts "off", "whenAvailable" and
"required". Change events may now include a "fullDocumentBeforeChange" response field.
JAVA-4468
=> Enhance pre-and post-image support for change streams

driver-core/src/main/com/mongodb/client/model/WindowedComputations.java, driver-scala/src/main/scala/org/mongodb/scala/model/Aggregates.scala, driver-scala/src/main/scala/org/mongodb/scala/model/WindowedComputations.scala, driver-scala/src/test/scala/org/mongodb/scala/model/AggregatesSpec.scala
We also need to update the examples in https://mongodb.github.io/mongo-java-driver/4.6/driver-scala/builders/aggregation/#setwindowfields such that they wrap references in `Some` where needed: https://jira.mongodb.org/browse/DOCSP-22696.
JAVA-4583
=> Stop using `null` values in the Scala query building API for ``$setWindowFields`

driver-legacy/src/main/com/mongodb/MongoClientOptions.java, driver-legacy/src/test/unit/com/mongodb/MongoClientOptionsSpecification.groovy
JAVA-4621
Make `MongoClientOptions` aware of `maintenanceInitialDelayMs`. 
QA: Unit tests to check that the property propagates across `MongoClientOptions` and `MongoClientSettings`.
=> JAVA-4621: Add maintenanceInitialDelay to MongoClientOptions

driver-core/src/main/com/mongodb/Jep395RecordCodecProvider.java
The RecordCodecProvider uses JDK 17 LTS to compile.
Users maybe using older (non LTS) JDK's where records are supported.
JAVA-4605
=> RecordCodecProvider < JDK 17 canary test

driver-legacy/src/main/com/mongodb/DBCursor.java, driver-legacy/src/main/com/mongodb/DBCursorCleaner.java, driver-legacy/src/main/com/mongodb/Java8DBCursorCleaner.java, driver-legacy/src/main/com/mongodb/Java9DBCursorCleaner.java
JAVA-4612
I don't see a way to regression test this, given the nature of Java garbage collection.  I've proven to myself that it works in the debugger.
=> Use Cleaner for DBCursor cleanup when runtime is Java 9+

bson-scala/src/main/scala/org/mongodb/scala/bson/codecs/macrocodecs/MacroCodec.scala, bson-scala/src/test/scala/org/mongodb/scala/bson/codecs/MacrosSpec.scala
Fixes an issue when determining the codec to use for a
case class that contains a Map type that has a value that
contains the same key name and field name.
JAVA-4611
=> Fix Scala case class macro codec lookup bug

bson-record-codec/src/main/org/bson/codecs/record/RecordCodec.java, bson-record-codec/src/main/org/bson/codecs/record/annotations/BsonId.java, bson-record-codec/src/main/org/bson/codecs/record/annotations/BsonProperty.java, bson-record-codec/src/main/org/bson/codecs/record/annotations/BsonRepresentation.java, bson-record-codec/src/test/unit/org/bson/codecs/record/RecordCodecProviderTest.java, bson-record-codec/src/test/unit/org/bson/codecs/record/RecordCodecTest.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecord.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithDeprecatedAnnotations.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithIllegalBsonCreatorOnConstructor.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithIllegalBsonCreatorOnMethod.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithIllegalBsonDiscriminatorOnRecord.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithIllegalBsonExtraElementsOnAccessor.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithIllegalBsonExtraElementsOnComponent.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithIllegalBsonIdOnAccessor.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithIllegalBsonIdOnCanonicalConstructor.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithIllegalBsonIgnoreOnAccessor.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithIllegalBsonIgnoreOnComponent.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithIllegalBsonPropertyOnAccessor.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithIllegalBsonPropertyOnCanonicalConstructor.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithIllegalBsonRepresentationOnAccessor.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithPojoAnnotations.java, bson/src/main/org/bson/codecs/pojo/annotations/BsonCreator.java, bson/src/main/org/bson/codecs/pojo/annotations/BsonDiscriminator.java, bson/src/main/org/bson/codecs/pojo/annotations/BsonExtraElements.java, bson/src/main/org/bson/codecs/pojo/annotations/BsonId.java, bson/src/main/org/bson/codecs/pojo/annotations/BsonIgnore.java, bson/src/main/org/bson/codecs/pojo/annotations/BsonProperty.java, bson/src/main/org/bson/codecs/pojo/annotations/BsonRepresentation.java
JAVA-4622
Pros:
1. Less confusion for application writers.  There is no way to rely on the type system to prevent use of the existing annotations on records, so our options to restrict use are documentation, logging, or runtime exceptions 
2. Less namespace pollution with multiple attributes with the same name but different packages
Cons:
1. It's less clear which annotations are supported on records.  Currently only three are.  More could be, but some don't make sense for records
2. It relies on access to private fields in the record, which may be prevented in some deployments.  We could eventually fix this but not until Java 17 is our minimum
Decision:
Based on internal discussion, we've decided to deprecate the new annotations, support the existing ones when applied to the record …
=> Support the existing pojo annotations on records

driver-core/src/main/com/mongodb/client/model/Aggregates.java, driver-core/src/main/com/mongodb/client/model/MongoTimeUnit.java, driver-core/src/main/com/mongodb/client/model/Window.java, driver-core/src/main/com/mongodb/client/model/WindowedComputation.java, driver-core/src/main/com/mongodb/client/model/WindowedComputations.java, driver-core/src/main/com/mongodb/client/model/Windows.java, driver-scala/src/main/scala/org/mongodb/scala/model/Aggregates.scala, driver-scala/src/main/scala/org/mongodb/scala/model/WindowedComputations.scala, driver-scala/src/main/scala/org/mongodb/scala/model/package.scala
I checked that all window functions for which we have builders are in https://www.mongodb.com/docs/manual/reference/operator/aggregation/setWindowFields/, i.e., that no was removed, and that none of them is marked as "preview" when used with `$setWindowFields`.
Removing `@Beta` appears to be the only thing we need to do here.
JAVA-4559
=> Remove `@Beta` from query builders related to `$setWindowFields`

driver-core/src/main/com/mongodb/client/model/Accumulators.java, driver-core/src/main/com/mongodb/client/model/WindowedComputations.java, driver-core/src/test/functional/com/mongodb/client/model/AggregatesFunctionalSpecification.groovy, driver-core/src/test/unit/com/mongodb/client/model/AggregatesSpecification.groovy, driver-core/src/test/unit/com/mongodb/client/model/TestWindowedComputations.java, driver-scala/src/main/scala/org/mongodb/scala/model/Accumulators.scala, driver-scala/src/main/scala/org/mongodb/scala/model/WindowedComputations.scala, driver-scala/src/test/scala/org/mongodb/scala/model/AggregatesSpec.scala
Note that the links to server docs from API docs are not currently working. They will start working when MongoDB 6.0 become the "current" version. Depending when we anticipate 4.7 driver release and 6.0 MongoDB release, this may either be fine, or we may need to create a DOCSP request to prepare temporary https://dochub.mongodb.org/ URIs.
JAVA-4094
=> Add builders for pick-accumulators / window functions

driver-reactive-streams/src/examples/reactivestreams/tour/QuickTour.java
The QuickTour was calling await on the wrong subscriber.
=> Corrected successSubscriber to documentSubscriber for 2 awaits() in the QuickTour.

driver-core/src/main/com/mongodb/client/model/Aggregates.java, driver-core/src/main/com/mongodb/client/model/Window.java, driver-core/src/main/com/mongodb/client/model/WindowedComputation.java, driver-core/src/main/com/mongodb/client/model/WindowedComputations.java, driver-core/src/main/com/mongodb/client/model/Windows.java
We have just removed the `@Beta` from this API an have not yet released it without `@Beta`, which means, that regardless of whether this change breaks binary compatibility or not (I don't know and have not tried to find this out), the change is allowed.
=> Accept `Iterable` instead of `List` in `Aggregates.setWindowFields`

driver-core/src/main/com/mongodb/internal/connection/tlschannel/util/Util.java, driver-core/src/test/unit/com/mongodb/internal/connection/tlschannel/util/UtilTest.java
This is a manual cherry-pick and squash of the following commits:
- https://github.com/marianobarrios/tls-channel/commit/3b5f8a0bb592dd918b6641d771fc83d9a5c3d1ca
- https://github.com/marianobarrios/tls-channel/commit/f4b780e10c42c8a49e39f92d43fcb0179131124d
We don't test against JDK 18, and definitely not against early access builds. A manual test confirms that `18-ea` mentioned is the ticket is parsed successfully by the updated code.
The ticket does not specify the version the client uses. I am planning to backport the fix only to 4.6.x.
JAVA-4656
=> Fix `tlschannel.util.Util.getJavaMajorVersion`

driver-core/src/main/com/mongodb/client/model/Aggregates.java, driver-core/src/main/com/mongodb/client/model/search/SearchOptions.java, driver-core/src/test/functional/com/mongodb/client/model/search/AggregatesSearchIntegrationTest.java, driver-core/src/test/unit/com/mongodb/client/model/AggregatesSpecification.groovy, driver-core/src/test/unit/com/mongodb/client/model/search/SearchOptionsTest.java, driver-scala/src/main/scala/org/mongodb/scala/model/Aggregates.scala, driver-scala/src/main/scala/org/mongodb/scala/model/search/SearchOptions.scala, driver-scala/src/test/scala/org/mongodb/scala/model/AggregatesSpec.scala
- Rename `SearchOptions.defaultSearchOptions` to `searchOptions`
- Stop allowing `null` `SearchOptions` in `Aggregates.search`/`searchMeta`
=> Do misc `$search` improvements

config/codenarc/codenarc.xml, driver-core/src/main/com/mongodb/client/model/Aggregates.java, driver-core/src/main/com/mongodb/client/model/WindowedComputations.java, driver-core/src/main/com/mongodb/client/model/fill/FillComputation.java, driver-core/src/main/com/mongodb/client/model/fill/FillConstructibleBson.java, driver-core/src/main/com/mongodb/client/model/fill/FillConstructibleBsonElement.java, driver-core/src/main/com/mongodb/client/model/fill/FillOptions.java, driver-core/src/main/com/mongodb/client/model/fill/LinearFillComputation.java, driver-core/src/main/com/mongodb/client/model/fill/LocfFillComputation.java, driver-core/src/main/com/mongodb/client/model/fill/ValueFillComputation.java, driver-core/src/main/com/mongodb/client/model/fill/package-info.java, driver-core/src/test/functional/com/mongodb/client/model/AggregatesFunctionalSpecification.groovy, driver-core/src/test/unit/com/mongodb/client/model/AggregatesSpecification.groovy, driver-core/src/test/unit/com/mongodb/client/model/TestWindowedComputations.java, driver-core/src/test/unit/com/mongodb/client/model/fill/FillComputationTest.java, driver-core/src/test/unit/com/mongodb/client/model/fill/FillOptionsTest.java, driver-scala/src/main/scala/org/mongodb/scala/model/Aggregates.scala, driver-scala/src/main/scala/org/mongodb/scala/model/WindowedComputations.scala, driver-scala/src/main/scala/org/mongodb/scala/model/fill/FillComputation.scala, driver-scala/src/main/scala/org/mongodb/scala/model/fill/FillOptions.scala, driver-scala/src/main/scala/org/mongodb/scala/model/fill/fill.scala, driver-scala/src/test/scala/org/mongodb/scala/model/AggregatesSpec.scala
The new API:
- `WindowedComputations.locf` for [`$locf`](https://www.mongodb.com/docs/v6.0/reference/operator/aggregation/locf/)
- `WindowedComputations.linearFill` for [`$linearFill`](https://www.mongodb.com/docs/v6.0/reference/operator/aggregation/linearFill/)
- `Aggregates.fill` for [`$fill`](https://www.mongodb.com/docs/v6.0/reference/operator/aggregation/fill/)
The server-side syntax document is [here](https://docs.google.com/document/d/1pwIBc5XzbZkMnZH-FAoVYf2OOUzQM2VT8wbtoC4FMTg/edit#heading=h.pkrftzkil1l1).
You may see how the API usage looks like, or play with it in
- `AggregatesFunctionalSpecification.'$setWindowFields'`
- `AggregatesFunctionalSpecification.'$fill'`
JAVA-4394
=> Add query building API for the `$fill` aggregation pipeline stage

driver-core/src/main/com/mongodb/internal/operation/ChangeStreamOperation.java, driver-core/src/test/resources/unified-test-format/change-streams/change-streams-showExpandedEvents.json, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/ChangeStreamPublisher.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/ChangeStreamPublisherImpl.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/syncadapter/SyncChangeStreamIterable.java, driver-scala/src/main/scala/org/mongodb/scala/ChangeStreamObservable.scala, driver-scala/src/test/scala/org/mongodb/scala/ChangeStreamObservableSpec.scala, driver-sync/src/main/com/mongodb/client/ChangeStreamIterable.java, driver-sync/src/main/com/mongodb/client/internal/ChangeStreamIterableImpl.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudHelper.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java
=> Add showExpandedEvents to change stream pipeline stage

bson/src/test/unit/org/bson/json/JsonReaderTest.java, driver-core/src/main/com/mongodb/connection/TlsChannelStreamFactoryFactory.java, driver-core/src/main/com/mongodb/internal/async/client/ClientSessionBinding.java, driver-core/src/main/com/mongodb/internal/async/function/RetryState.java, driver-core/src/main/com/mongodb/internal/async/function/RetryingSyncSupplier.java, driver-core/src/main/com/mongodb/internal/connection/AsynchronousClusterEventListener.java, driver-core/src/main/com/mongodb/internal/connection/ConcurrentPool.java, driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java, driver-core/src/main/com/mongodb/internal/connection/DefaultDnsSrvRecordMonitor.java, driver-core/src/main/com/mongodb/internal/connection/DefaultServerMonitor.java, driver-core/src/main/com/mongodb/internal/connection/GetMoreProtocol.java, driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnection.java, driver-core/src/main/com/mongodb/internal/connection/KillCursorProtocol.java, driver-core/src/main/com/mongodb/internal/connection/ProtocolHelper.java, driver-core/src/main/com/mongodb/internal/connection/QueryProtocol.java, driver-core/src/main/com/mongodb/internal/connection/WriteProtocol.java, driver-core/src/main/com/mongodb/internal/connection/ZstdCompressor.java, driver-core/src/main/com/mongodb/internal/event/ConnectionPoolListenerMulticaster.java, driver-core/src/main/com/mongodb/internal/operation/AsyncChangeStreamBatchCursor.java, driver-core/src/main/com/mongodb/internal/operation/OperationHelper.java, driver-core/src/main/com/mongodb/internal/operation/QueryBatchCursor.java, driver-core/src/test/functional/com/mongodb/client/model/search/AggregatesSearchIntegrationTest.java, driver-core/src/test/functional/com/mongodb/internal/connection/DefaultConnectionPoolTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/TestInternalConnection.java, driver-sync/src/test/functional/com/mongodb/client/AbstractClientSideEncryptionTest.java, driver-sync/src/test/functional/com/mongodb/client/AbstractRetryableWritesTest.java, driver-sync/src/test/functional/com/mongodb/client/AbstractUnifiedTest.java, driver-sync/src/test/functional/com/mongodb/client/WithTransactionProseTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTestFailureValidator.java
Kotlin does not support checked exceptions, so our handlers will use Exception. All handlers are replaced, even those obviously unaffected, for the sake of a consistent noticeable pattern.
JAVA-4575
=> Replace RuntimeException in catch with Exception to support Kotlin

driver-core/src/main/com/mongodb/client/model/Aggregates.java, driver-core/src/main/com/mongodb/client/model/MongoTimeUnit.java, driver-core/src/main/com/mongodb/client/model/Windows.java, driver-core/src/main/com/mongodb/client/model/densify/DateDensifyRange.java, driver-core/src/main/com/mongodb/client/model/densify/DensifyConstructibleBson.java, driver-core/src/main/com/mongodb/client/model/densify/DensifyOptions.java, driver-core/src/main/com/mongodb/client/model/densify/DensifyRange.java, driver-core/src/main/com/mongodb/client/model/densify/NumberDensifyRange.java, driver-core/src/main/com/mongodb/client/model/densify/package-info.java, driver-core/src/test/functional/com/mongodb/client/model/AggregatesFunctionalSpecification.groovy, driver-core/src/test/unit/com/mongodb/client/model/AggregatesSpecification.groovy, driver-core/src/test/unit/com/mongodb/client/model/TestWindows.java, driver-core/src/test/unit/com/mongodb/client/model/densify/DensifyOptionsTest.java, driver-core/src/test/unit/com/mongodb/client/model/densify/DensifyRangeTest.java, driver-scala/src/main/scala/org/mongodb/scala/model/Aggregates.scala, driver-scala/src/main/scala/org/mongodb/scala/model/densify/DensifyOptions.scala, driver-scala/src/main/scala/org/mongodb/scala/model/densify/DensifyRange.scala, driver-scala/src/main/scala/org/mongodb/scala/model/densify/package.scala, driver-scala/src/main/scala/org/mongodb/scala/model/package.scala, driver-scala/src/test/scala/org/mongodb/scala/model/AggregatesSpec.scala
The new API:
- Aggregates.densify for [`$densify`](https://www.mongodb.com/docs/v6.0/reference/operator/aggregation/densify/)
The server-side syntax document is [here](https://docs.google.com/document/d/1pwIBc5XzbZkMnZH-FAoVYf2OOUzQM2VT8wbtoC4FMTg/edit#heading=h.sshyb2wdxr2w).
You may see how the API usage looks like, or play with it in
- `AggregatesFunctionalSpecification.'$densify'`
JAVA-4350
=> Add query building API for the `$densify` aggregation pipeline stage

driver-core/src/main/com/mongodb/internal/operation/OperationHelper.java, driver-core/src/test/resources/unified-test-format/transactions/do-not-retry-read-in-transaction.json, driver-core/src/test/unit/com/mongodb/internal/operation/OperationHelperSpecification.groovy
Fixes a regression introduced in 4.4.0 in scope of JAVA-4034, and
was undetected due to the lack of a specification test for the
required behavior.
JAVA-4684
=> Do not retry a read operation when in a transaction

driver-sync/src/test/functional/com/mongodb/client/AbstractClientSideEncryptionExplicitEncryptionTest.java
JAVA-4623
I tried to also re-enable the other prose tests but those still [failed](https://spruce.mongodb.com/task/mongo_java_driver_tests_serverless__os~ubuntu_jdk~jdk17_serverless_test_patch_afb5d0ae6693d1915b7afa3b84d250974fe15998_62deda02562343035a9adc1b_22_07_25_17_59_46/tests?execution=0&sortBy=STATUS&sortDir=ASC) with an error about being unable to find mongocryptd, so I limited it to just the explicit encryption tests, which do now pass.
=> Re-enable ClientSideEncryptionExplicitEncryptionTest for serverless

bson/src/main/org/bson/AbstractBsonWriter.java, bson/src/main/org/bson/FieldNameValidator.java, bson/src/test/unit/org/bson/BsonWriterSpecification.groovy, driver-core/src/main/com/mongodb/internal/validator/MappedFieldNameValidator.java, driver-core/src/main/com/mongodb/internal/validator/ReplacingDocumentFieldNameValidator.java, driver-core/src/main/com/mongodb/internal/validator/UpdateFieldNameValidator.java, driver-core/src/test/functional/com/mongodb/internal/operation/FindAndReplaceOperationSpecification.groovy, driver-core/src/test/functional/com/mongodb/internal/operation/FindAndUpdateOperationSpecification.groovy, driver-core/src/test/functional/com/mongodb/internal/operation/MixedBulkWriteOperationSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/validator/ReplacingDocumentFieldNameValidatorTest.java
For replacement documents, it's now:
"Field names in a replacement document can not start with '$' but '%s' does"
For update documents, it's now:
"All update operators must start with '$', but '%s' does not"
JAVA-2114
=> Improve error message for invalid field names

driver-core/src/main/com/mongodb/KerberosSubjectProvider.java, driver-core/src/main/com/mongodb/internal/CheckedSupplier.java, driver-core/src/main/com/mongodb/internal/Locks.java, driver-core/src/main/com/mongodb/internal/connection/BaseCluster.java, driver-core/src/main/com/mongodb/internal/connection/ClusterClock.java, driver-core/src/main/com/mongodb/internal/connection/MongoCredentialWithCache.java, driver-core/src/main/com/mongodb/internal/connection/SaslAuthenticator.java, driver-sync/src/main/com/mongodb/client/gridfs/GridFSDownloadStreamImpl.java, driver-sync/src/main/com/mongodb/client/gridfs/GridFSUploadStreamImpl.java
In order to get the benefit for structured concurrency, the driver
must use Lock#lockInterruptibly rather than simply Lock#lock.
JAVA-4642
What use of `synchrnonized` is left out of this PR?
* Used in the bson module: I didn't include this because `MongoInterruptedException` is in driver-core, not bson, so it wasn't clear what exception should be thrown.  So deferring this for now
* Use in driver-legacy. Generally we don't make improvements in legacy
* Use in threads that the driver starts itself.  This can be done later if we ever move these to virtual threads.  But also, these threads are not accessible to applications so can't easily be interrupted.
* Use in asynchronous contexts.  Structured concurrency wouldn't be used with reactive streams, so it's not needed
* Use in tests. …
=> Replace synchronized with ReentrantLock

driver-sync/build.gradle, driver-sync/src/examples/documentation/ExampleAwsLambdaHandler.java, driver-sync/src/examples/documentation/TestAwsLambdaHandler.java
JAVA-4474
Note that there is only one example rather than a separate one for MONGODB-AWS authentication.  My argument for it is that the AWS credentials should properly be obtained by the driver via either environment variables or, perhaps, EC2 or ECS endpoints, and can be used just by specifying a MONGODB_URI environment variable like:
`mongodb+srv://<host>/?authMechanism=MONGODB-AWS`
=> Add AWS Lambda example

.evergreen/.evg.yml, .evergreen/run-mongodb-fle-gcp-auto.sh, build.gradle, driver-core/src/main/com/mongodb/internal/authentication/AwsCredentialHelper.java, driver-core/src/main/com/mongodb/internal/authentication/GcpCredentialHelper.java, driver-core/src/main/com/mongodb/internal/authentication/HttpHelper.java, driver-core/src/main/com/mongodb/internal/capi/MongoCryptHelper.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/ClientSideEncryptionOnDemandGcpCredentialsTest.java, driver-sync/src/test/functional/com/mongodb/client/AbstractClientSideEncryptionOnDemandGcpCredentialsTest.java, driver-sync/src/test/functional/com/mongodb/client/ClientSideEncryptionOnDemandGcpCredentialsTest.java
=> Support attached service accounts for GCP KMS

build.gradle, driver-benchmarks/build.gradle, driver-reactive-streams/build.gradle, driver-workload-executor/build.gradle
JAVA-4710
Note: Updating Jupiter dependency caused a strange Gradle build failure, so leaving that one alone for now.
=> Update project dependencies to latest available

build.gradle, driver-core/build.gradle
=> Update netty dependencies to use the netty-bom

driver-core/src/main/com/mongodb/client/model/changestream/UpdateDescription.java, driver-core/src/test/resources/unified-test-format/change-streams/change-streams-disambiguatedPaths.json, driver-core/src/test/unit/com/mongodb/client/model/changestream/UpdateDescriptionSpecification.groovy
=> Add disambiguatedPaths field to ChangeStreamDocument

bson/src/main/org/bson/BsonDocumentWrapper.java, bson/src/main/org/bson/BsonTimestamp.java, bson/src/main/org/bson/types/CodeWithScope.java, bson/src/main/org/bson/types/Decimal128.java, driver-core/src/main/com/mongodb/BasicDBObjectBuilder.java, driver-core/src/main/com/mongodb/connection/ConnectionPoolSettings.java, driver-core/src/main/com/mongodb/event/ConnectionCheckOutStartedEvent.java, driver-core/src/main/com/mongodb/internal/async/function/AsyncCallbackFunction.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/syncadapter/SyncMongoClient.java
open the PR of typo correction, i found while using the driver for a long time.
--
I understood it to only open issues for features or bugs.
so,,, should i open an issue? if so, please tell me 🙇
=> Fix minor typos in java comments(javadoc) and all that minor typos

bson-record-codec/src/main/org/bson/codecs/record/RecordCodec.java, bson-record-codec/src/test/unit/org/bson/codecs/record/RecordCodecTest.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordEmbedded.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithListOfListOfRecords.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithListOfRecords.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithMapOfListOfRecords.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithMapOfRecords.java, bson/src/main/org/bson/codecs/AbstractIterableCodec.java, bson/src/main/org/bson/codecs/AbstractMapCodec.java, bson/src/main/org/bson/codecs/ContainerCodecHelper.java, bson/src/main/org/bson/codecs/IterableCodec.java, bson/src/main/org/bson/codecs/MapCodec.java, bson/src/main/org/bson/codecs/Parameterizable.java, bson/src/main/org/bson/codecs/ParameterizedIterableCodec.java, bson/src/main/org/bson/codecs/ParameterizedMapCodec.java, bson/src/test/unit/org/bson/codecs/IterableCodecSpecification.groovy, bson/src/test/unit/org/bson/codecs/MapCodecSpecification.groovy
This enhances the support for any record component that is a generic List or Map where the generic type of the List or Map value is a record or POJO.  It used to incorrectly decode to org.bson.Document. Now it respects the generic type of the List or Map value when decoding.
JAVA-4667
=> Support List<T> and Map<String, T> components in Java records

driver-core/src/main/com/mongodb/internal/connection/DefaultServerMonitor.java
There is a missing check in an already-complicated conditinal statement for whether to sleep in the server monitor before executing the next check.
The condition is included in the server discovery and monitoring specification pseudo-code but missing in the driver, and there are currently no tests for it.
This commits adds the missing condition to the conditional statement.  Effectively, this will reduce the number of sockets that the monitor opens on a server that is in the process of shutting down but still accepting connections.
JAVA-4730
=> Add missing condition for whether to sleep in server monitor

driver-core/src/main/com/mongodb/internal/capi/MongoCryptHelper.java, driver-core/src/test/functional/com/mongodb/internal/capi/MongoCryptHelperTest.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/crypt/CommandMarker.java, driver-sync/src/main/com/mongodb/client/internal/CommandMarker.java
JAVA-4739
* Extract method for duplicated logic from sync and reactive CommandMarker
* Fix the bug and and unit tests for the extracted method
=> Fix check for whether crypt shared lib is available 

bson-record-codec/src/main/org/bson/codecs/record/RecordCodec.java, bson-record-codec/src/test/unit/org/bson/codecs/record/RecordCodecTest.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordParameterized.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithNestedParameterized.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithNestedParameterizedRecord.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithParameterizedRecord.java
=> Support encoding/decoding of parameterized records

driver-core/src/main/com/mongodb/event/ConnectionCheckOutFailedEvent.java, driver-core/src/main/com/mongodb/event/ConnectionCheckOutStartedEvent.java, driver-core/src/main/com/mongodb/event/ConnectionCheckedInEvent.java, driver-core/src/main/com/mongodb/event/ConnectionCheckedOutEvent.java, driver-core/src/main/com/mongodb/event/ConnectionClosedEvent.java, driver-core/src/main/com/mongodb/event/ConnectionCreatedEvent.java, driver-core/src/main/com/mongodb/event/ConnectionReadyEvent.java, driver-core/src/main/com/mongodb/event/ConnectionRemovedEvent.java, driver-core/src/main/com/mongodb/event/ServerHeartbeatFailedEvent.java, driver-core/src/main/com/mongodb/event/ServerHeartbeatStartedEvent.java, driver-core/src/main/com/mongodb/event/ServerHeartbeatSucceededEvent.java
=> Add server address and cluster id to events' toString output

driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/MongoClients.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/package-info.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/ClientSideEncryptionAwsCredentialFromEnvironmentTest.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/ClientSideEncryptionDeadlockTest.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/ClientSideEncryptionOnDemandGcpCredentialsTest.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/ExplainTest.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/ReactiveInitialDnsSeedlistDiscoveryTest.java, driver-sync/src/test/functional/com/mongodb/client/AbstractClientEncryptionCustomEndpointTest.java, driver-sync/src/test/functional/com/mongodb/client/AbstractClientSideEncryptionOnDemandGcpCredentialsTest.java, driver-sync/src/test/functional/com/mongodb/client/ClientSideEncryptionOnDemandGcpCredentialsTest.java
=> Annotate com.mongodb.reactivestreams.client package as NonNullApi

driver-core/src/main/com/mongodb/internal/connection/AbstractMultiServerCluster.java, driver-core/src/main/com/mongodb/internal/operation/ServerVersionHelper.java, driver-core/src/test/resources/server-discovery-and-monitoring/rs/electionId_precedence_setVersion.json, driver-core/src/test/resources/server-discovery-and-monitoring/rs/null_election_id-pre-6.0.json, driver-core/src/test/resources/server-discovery-and-monitoring/rs/null_election_id.json, driver-core/src/test/resources/server-discovery-and-monitoring/rs/secondary_ignore_ok_0-pre-6.0.json, driver-core/src/test/resources/server-discovery-and-monitoring/rs/secondary_ignore_ok_0.json, driver-core/src/test/resources/server-discovery-and-monitoring/rs/set_version_can_rollback.json, driver-core/src/test/resources/server-discovery-and-monitoring/rs/setversion_equal_max_without_electionid.json, driver-core/src/test/resources/server-discovery-and-monitoring/rs/setversion_greaterthan_max_without_electionid.json, driver-core/src/test/resources/server-discovery-and-monitoring/rs/setversion_without_electionid-pre-6.0.json, driver-core/src/test/resources/server-discovery-and-monitoring/rs/setversion_without_electionid.json, driver-core/src/test/resources/server-discovery-and-monitoring/rs/use_setversion_without_electionid-pre-6.0.json, driver-core/src/test/resources/server-discovery-and-monitoring/rs/use_setversion_without_electionid.json
=> Prioritize electionId over setVersion on 6.0+ servers

driver-core/src/main/com/mongodb/MongoException.java, driver-core/src/main/com/mongodb/internal/operation/CommandOperationHelper.java, driver-core/src/test/functional/com/mongodb/internal/operation/MixedBulkWriteOperationSpecification.groovy, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/RetryableWritesProseTest.java, driver-sync/src/test/functional/com/mongodb/client/FailPoint.java, driver-sync/src/test/functional/com/mongodb/client/Fixture.java, driver-sync/src/test/functional/com/mongodb/client/RetryableWritesProseTest.java
TODO for @stIncMale: what's achieved by introducing `NoWritesPerformed` given that we already have `RetryableWriteError`? 
JAVA-4701
=> Propagate the original error for write errors labeled `NoWritesPerformed`

driver-sync/src/main/com/mongodb/client/internal/MongoClientImpl.java, driver-sync/src/test/unit/com/mongodb/client/MongoClientSpecification.groovy
=> Use wrapped CodecRegistry for MongoClient#watch

.evergreen/.evg.yml, .evergreen/run-mongodb-aws-ecs-test.sh, .evergreen/run-mongodb-aws-test.sh, build.gradle, driver-core/build.gradle, driver-core/src/main/com/mongodb/internal/authentication/AwsCredentialHelper.java, driver-core/src/main/com/mongodb/internal/authentication/AwsSdkV1CredentialSupplier.java, driver-core/src/main/com/mongodb/internal/authentication/AwsSdkV2CredentialSupplier.java, driver-core/src/main/com/mongodb/internal/authentication/BuiltInAwsCredentialSupplier.java, driver-core/src/test/functional/com/mongodb/internal/connection/AwsAuthenticationSpecification.groovy
To fetch AWS credentials from the environment:
* Use AWS SDK v2 if available on the classpath
* Otherwise, use AWS SDK v2 if available on the classpath
* Otherwise, use the existing driver implementation
JAVA-4718
=> Use AWS SDK v2/v1 if available for AWS credential fetching

driver-core/build.gradle
Currently the Java Driver can't be used in OSGi containers using a Java version lower than 17, which according to the compatibility matrix should not happen, as it should be compatible from Java 8+.
The problem is that there is a dependency of bson.codecs.record, which requires Java17+ according to its MANIFEST.MF:
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=17))"
This change will make the Import-Package attribute for bson.codecs.record optional, meaning when trying to use it in a OSGi container it won't fail because the dependency can't be satisfied in lower versions than 17.
After building with this change applied, that line in the MANIFEST.MF file will look like this:
org.bson.codecs.record;resolution:=optional;version="[4.7,5)"
We can see above this line that the …
=> JAVA-4789: Make bson.record.codec module optional for OSGi

driver-core/src/main/com/mongodb/internal/operation/AsyncOperations.java, driver-core/src/main/com/mongodb/internal/operation/Operations.java, driver-core/src/main/com/mongodb/internal/operation/SyncOperations.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/AggregatePublisherImpl.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/BatchCursorPublisher.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/FindPublisherImpl.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/MongoOperationPublisher.java, driver-reactive-streams/src/test/unit/com/mongodb/reactivestreams/client/internal/TestHelper.java
JAVA-4795
One more change to clean up use of internal `operation` package
The benefit is that, like with `SyncOperation`, `AsyncOperations` doesn't expose the concrete class of any operation, and just deals with the interfaces like `AsyncReadOperation` and `AsyncWriteOperation`.
This gets us closer to a state where we can make all concrete Operation classes package private.  The main thing stopping us from doing it now is that driver-legacy was never refactored to use SyncOperations and still constructs each operation directly.
=> Add AsyncOperations to match SyncOperations

driver-core/src/main/com/mongodb/internal/ExpirableValue.java, driver-core/src/main/com/mongodb/internal/authentication/AzureCredentialHelper.java, driver-core/src/test/unit/com/mongodb/internal/ExpirableValueTest.java
=> Cache Azure credential obtained from environment

driver-core/src/main/com/mongodb/client/model/expressions/ArrayExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/Expressions.java, driver-core/src/main/com/mongodb/client/model/expressions/MqlExpression.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/ArrayExpressionsFunctionalTest.java
JAVA-4781
(Javadocs are tentative, as per JAVA-4799)
=> Implement filter, map, reduce

driver-core/src/main/com/mongodb/MongoCommandException.java, driver-core/src/main/com/mongodb/MongoCursorNotFoundException.java, driver-core/src/main/com/mongodb/MongoQueryException.java, driver-core/src/main/com/mongodb/internal/connection/ProtocolHelper.java, driver-core/src/main/com/mongodb/internal/operation/FindOperation.java, driver-core/src/main/com/mongodb/internal/operation/QueryHelper.java, driver-core/src/test/functional/com/mongodb/internal/operation/QueryOperationHelper.groovy, driver-core/src/test/resources/unified-test-format/collection-management/modifyCollection-errorResponse.json, driver-core/src/test/resources/unified-test-format/crud/aggregate-merge-errorResponse.json, driver-core/src/test/resources/unified-test-format/crud/bulkWrite-errorResponse.json, driver-core/src/test/resources/unified-test-format/crud/deleteOne-errorResponse.json, driver-core/src/test/resources/unified-test-format/crud/findOneAndUpdate-errorResponse.json, driver-core/src/test/resources/unified-test-format/crud/insertOne-errorResponse.json, driver-core/src/test/resources/unified-test-format/crud/updateOne-errorResponse.json, driver-core/src/test/resources/unified-test-format/valid-pass/expectedError-errorResponse.json, driver-core/src/test/unit/com/mongodb/internal/operation/ChangeStreamBatchCursorHelperTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/ErrorMatcher.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudHelper.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java
The MongoQueryException class currently extends MongoServerException,
the reason being that prior to MongoDB 3.2 the find helper was implemented
using the OP_QUERY wire protocol message, which is not a command.  But now
that 3.6 is the minimum required server version, the find helper is always
implemented via the find command.  So MongoQueryException can now extend
MongoCommandException and include the full command response document.
JAVA-4676
=> Update MongoQueryException to extend MongoCommandException

driver-core/src/main/com/mongodb/client/model/expressions/Expression.java, driver-core/src/main/com/mongodb/client/model/expressions/Expressions.java, driver-core/src/main/com/mongodb/client/model/expressions/MqlExpression.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/ComparisonExpressionsFunctionalTest.java
=> Implement eq, ne, gt, gte, lt, lte

driver-core/src/main/com/mongodb/internal/operation/AsyncOperations.java, driver-core/src/main/com/mongodb/internal/operation/Operations.java, driver-core/src/main/com/mongodb/internal/operation/SyncOperations.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/ChangeStreamPublisherImpl.java, driver-sync/src/main/com/mongodb/client/internal/ChangeStreamIterableImpl.java
=> Encapsulate ChangeStreamOperation

driver-core/src/main/com/mongodb/internal/operation/AsyncOperations.java, driver-core/src/main/com/mongodb/internal/operation/Operations.java, driver-core/src/main/com/mongodb/internal/operation/SyncOperations.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/MongoDatabaseImpl.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/MongoOperationPublisher.java, driver-reactive-streams/src/test/unit/com/mongodb/reactivestreams/client/internal/MongoDatabaseImplTest.java, driver-sync/src/main/com/mongodb/client/internal/MongoDatabaseImpl.java
=> Encapsulate operations used by MongoDatabase

driver-core/src/main/com/mongodb/client/model/expressions/Expressions.java, driver-core/src/main/com/mongodb/client/model/expressions/MqlExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/StringExpression.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/AbstractExpressionsFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/ComparisonExpressionsFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/StringExpressionsFunctionalTest.java
JAVA-4801 
Implements string expressions from the top 50, and a few others.
See: https://www.mongodb.com/docs/manual/reference/operator/aggregation/#string-expression-operators
=> Implement string expressions

driver-core/src/main/com/mongodb/internal/operation/MixedBulkWriteOperation.java, driver-core/src/test/functional/com/mongodb/internal/operation/MixedBulkWriteOperationSpecification.groovy, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/MongoWriteConcernWithResponseExceptionTest.java, driver-sync/src/test/functional/com/mongodb/client/MongoWriteConcernWithResponseExceptionTest.java, driver-sync/src/test/functional/com/mongodb/client/RetryableWritesProseTest.java
=> Fix `MixedBulkWriteOperation` such that it does not leak `MongoWriteConcernWithResponseException` to users

driver-core/src/main/com/mongodb/client/model/expressions/Expressions.java, driver-core/src/main/com/mongodb/client/model/expressions/IntegerExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/MqlExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/NumberExpression.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/ArithmeticExpressionsFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/ArrayExpressionsFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/ComparisonExpressionsFunctionalTest.java
JAVA-4803
Implements arithmetic expressions from the top 50, and a few others.
=> Implement arithmetic expressions

driver-core/src/main/com/mongodb/client/model/expressions/ArrayExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/Expressions.java, driver-core/src/main/com/mongodb/client/model/expressions/MqlExpression.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/AbstractExpressionsFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/ArrayExpressionsFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/ComparisonExpressionsFunctionalTest.java
=> Implement array expressions

driver-core/src/main/com/mongodb/client/model/expressions/DateExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/Expressions.java, driver-core/src/main/com/mongodb/client/model/expressions/MqlExpression.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/DateExpressionsFunctionalTest.java
=> Implement date expressions

driver-sync/src/main/com/mongodb/client/gridfs/GridFSUploadStreamImpl.java, driver-sync/src/test/functional/com/mongodb/client/gridfs/GridFSBucketSmokeTestSpecification.groovy
=> Move check for previous value of "closed" outside of lambda

driver-core/src/main/com/mongodb/internal/connection/DefaultServerMonitor.java
Log as error any exception except MongoInterruptedException in server monitor before exiting monitor thread
JAVA-4822
=> Improve logging in server monitor

bson/src/main/org/bson/types/ObjectId.java, bson/src/test/unit/org/bson/types/ObjectIdTest.java
JIRA Ticket: https://jira.mongodb.org/browse/JAVA-4816
The current implementation of `ObjectId` `parseHexString` is somewhat slow, because it makes a total of 12 calls to `Integer.parseInt`, which is not the fastest to begin with. This imposes some overhead to all `ObjectId(string)` calls, which can really add up at scale, for example when deserializing a large amount of ObjectId data via Jackson.
Replacing this implementation with a hand-rolled version which converts each part of the hex string to a byte. This in my rough testing is about 5x faster than the current implementation of `parseHexString`.
Tests (on my M1 MacBook Pro):
```
public static void main(String[] args) {
long startTime = System.currentTimeMillis();
for (int i = 10000000; i < 100000000; i++) {
new …
```
=> [JAVA-4816] perf: improving performance of ObjectId parseHexString()

driver-core/src/main/com/mongodb/client/model/expressions/DocumentExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/Expression.java, driver-core/src/main/com/mongodb/client/model/expressions/MqlExpression.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/AbstractExpressionsFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/ArrayExpressionsFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/ComparisonExpressionsFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/DocumentExpressionsFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/TypeExpressionsFunctionalTest.java
=> Implement document expressions

driver-core/build.gradle
JAVA-4836
One thing that's weird here is that there is no version range in the jar file:
```
Import-Package: io.netty.bootstrap;resolution:=optional;version="[4.1,
5)",io.netty.buffer;resolution:=optional;version="[4.1,5)",io.netty.c
hannel;resolution:=optional;version="[4.1,5)",io.netty.channel.nio;re
solution:=optional;version="[4.1,5)",io.netty.channel.socket;resoluti
on:=optional;version="[4.1,5)",io.netty.channel.socket.nio;resolution
:=optional;version="[4.1,5)",io.netty.handler.ssl;resolution:=optiona
l;version="[4.1,5)",io.netty.handler.timeout;resolution:=optional;ver
sion="[4.1,5)",io.netty.util.concurrent;resolution:=optional;version=
"[4.1,5)",com.amazonaws.auth;resolution:=optional,software.amazon.aws
sdk.auth.credentials;resolution:=optional,org.xerial.snappy;resolutio …
```
=> Add OSGi package imports for AWS SDK v1 and v2

bson/src/main/org/bson/Document.java, bson/src/test/unit/org/bson/types/DocumentSpecification.groovy
=> Allow null elements in Document#getList

driver-core/src/main/com/mongodb/client/model/expressions/ArrayExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/DocumentExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/MqlExpression.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/ArrayExpressionsFunctionalTest.java
=> Re-implement reduce

driver-core/src/main/com/mongodb/client/model/expressions/ArrayExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/DocumentExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/EntryExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/Expression.java, driver-core/src/main/com/mongodb/client/model/expressions/Expressions.java, driver-core/src/main/com/mongodb/client/model/expressions/MapExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/MqlExpression.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/AbstractExpressionsFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/ComparisonExpressionsFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/DocumentExpressionsFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/MapExpressionsFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/TypeExpressionsFunctionalTest.java
JAVA-4817
objectToArray / arrayToObject (which correspond to Java's map.entrySet, and reduce-entries-to-map) require a Map type (as well as an Entry type)
=> Implement map expressions

driver-core/src/main/com/mongodb/client/model/expressions/Expressions.java, driver-sync/src/test/functional/com/mongodb/client/model/expressions/InContextExpressionsFunctionalTest.java
=> Test expressions in context

bson/src/main/org/bson/codecs/pojo/ConventionAnnotationImpl.java, bson/src/test/unit/org/bson/codecs/pojo/ConventionsTest.java, bson/src/test/unit/org/bson/codecs/pojo/entities/conventions/CreatorConstructorNoKnownIdModel.java
Help users when using a BsonId in a constructor and there is no known Id property in the model.
JAVA-4838
=> PojoCodec BsonId error message

driver-core/src/main/com/mongodb/client/model/expressions/ArrayExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/BooleanExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/Branches.java, driver-core/src/main/com/mongodb/client/model/expressions/DateExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/DocumentExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/EntryExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/Expression.java, driver-core/src/main/com/mongodb/client/model/expressions/Expressions.java, driver-core/src/main/com/mongodb/client/model/expressions/IntegerExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/MapExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/MqlExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/MqlUnchecked.java, driver-core/src/main/com/mongodb/client/model/expressions/NumberExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/StringExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/package-info.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/ControlExpressionsFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/TypeExpressionsFunctionalTest.java
Partial work for JAVA-4799
Covers boolean, date, number, integer, and expression, but not others, since PRs are still in progress.
There are naming changes, to parameters especially.
=> Javadoc for expressions

driver-core/src/main/com/mongodb/annotations/Sealed.java, driver-core/src/main/com/mongodb/client/model/expressions/ArrayExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/BooleanExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/Branches.java, driver-core/src/main/com/mongodb/client/model/expressions/BranchesIntermediary.java, driver-core/src/main/com/mongodb/client/model/expressions/BranchesTerminal.java, driver-core/src/main/com/mongodb/client/model/expressions/DateExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/DocumentExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/EntryExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/Expression.java, driver-core/src/main/com/mongodb/client/model/expressions/ExpressionCodecProvider.java, driver-core/src/main/com/mongodb/client/model/expressions/Expressions.java, driver-core/src/main/com/mongodb/client/model/expressions/IntegerExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/MapExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/MqlExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/MqlUnchecked.java, driver-core/src/main/com/mongodb/client/model/expressions/NumberExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/StringExpression.java, driver-core/src/main/com/mongodb/client/model/expressions/package-info.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/ArithmeticExpressionsFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/ArrayExpressionsFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/ControlExpressionsFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/DocumentExpressionsFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/MapExpressionsFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/NotNullApiTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/StringExpressionsFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/expressions/TypeExpressionsFunctionalTest.java, driver-sync/src/test/functional/com/mongodb/client/model/expressions/InContextExpressionsFunctionalTest.java
The remaining docs for [JAVA-4799](https://jira.mongodb.org/browse/JAVA-4799), continuing #1059.
Also adds `has` to document, and a fix to multiply (found while writing docs).
=> Javadoc for expressions, part 2

driver-core/src/main/com/mongodb/LoggerSettings.java, driver-core/src/main/com/mongodb/MongoClientSettings.java, driver-core/src/main/com/mongodb/internal/connection/DefaultClusterFactory.java, driver-core/src/main/com/mongodb/internal/connection/DefaultClusterableServerFactory.java, driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnection.java, driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnectionFactory.java, driver-core/src/main/com/mongodb/internal/connection/LoadBalancedClusterableServerFactory.java, driver-core/src/main/com/mongodb/internal/connection/LoggingCommandEventSender.java, driver-core/src/test/functional/com/mongodb/ClusterFixture.java, driver-core/src/test/functional/com/mongodb/internal/connection/CommandHelperSpecification.groovy, driver-core/src/test/functional/com/mongodb/internal/connection/PlainAuthenticatorTest.java, driver-core/src/test/functional/com/mongodb/internal/connection/ServerMonitorSpecification.groovy, driver-core/src/test/functional/com/mongodb/internal/connection/SingleServerClusterTest.java, driver-core/src/test/unit/com/mongodb/MongoClientSettingsSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/AbstractConnectionPoolTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/LoggingCommandEventSenderSpecification.groovy, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/MongoClients.java, driver-scala/src/main/scala/org/mongodb/scala/LoggerSettings.scala, driver-sync/src/main/com/mongodb/client/internal/MongoClientImpl.java, driver-sync/src/test/functional/com/mongodb/client/unified/Entities.java
=> Support configuration of max document length for command logging

driver-async/build.gradle, driver-embedded/build.gradle, mongo-java-driver/build.gradle, mongodb-driver/build.gradle
Update the name and description to indicate these are legacy and not the most recent release.
JAVA-4854
=> Update the legacy uber packages pom.xml

driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/BatchCursor.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/BatchCursorFlux.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/internal/BatchCursorFluxTest.java
The BatchCursor class can be closed by the BatchCursorFlux class but there is no signalling for the BatchCursor onNext publisher.
This leads to a next() called after the cursor was closed error and that breaks the reactive streams spec as the error ends up being dropped.
JAVA-4849
=> Ensure BatchCursorFlux does not drop an error

driver-sync/src/test/functional/com/mongodb/client/AbstractClientSideEncryptionAutoDataKeysTest.java
=> Fix the "database name is too long" error that happens when running against Serverless

.evergreen/.evg.yml, .evergreen/run-csfle-tests-with-mongocryptd.sh, .gitignore
See this [comment](https://jira.mongodb.org/browse/JAVA-4763?focusedCommentId=5187542&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-5187542) for my analysis of the pre-PR state.
JAVA-4763
=> Run CSFLE unified and legacy tests with `mongocryptd`

driver-core/src/main/com/mongodb/connection/ConnectionDescription.java, driver-core/src/main/com/mongodb/internal/connection/CommandMessage.java, driver-core/src/main/com/mongodb/internal/connection/DescriptionHelper.java, driver-core/src/main/com/mongodb/internal/connection/MessageSettings.java, driver-core/src/main/com/mongodb/internal/connection/ProtocolHelper.java, driver-core/src/main/com/mongodb/internal/operation/BaseFindAndModifyOperation.java, driver-core/src/main/com/mongodb/internal/operation/BulkWriteBatch.java, driver-core/src/main/com/mongodb/internal/operation/CommandOperationHelper.java, driver-core/src/main/com/mongodb/internal/operation/MixedBulkWriteOperation.java, driver-core/src/main/com/mongodb/internal/operation/OperationHelper.java, driver-core/src/test/functional/com/mongodb/internal/operation/FindAndDeleteOperationSpecification.groovy, driver-core/src/test/functional/com/mongodb/internal/operation/FindAndReplaceOperationSpecification.groovy, driver-core/src/test/functional/com/mongodb/internal/operation/FindAndUpdateOperationSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/CommandMessageSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/operation/BulkWriteBatchSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/operation/OperationHelperSpecification.groovy, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/ClientSessionHelper.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/MongoClientImpl.java, driver-reactive-streams/src/test/unit/com/mongodb/reactivestreams/client/internal/MongoClientImplTest.java, driver-sync/src/main/com/mongodb/client/internal/MongoClientDelegate.java, driver-sync/src/test/functional/com/mongodb/client/AbstractSessionsProseTest.java
Instead, check for session support during operation execution after the connection is checked out.
JAVA-4860
=> Do not perform server selection to determine sessions support

driver-sync/src/test/functional/com/mongodb/client/AbstractUnifiedTest.java
On 4.0 sharded clusters, the create collection command often fails (on the same test) with error code 11601 (Interrupted).  Work around it by retrying the command.
JAVA-4883
=> Work around create failure in unified tests with retry

driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/BatchCursorFlux.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/internal/BatchCursorFluxTest.java
Hi there 👋,
We use Mongodb reactive stream driver with akka-stream and had an issue when trying to upgrade our mongodb driver from 4.1.x to 4.9.0. The same code which was working with 4.1.x does not work anymore with 4.9.0. 
We tracked downed the issue and it's happening since the addition of reactor to this project. 
The issue is that when performing a find/distinct which returns `null` values, when the results are used in a `SerializedFluxSink` a NullPointerException is thrown and everything stops.
This is because `SerializedFluxSink.next` performs a call to `Object.requireNonNull()`.
To fix this NPE we filter out null values from the results.
I'm not sure this is the appropriate way to test/fix, suggestions are welcome.
In the meantime we workaround this on our side by filtering out …
=> fix: ensure no NPE is thrown with SerializedFluxSink

.evergreen/.evg.yml
JAVA-4926
- Reload expansions before deleting Azure resources
Verified with this patch: https://spruce.mongodb.com/version/64305c55d1fe07ff5999c510/
This is an improvement to the `testazurekms_task_group` added as part of DRIVERS-2411. https://github.com/mongodb/mongo-c-driver/pull/1234 explains this improvement.
=> Reload expansions before deleting Azure resources

driver-core/src/main/com/mongodb/internal/operation/CommandOperationHelper.java, driver-core/src/main/com/mongodb/internal/operation/FindOperation.java, driver-core/src/main/com/mongodb/internal/operation/ListCollectionsOperation.java, driver-core/src/main/com/mongodb/internal/operation/ListIndexesOperation.java, driver-core/src/main/com/mongodb/internal/operation/MixedBulkWriteOperation.java
The code that logs retries is now added by the `decorate*WithRetries` methods. Sometimes, this may result in us not logging even the short description of the command that is being retried, because currently we know the command (we create it) only after checking out a connection and checking if the server supports retries. So if the first attempt fails at a point before we create the command (e.g., because of the `MongoConnectionPoolClearedException`), we don't do `retryState.attach(AttachmentKeys.commandDescriptionSupplier(), command::getFirstKey, false)`, and the retrying attempt does not have the information about the command that it retries. This situation will be improved when [Log operation ID when retrying](https://jira.mongodb.org/browse/JAVA-4939) is done.
For each retry attempt …
=> Fix duplicate retry log messages

driver-core/src/main/com/mongodb/internal/operation/CommandOperationHelper.java, driver-core/src/main/com/mongodb/internal/operation/FindOperation.java, driver-core/src/main/com/mongodb/internal/operation/ListCollectionsOperation.java, driver-core/src/main/com/mongodb/internal/operation/ListIndexesOperation.java, driver-core/src/main/com/mongodb/internal/operation/MixedBulkWriteOperation.java
This PR adds logging of the `OperationContext` object to the `CommandOperationHelper.logRetryExecute()` method. The `OperationContext` object provides context information about the operation being executed, such as the operation id.
Logging  the `OperationContext` object  can be useful for troubleshooting, as it allows us to track the execution of specific operations.
[JAVA-4939](https://jira.mongodb.org/browse/JAVA-4939)
=> Add operation identifier to retry logs.

driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/unified/ConnectionPoolLoggingTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/ConnectionPoolLoggingTest.java
Ignore "Connection checkout fails due to error establishing connection" test in connection-logging.json
The implementation of the functionality related to clearing the connection pool before closing the connection will be carried out once the specification is finalized and ready.
[JAVA-4976](https://jira.mongodb.org/browse/JAVA-4976)
=> Ignore connection-logging tests.

.evergreen/.evg.yml
=> Test in CI against MongoDB 7.0

driver-core/src/main/com/mongodb/MongoClientSettings.java
This should have probably been removed in this [commit](https://github.com/mongodb/mongo-java-driver/commit/dfcf57f3dfea23609bfe911b788cc347173d4d76).
Maybe the modified sentence in this PR should just be completely removed so there is not duplication of documentation and actual properties in the class. If you would like that let me know and I can remove the entire sentence.
=> Cleanup documentation referring to removed property

driver-core/src/main/com/mongodb/internal/connection/ZstdCompressor.java
=> JAVA-4868 3.12.x backport

driver-core/src/main/com/mongodb/internal/connection/ServerAddressWithResolver.java, driver-core/src/main/com/mongodb/spi/dns/InetAddressResolver.java, driver-sync/src/test/functional/com/mongodb/client/AbstractDnsConfigurationTest.java
=> Remove IP literal check for InetAddressResolver

bson-kotlin/src/main/kotlin/org/bson/codecs/kotlin/DataClassCodec.kt, bson-kotlin/src/main/kotlin/org/bson/codecs/kotlin/DataClassCodecProvider.kt, bson-kotlin/src/test/kotlin/org/bson/codecs/kotlin/DataClassCodecProviderTest.kt, bson-record-codec/src/main/org/bson/codecs/record/RecordCodec.java, bson-record-codec/src/main/org/bson/codecs/record/RecordCodecProvider.java, bson-record-codec/src/test/unit/org/bson/codecs/record/RecordCodecTest.java, bson/src/main/org/bson/codecs/CollectionCodec.java, bson/src/main/org/bson/codecs/CollectionCodecProvider.java, bson/src/main/org/bson/codecs/MapCodecProvider.java, bson/src/main/org/bson/codecs/MapCodecV2.java, bson/src/main/org/bson/codecs/Parameterizable.java, bson/src/main/org/bson/codecs/configuration/CodecProvider.java, bson/src/main/org/bson/codecs/configuration/OverridableUuidRepresentationCodecProvider.java, bson/src/main/org/bson/internal/ChildCodecRegistry.java, bson/src/main/org/bson/internal/ProvidersCodecRegistry.java, bson/src/test/unit/org/bson/codecs/CollectionCodecProviderTest.java, bson/src/test/unit/org/bson/codecs/CollectionCodecSpecification.groovy, bson/src/test/unit/org/bson/codecs/MapCodecProviderTest.java, bson/src/test/unit/org/bson/codecs/MapCodecV2Specification.groovy, bson/src/test/unit/org/bson/codecs/configuration/CodeRegistriesSpecification.groovy, driver-core/src/main/com/mongodb/Jep395RecordCodecProvider.java, driver-core/src/main/com/mongodb/KotlinCodecProvider.java
Turns out, we don't even need to introduce `ParameterizedCodecProvider` to replace `Parameterizable`. All we need is a new default method on `CodecProvider`. And the cost of still supporting `Parameterizable` is really small: a single `if` block in `ProvidersCodecRegistry.getFromCodecProvider`.
I also refactored `RecordCodec`, `CollectionCodec`, `MapCodecV2`, `org.bson.codecs.kotlin.DataClassCodec` such that they no longer implement `Parameterizable`.
JAVA-4954 is about trying to improve `PojoCodecImpl` to be more like `RecordCodec`. Given that we discovered a better alternative to `Parameterizable`, which can be implemented without breaking public API, it seems worth making the improvement before trying to refactor `PojoCodecImpl`. Otherwise, we will likely have to refactor …
=> Deprecate `Parameterizable`, introduce default `CodecProvider.get(Class<T>, List<Type>, CodecRegistry)` instead

bson-scala/src/main/scala/org/mongodb/scala/bson/codecs/macrocodecs/CaseClassCodec.scala
https://jira.mongodb.org/browse/JAVA-4966
If the sealed trait and the Macro are not defined is the same module, we have the following error `No known subclasses of the sealed trait`
Add a `val _` to make sure that `isCaseClass` returns the correct value.  This "hack" is described in https://github.com/scala/bug/issues/7755
It's complicated to test that, because it requires having multi modules. But this change solved the issue in my project.
=> JAVA-4966 : Fix Macro for sealed trait

bson/src/main/org/bson/codecs/pojo/LazyPropertyModelCodec.java, bson/src/main/org/bson/codecs/pojo/PojoCodecImpl.java, bson/src/main/org/bson/codecs/pojo/PojoCodecProvider.java, bson/src/test/unit/org/bson/codecs/pojo/PojoTestCase.java
This PR moves some of the conditional logic from `PojoCodecImpl` under the rug, thus allegedly simplifying `PojoCodecImpl`, but not the POJO codec implementation overall.
I still have no idea about the following:
- What "specialization" means and why it exists?
- Why there is two "unusable" types codecs; previously it was `LazyPropertyModelCodec` and some instances of `PojoCodecImpl`, now its `LazyPropertyModelCodec` and all instances of `NeedsSpecializationCodec`?
- Why is it so happens that `NeedsSpecializationCodec` is always (I judge based on the existing tests) replaced by `LazyPropertyModelCodec` with a usable codec instance?
JAVA-4954
=> Remove specialization-related conditional logic from `PojoCodecImpl` by introducing `LazyPropertyModelCodec.NeedsSpecializationCodec`

driver-sync/src/test/functional/com/mongodb/client/AbstractClientEncryptionRewrapManyDataKeyProseTest.java
This PR adds one missing prose test from the spec.
[JAVA-4766](https://jira.mongodb.org/browse/JAVA-4766)
=> Add second case for the RewrapManyDataKeyOpts prose test.

driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/crypt/Crypt.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/crypt/Crypts.java, driver-sync/src/main/com/mongodb/client/internal/Crypt.java, driver-sync/src/main/com/mongodb/client/internal/Crypts.java
When AutoEncryptionSettings#keyVaultMongoClientSettings is non-null and AutoEncryptionSettings#isBypassAutoEncryption is false, the second internal MongoClient is now closed when the containing MongoClient is closed.
The bug is fixed in both the synchronous and reactive streams drivers.
JAVA-4993
=> Fix MongoClient leak in auto-encryption

bson/src/main/org/bson/BsonArray.java, driver-core/src/main/com/mongodb/internal/connection/ByteBufBsonArray.java, driver-core/src/main/com/mongodb/internal/connection/ByteBufBsonDocument.java, driver-core/src/main/com/mongodb/internal/connection/ByteBufBsonHelper.java, driver-core/src/test/unit/com/mongodb/internal/connection/ByteBufBsonArrayTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/ByteBufBsonDocumentSpecification.groovy
This one got a bit complicated.  The root cause of the bug is that `ByteBufBsonDocument#entrySet` hydrates its byte buffer into the base class's hash map instead of implementing the entry set via iterating over the raw BSON.  To avoid this hydration completely, including for nested documents and arrays, requires quite a few code changes, including the introduction of a new class, `ByteBufBsonArray`, that does the same job for nested arrays.
JAVA-4917
=> ByteBufBsonDocument remains a ByteBuf

driver-core/src/main/com/mongodb/client/model/mql/MqlValues.java, driver-core/src/test/functional/com/mongodb/client/model/mql/ArrayMqlValuesFunctionalTest.java, driver-core/src/test/functional/com/mongodb/client/model/mql/StringMqlValuesFunctionalTest.java
=> Wrap string in literal if it contains $

bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/KotlinSerializerCodec.kt, bson-kotlinx/src/test/kotlin/org/bson/codecs/kotlinx/KotlinSerializerCodecProviderTest.kt, driver-core/src/test/functional/com/mongodb/client/model/AggregatesTest.java
=> Kotlinx codec provider limit to data, value or sealed classes.

driver-core/build.gradle, driver-kotlin-coroutine/build.gradle.kts, driver-kotlin-sync/build.gradle.kts
Reduce the dependency tree for driver-core by making the kotlin dependencies optional.
Kotlin-coroutine and Kotlin-sync now take a hard dependency on bson-kotlin. So they will work out the box. Users will now have to opt into bson-kotlinx support.
JAVA-5036
=> Build: Make bson-kotlin and bson-kotlinx optional

bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/KotlinSerializerCodec.kt, bson-kotlinx/src/test/kotlin/org/bson/codecs/kotlinx/KotlinSerializerCodecProviderTest.kt
Only support classes annotated as serializable.
JAVA-5035
=> Kotlin: Improve KotlinSerializerCodec

bson/src/main/org/bson/io/OutputBuffer.java, driver-core/src/main/com/mongodb/connection/Stream.java, driver-core/src/main/com/mongodb/connection/netty/NettyStream.java, driver-core/src/main/com/mongodb/internal/ResourceUtil.java, driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnection.java
=> `InternalStreamConnection` must release buffers obtained via `ByteBufferBsonOutput.getByteBuffers`

driver-kotlin-sync/src/test/kotlin/com/mongodb/kotlin/client/MongoCursorTest.kt, driver-sync/src/main/com/mongodb/client/MongoCursor.java, driver-sync/src/test/unit/com/mongodb/client/internal/MongoBatchCursorAdapterSpecification.groovy
The override of the default implementation ensures that the cursor is closed even if an exception is thrown.
JAVA-5085
=> Override Iterator#forEachRemaining in MongoCursor

driver-core/src/main/com/mongodb/ConnectionString.java, driver-core/src/test/unit/com/mongodb/ConnectionStringSpecification.groovy
=> Allow tls=false override with mongodb+srv protocol

driver-core/src/main/com/mongodb/client/model/changestream/ChangeStreamDocument.java, driver-core/src/main/com/mongodb/client/model/changestream/ChangeStreamDocumentCodec.java, driver-core/src/main/com/mongodb/client/model/changestream/SplitEvent.java, driver-core/src/test/functional/com/mongodb/client/CrudTestHelper.java, driver-core/src/test/functional/com/mongodb/internal/connection/ClientMetadataHelperProseTest.java, driver-core/src/test/unit/com/mongodb/client/model/changestream/ChangeStreamDocumentCodecSpecification.groovy, driver-core/src/test/unit/com/mongodb/client/model/changestream/ChangeStreamDocumentSpecification.groovy, driver-sync/src/test/functional/com/mongodb/client/ChangeStreamProseTest.java
=> Support $changeStreamSplitLargeEvent

.evergreen/.evg.yml, .evergreen/run-kotlin-tests.sh, .evergreen/run-scala-tests.sh, .evergreen/static-checks.sh, bson-kotlin/build.gradle.kts, bson-kotlinx/build.gradle.kts, bson-scala/build.gradle, driver-kotlin-coroutine/build.gradle.kts, driver-kotlin-sync/build.gradle.kts, driver-scala/build.gradle
Ensures that Kotlin and Scala checks are also run.
* Renamed compile.sh to static-checks.sh so its discoverable
* Added compileIntegrationTest to Kotlin/Scala checks
* Updated the evergreen static-checks.sh to run the Kotlin & Scala checks
JAVA-5095
=> Evergreen: Updated static checks

driver-core/src/test/functional/com/mongodb/internal/operation/CreateCollectionOperationSpecification.groovy, driver-core/src/test/resources/client-side-encryption/legacy/bypassedCommand.json, driver-legacy/src/main/com/mongodb/DBCollection.java, driver-legacy/src/test/functional/com/mongodb/DBCollectionSpecification.groovy, driver-legacy/src/test/functional/com/mongodb/DBTest.java, driver-legacy/src/test/unit/com/mongodb/DBSpecification.groovy, driver-sync/src/examples/documentation/DocumentationSamples.java
=> Deprecate `currentOp`/`collStats` commands

driver-scala/src/integration/scala/org/mongodb/scala/syncadapter/SyncMongoCollection.scala
=> Add Scala test methods to SyncMongoCollection.

driver-scala/src/integration/scala/org/mongodb/scala/syncadapter/SyncMongoCollection.scala
This reverts commit ed2dda53cabc623ed57934e45b75bafde268dc49 in order to resolve the duplication issue. The changes had been already added in this [commit](https://github.com/mongodb/mongo-java-driver/commit/e7de6b039127365862bef3c4ce986d69941cb826).
=> Revert "Add Scala test methods to SyncMongoCollection"

driver-core/src/main/com/mongodb/internal/session/BaseClientSessionImpl.java
Replace the volatile boolean with an AtomicBoolean to ensure that the side effects of the close method only execute once.
JAVA-5107
=> Make the ClientSession close method thread-safe

driver-core/src/main/com/mongodb/ConnectionString.java, driver-core/src/main/com/mongodb/MongoClientSettings.java, driver-core/src/test/unit/com/mongodb/MongoClientSettingsSpecification.groovy, driver-legacy/src/main/com/mongodb/MongoClientOptions.java, driver-legacy/src/main/com/mongodb/MongoClientURI.java, driver-legacy/src/test/unit/com/mongodb/MongoClientOptionsSpecification.groovy, driver-legacy/src/test/unit/com/mongodb/MongoClientURISpecification.groovy
=> CSOT: Added timeout to settings & connection string

driver-core/src/main/com/mongodb/ConnectionString.java, driver-core/src/main/com/mongodb/connection/ConnectionPoolSettings.java, driver-core/src/main/com/mongodb/event/ConnectionCheckOutFailedEvent.java, driver-core/src/main/com/mongodb/event/ConnectionCheckedInEvent.java, driver-core/src/main/com/mongodb/event/ConnectionCheckedOutEvent.java, driver-core/src/main/com/mongodb/event/ConnectionClosedEvent.java, driver-core/src/main/com/mongodb/event/ConnectionCreatedEvent.java, driver-core/src/main/com/mongodb/event/ConnectionReadyEvent.java, driver-core/src/main/com/mongodb/internal/connection/ConnectionPool.java, driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java, driver-core/src/test/resources/unified-test-format/connection-monitoring-and-pooling/logging/connection-logging.json, driver-core/src/test/resources/unified-test-format/connection-monitoring-and-pooling/logging/connection-pool-options.json, driver-core/src/test/unit/com/mongodb/internal/connection/DefaultConnectionPoolSpecification.groovy
This PR implements the spec change https://github.com/mongodb/specifications/pull/1448.
JAVA-5076
=> Add durations to connection pool events

bson/src/main/org/bson/codecs/pojo/LazyPropertyModelCodec.java, driver-core/src/main/com/mongodb/connection/netty/NettyStream.java, driver-core/src/main/com/mongodb/internal/authentication/AzureCredentialHelper.java, driver-core/src/main/com/mongodb/internal/connection/AsynchronousChannelStream.java, driver-core/src/main/com/mongodb/internal/connection/DefaultServerMonitor.java, driver-core/src/main/com/mongodb/internal/connection/ExponentiallyWeightedMovingAverage.java, driver-core/src/main/com/mongodb/internal/operation/AsyncQueryBatchCursor.java, driver-legacy/src/main/com/mongodb/DBCollection.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/gridfs/ResizingByteBufferFlux.java
The philosophy behind this PR:
1. the changes must not break what was guaranteed to work;
2. but if existing code is not correct (some of the touched code looks dubious to me), it's not the goal to deeply analyze it and fix as part of this PR, though if something is obvious - it's fine to fix it.
I recommend enabling the "Hide whitespace" option when viewing changes.
I would appreciate reviewers being especially vigilant reviewing changes in this PR: if you can't convince yourself that the change does not break what was guaranteed to work, please bring your concern up, with as details if possible, as we should then think about it more / discuss it. For example, if you can point out a specific guarantee the new code does not have compared to the original code, and how that specific …
=> Get rid of all `synchronized` blocks and methods in production code

.evergreen/.evg.yml, .evergreen/run-atlas-search-index-management-tests.sh, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/AtlasSearchIndexManagementProseTest.java, driver-sync/src/test/functional/com/mongodb/client/AbstractAtlasSearchIndexManagementProseTest.java, driver-sync/src/test/functional/com/mongodb/client/AtlasSearchIndexManagementProseTest.java
=> Add end-to-end Search Index Management Helper Methods Tests

driver-core/src/main/com/mongodb/ServerAddress.java, driver-core/src/main/com/mongodb/UnixServerAddress.java, driver-core/src/main/com/mongodb/connection/TlsChannelStreamFactoryFactory.java, driver-core/src/main/com/mongodb/connection/netty/NettyStream.java, driver-core/src/main/com/mongodb/internal/connection/AsynchronousSocketChannelStream.java, driver-core/src/main/com/mongodb/internal/connection/ServerAddressWithResolver.java, driver-core/src/main/com/mongodb/internal/connection/SocketStream.java, driver-core/src/main/com/mongodb/internal/connection/UnixSocketChannelStream.java
* ServerAddress#getSocketAddress
* ServerAddress#getSocketAddresses
* UnixServerAddress#getUnixSocketAddress
JAVA-4940
When we actually remove these methods and replace with some private helper, and also remove `StreamFactory` from API, we'll be able to remove the `ServerAddressWithResolver` class and just pass the `InetAddressResolver` wherever it needs to be available.
=> Deprecate SocketAddress-related methods

driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java, driver-core/src/main/com/mongodb/internal/connection/DefaultServer.java, driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnection.java, driver-core/src/main/com/mongodb/internal/connection/SocketStream.java, driver-core/src/test/unit/com/mongodb/internal/connection/InternalStreamConnectionSpecification.groovy
=> Handle `Socket` IO interruptibility

.evergreen/.evg.yml
This PR introduces enhancements to performance monitoring:
-  Adds dedicated distro rhel90-dbx-perf-large for performance testing.
- Uses patch-pinned v6 server (6.0.6) as v6.0-perf alias.
JAVA-5065
=> Improve performance monitoring

driver-core/src/test/functional/com/mongodb/internal/operation/AggregateOperationSpecification.groovy, driver-sync/src/test/functional/com/mongodb/client/AbstractExplainTest.java
The response document for the explain command has changed in 7.2 sharded clusters. It introduces a top-level "shards" document that contains the explain output for each shard. This patch supports this new field in tests of explain API in the driver.
JAVA-5137
=> Handle new explain output in tests

driver-core/src/main/com/mongodb/MongoInterruptedException.java, driver-core/src/main/com/mongodb/connection/netty/NettyStream.java, driver-core/src/main/com/mongodb/internal/Locks.java, driver-core/src/main/com/mongodb/internal/connection/AsynchronousChannelStream.java, driver-core/src/main/com/mongodb/internal/connection/BaseCluster.java, driver-core/src/main/com/mongodb/internal/connection/ConcurrentPool.java, driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java, driver-core/src/main/com/mongodb/internal/connection/DefaultDnsSrvRecordMonitor.java, driver-core/src/main/com/mongodb/internal/connection/DefaultServerMonitor.java, driver-core/src/main/com/mongodb/internal/connection/FutureAsyncCompletionHandler.java, driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnection.java, driver-core/src/main/com/mongodb/internal/connection/LoadBalancedCluster.java, driver-core/src/main/com/mongodb/internal/connection/tlschannel/async/AsynchronousTlsChannelGroup.java, driver-core/src/main/com/mongodb/internal/thread/InterruptionUtil.java, driver-core/src/test/functional/com/mongodb/ClusterFixture.java, driver-core/src/test/functional/com/mongodb/internal/connection/ServerHelper.java, driver-core/src/test/functional/com/mongodb/internal/connection/TestCommandListener.java, driver-core/src/test/unit/com/mongodb/internal/connection/AbstractConnectionPoolTest.java, driver-legacy/src/main/com/mongodb/client/jndi/MongoClientFactory.java, driver-reactive-streams/src/examples/reactivestreams/helpers/SubscriberHelpers.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/Fixture.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/syncadapter/SyncClientSession.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/syncadapter/SyncMongoCursor.java, driver-sync/src/test/functional/com/mongodb/client/ServerDiscoveryAndMonitoringProseTests.java
=> Fix how `InterruptedException`s are handled

driver-core/src/test/functional/com/mongodb/client/model/AggregatesTest.java, driver-core/src/test/functional/com/mongodb/client/model/OperationTest.java
This works around small variations in native math libraries used by the server.
JAVA-5097
=> Scale double values to 4 decimal digits in geoNear test

driver-core/src/main/com/mongodb/internal/connection/SocketStream.java, driver-core/src/main/com/mongodb/internal/connection/SocksSocket.java
Notably, `Socket.close` may also block if one enables `SO_LINGER` by calling `Socket.setSoLinger`, yet there is not a word on interruptibility of `Socket.close` in the docs. Fortunately, we don't enable `SO_LINGER`, so we don't have to care about the behavior of `Socket.close`.
JAVA-5138
=> Handle interrupts: `Socket.connect` is interruptible in a virtual thread

driver-core/src/main/com/mongodb/connection/netty/NettyStream.java, driver-core/src/main/com/mongodb/internal/Locks.java, driver-core/src/main/com/mongodb/internal/authentication/AzureCredentialHelper.java, driver-core/src/main/com/mongodb/internal/connection/ConcurrentPool.java, driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java, driver-core/src/main/com/mongodb/internal/connection/DefaultServerMonitor.java, driver-core/src/main/com/mongodb/internal/connection/LoadBalancedCluster.java, driver-core/src/main/com/mongodb/internal/operation/AsyncQueryBatchCursor.java, driver-core/src/main/com/mongodb/internal/operation/QueryBatchCursor.java, driver-legacy/src/main/com/mongodb/DBCollection.java
=> Replace uninterruptible `Lock.lock` with `Lock.lockInterruptibly`

driver-sync/src/main/com/mongodb/client/internal/Crypt.java, driver-sync/src/main/com/mongodb/client/internal/KeyManagementService.java
This PR is very similar to https://github.com/mongodb/mongo-java-driver/pull/1203, which is why I assigned the same reviewers.
JAVA-5139
=> Handle interrupts: synchronous `KeyManagementService` uses Socket IO (open, read, write), which is interruptible in a virtual thread

bson-kotlin/build.gradle.kts, bson-kotlinx/build.gradle.kts, driver-kotlin-coroutine/build.gradle.kts, driver-kotlin-sync/build.gradle.kts
Configures `sourcesJar` task for Kotlin projects to actually include Kotlin sources, otherwise jar files are empty.
See [mongodb-driver-kotlin-sync-4.10.2-sources.jar](https://repo1.maven.org/maven2/org/mongodb/mongodb-driver-kotlin-sync/4.10.2/mongodb-driver-kotlin-sync-4.10.2-sources.jar) for example.
Also see this for context: https://youtrack.jetbrains.com/issue/KT-54207
=> fix: include Kotlin sources into the sources jar

bson-kotlin/src/main/kotlin/org/bson/codecs/kotlin/DataClassCodec.kt, bson-kotlin/src/test/kotlin/org/bson/codecs/kotlin/DataClassCodecTest.kt
=> Kotlin. Support stored nulls for nullable fields

driver-core/src/main/com/mongodb/event/ClusterListener.java, driver-core/src/main/com/mongodb/event/ServerListener.java, driver-core/src/main/com/mongodb/event/ServerMonitorListener.java
=> Fix the `ClusterListener`, `ServerListener`, `ServerMonitorListener` API docs relevant to thread-safety

driver-core/src/main/com/mongodb/event/CommandEvent.java, driver-core/src/main/com/mongodb/event/CommandFailedEvent.java, driver-core/src/main/com/mongodb/event/CommandStartedEvent.java, driver-core/src/main/com/mongodb/event/CommandSucceededEvent.java, driver-core/src/main/com/mongodb/internal/connection/LoggingCommandEventSender.java, driver-core/src/main/com/mongodb/internal/connection/ProtocolHelper.java, driver-core/src/test/functional/com/mongodb/internal/connection/TestCommandListener.java, driver-core/src/test/resources/unified-test-format/command-monitoring/command.json, driver-core/src/test/resources/unified-test-format/command-monitoring/find.json, driver-core/src/test/unit/com/mongodb/internal/connection/LoggingCommandEventSenderSpecification.groovy, driver-sync/src/test/functional/com/mongodb/client/unified/EventMatcher.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java
=> Add databaseName to command succeeded/failed events/logs

driver-core/src/main/com/mongodb/client/model/Aggregates.java, driver-core/src/test/functional/com/mongodb/client/model/AggregatesTest.java
=> $lookup "from" must be null when using $documents pipeline

driver-core/src/main/com/mongodb/client/model/FindOneAndDeleteOptions.java, driver-core/src/main/com/mongodb/client/model/FindOneAndReplaceOptions.java, driver-core/src/main/com/mongodb/client/model/FindOneAndUpdateOptions.java, driver-core/src/main/com/mongodb/client/model/Projections.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/FindPublisher.java, driver-scala/src/main/scala/org/mongodb/scala/FindObservable.scala, driver-scala/src/main/scala/org/mongodb/scala/model/Projections.scala, driver-sync/src/main/com/mongodb/client/FindIterable.java
=> Update Javadoc for Projections.

config/spotbugs/exclude.xml, driver-core/src/main/com/mongodb/internal/TimeoutContext.java, driver-core/src/main/com/mongodb/internal/connection/AbstractMultiServerCluster.java, driver-core/src/main/com/mongodb/internal/connection/BaseCluster.java, driver-core/src/main/com/mongodb/internal/connection/Cluster.java, driver-core/src/main/com/mongodb/internal/connection/LoadBalancedCluster.java, driver-core/src/main/com/mongodb/internal/connection/SingleServerCluster.java, driver-core/src/test/functional/com/mongodb/internal/connection/SingleServerClusterTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/AbstractServerDiscoveryAndMonitoringTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/BaseClusterSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/DefaultServerSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/DnsMultiServerClusterSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/LoadBalancedClusterTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/MultiServerClusterSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/ServerDiscoveryAndMonitoringTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/SingleServerClusterSpecification.groovy
JAVA-5184
Refactoring in advance of [JAVA-4065](https://jira.mongodb.org/browse/JAVA-4065).
In [JAVA-5175](https://jira.mongodb.org/browse/JAVA-5175), we used a timeout, but obtained from the existing settings. Here, we obtain that timeout from the OperationContext added in [JAVA-5170](https://jira.mongodb.org/browse/JAVA-5170).
Also fixes flaky tests.
=> Refactor to obtain timeout from OperationContext for server selection

bson-record-codec/src/main/org/bson/codecs/record/RecordCodec.java, bson-record-codec/src/test/unit/org/bson/codecs/record/RecordCodecTest.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithNullableAnnotation.java, bson-record-codec/src/test/unit/org/bson/codecs/record/samples/TestRecordWithNullableField.java
Same as the issue raised in https://jira.mongodb.org/browse/JAVA-5134, this change implements a mechanism to gracefully handle stored nulls for fields that are annotated with JSR305 `@Nullable` annotations.
- Introduce a boolean field `isNullable` to `RecordCodec.ComponentModel`, which is set to true when given field is not primitive.
- When decoding stored null for a field that is considered nullable in above step, read null in stead of throwing an `BsonInvalidOperationException`.
- For any other scenarios, previous codec behaviour is preserved.
https://jira.mongodb.org/browse/JAVA-5203
=> [JAVA-5203] Support stored nulls for non-primitive fields in Java records

bson-kotlin/build.gradle.kts, bson-kotlinx/build.gradle.kts, bson-scala/build.gradle, bson/build.gradle, driver-kotlin-coroutine/build.gradle.kts, driver-kotlin-sync/build.gradle.kts, driver-scala/build.gradle, gradle/publish.gradle
<h2> Description :</h2>
Some modules rely on the `publish.gradle` file to generate the Automatic Module Name in the manifest, based on the `groupName` and `archivesBaseName` of the project. However, the `archivesName` contains hyphens that are not valid according to the [Java Language Specification](https://docs.oracle.com/javase/specs/jls/se13/html/jls-7.html#jls-7.7).
As a result, all Automatic Module Names are now explicitly specified in each build.gradle file:
`org.mongodb.mongodb-driver-kotlin-coroutine` is renamed to `org.mongodb.driver.kotlin.coroutine`
`org.mongodb.mongodb-driver-kotlin-sync` is renamed to `org.mongodb.driver.kotlin.sync`
`org.mongodb.bson-kotlin` is renamed to `org.mongodb.bson.kotlin`
`org.mongodb.bson-kotlinx` is renamed to `org.mongodb.bson.kotlinx` …
=> Add explicit automatic module name configuration.

driver-core/src/main/com/mongodb/internal/connection/DefaultClusterFactory.java, driver-core/src/test/unit/com/mongodb/internal/connection/DefaultClusterFactoryTest.java
=> Update logger name to align with naming conventions.

build.gradle, config/spotbugs/exclude.xml, driver-core/src/main/com/mongodb/internal/connection/ClientMetadataHelper.java, driver-core/src/test/functional/com/mongodb/internal/connection/ClientMetadataHelperProseTest.java
Include container and Kubernetes awareness, as specified in the [MongoDB Handshake Specification](https://github.com/abr-egn/specifications/blob/c4831b426c7eab8749723d7f3cd6bb5c237bcbbe/source/mongodb-handshake/handshake.rst#container)
JAVA-5072
=> Enable container and Kubernetes awareness for improved telemetry.

driver-core/src/main/com/mongodb/internal/TimeoutContext.java, driver-core/src/main/com/mongodb/internal/connection/BaseCluster.java, driver-core/src/main/com/mongodb/internal/time/TimePoint.java, driver-core/src/main/com/mongodb/internal/time/Timeout.java, driver-reactive-streams/src/test/functional/com/mongodb/internal/ClientSideOperationsTimeoutAsyncProseTests.java, driver-sync/src/test/functional/com/mongodb/internal/ClientSideOperationsTimeoutProseTests.java
=> Apply timeout to server selection

driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/DatabaseTestCase.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/RetryableReadsProseTest.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/RetryableWritesProseTest.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/TransactionFailureTest.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/WriteConcernProseTest.java, driver-sync/src/examples/documentation/DocumentationSamples.java, driver-sync/src/examples/primer/AggregatePrimer.java, driver-sync/src/examples/primer/IndexesPrimer.java, driver-sync/src/examples/primer/InsertPrimer.java, driver-sync/src/examples/primer/QueryPrimer.java, driver-sync/src/examples/primer/RemovePrimer.java, driver-sync/src/examples/primer/UpdatePrimer.java, driver-sync/src/test/functional/com/mongodb/client/ChangeStreamProseTest.java, driver-sync/src/test/functional/com/mongodb/client/CrudProseTest.java, driver-sync/src/test/functional/com/mongodb/client/DatabaseTestCase.java, driver-sync/src/test/functional/com/mongodb/client/MongoCollectionTest.java, driver-sync/src/test/functional/com/mongodb/client/RetryableReadsProseTest.java, driver-sync/src/test/functional/com/mongodb/client/RetryableWritesProseTest.java, driver-sync/src/test/functional/com/mongodb/client/TransactionFailureTest.java, driver-sync/src/test/functional/com/mongodb/client/WithTransactionProseTest.java, driver-sync/src/test/functional/com/mongodb/client/model/mql/InContextMqlValuesFunctionalTest.java
=> Update DatabaseTestCase to Junit 5

driver-core/src/main/com/mongodb/internal/connection/BaseCluster.java, driver-core/src/main/com/mongodb/internal/logging/LogMessage.java, driver-core/src/main/com/mongodb/internal/logging/StructuredLogger.java, driver-core/src/main/com/mongodb/internal/session/ServerSessionPool.java, driver-core/src/test/resources/unified-test-format/server-selection/logging/load-balanced.json, driver-core/src/test/resources/unified-test-format/server-selection/logging/operation-id.json, driver-core/src/test/resources/unified-test-format/server-selection/logging/replica-set.json, driver-core/src/test/resources/unified-test-format/server-selection/logging/sharded.json, driver-core/src/test/resources/unified-test-format/server-selection/logging/standalone.json, driver-core/src/test/unit/com/mongodb/internal/connection/BaseClusterSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/TestClusterListener.java, driver-core/src/test/unit/com/mongodb/internal/connection/TestServerListener.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/unified/ServerSelectionLoggingTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/ContextElement.java, driver-sync/src/test/functional/com/mongodb/client/unified/Entities.java, driver-sync/src/test/functional/com/mongodb/client/unified/EventMatcher.java, driver-sync/src/test/functional/com/mongodb/client/unified/LogMatcher.java, driver-sync/src/test/functional/com/mongodb/client/unified/ServerSelectionLoggingTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudHelper.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java
The implemented spec changes: https://github.com/mongodb/specifications/commit/c773534925f83ecc5728971442baa63d69ecf0ce.
JAVA-4754
=> Add server selection log messages

driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnection.java, driver-core/src/main/com/mongodb/internal/connection/ReplyHeader.java, driver-core/src/main/com/mongodb/internal/connection/ReplyMessage.java, driver-core/src/main/com/mongodb/internal/connection/ResponseBuffers.java, driver-core/src/test/functional/com/mongodb/internal/connection/ReplyHeaderSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/CommandMessageSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/MessageHelper.java, driver-core/src/test/unit/com/mongodb/internal/connection/ReplyMessageTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/TestInternalConnection.java
The dead code is a remnant of when the driver supported the full range of OP_REPLY wire protocol message usage.  Since the driver now only runs against MongoDB releases that support OP_MSG, OP_REPLY is only used for the response to the `hello` command in the handshake, and therefore most of the OP_REPLY-handling code is no longer on any execution paths.
JAVA-5204
=> Remove dead code in ReplyHeader

driver-core/src/main/com/mongodb/internal/binding/AsyncClusterAwareReadWriteBinding.java, driver-core/src/main/com/mongodb/internal/binding/AsyncClusterBinding.java, driver-core/src/main/com/mongodb/internal/binding/ClusterAwareReadWriteBinding.java, driver-core/src/main/com/mongodb/internal/binding/ClusterBinding.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/crypt/CryptBinding.java, driver-sync/src/main/com/mongodb/client/internal/CryptBinding.java
from the following internal interfaces:
* ClusterAwareReadWriteBinding
* AsyncClusterAwareReadWriteBinding
The interfaces remain, as they have picket up a second method.  The existing interface names arguably still make sense since implementations have to be "cluster-aware" in order to implement the remaining method.
JAVA-5217
=> Remove getCluster method

driver-core/src/main/com/mongodb/internal/operation/AbstractWriteSearchIndexOperation.java, driver-core/src/main/com/mongodb/internal/operation/CreateSearchIndexesOperation.java, driver-core/src/main/com/mongodb/internal/operation/DropSearchIndexOperation.java, driver-core/src/main/com/mongodb/internal/operation/Operations.java, driver-core/src/main/com/mongodb/internal/operation/UpdateSearchIndexesOperation.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/MongoCollectionImpl.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/MongoOperationPublisher.java, driver-sync/src/main/com/mongodb/client/internal/ListSearchIndexesIterableImpl.java, driver-sync/src/main/com/mongodb/client/internal/MongoCollectionImpl.java, driver-sync/src/test/functional/com/mongodb/client/AbstractAtlasSearchIndexManagementProseTest.java
=> Remove write and read concern from Atlas Search Index commands.

driver-core/src/main/com/mongodb/MongoBulkWriteException.java, driver-core/src/main/com/mongodb/MongoWriteConcernException.java, driver-core/src/main/com/mongodb/MongoWriteException.java, driver-core/src/main/com/mongodb/bulk/WriteConcernError.java, driver-core/src/main/com/mongodb/internal/connection/BulkWriteBatchCombiner.java, driver-core/src/main/com/mongodb/internal/operation/FindAndModifyHelper.java, driver-core/src/main/com/mongodb/internal/operation/WriteConcernHelper.java, driver-core/src/test/unit/com/mongodb/MongoWriteExceptionTest.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/MongoOperationPublisher.java, driver-sync/src/main/com/mongodb/client/internal/MongoCollectionImpl.java
JAVA-5153
This requires a bit of refactoring in order to remove any usage of the errorLabels in WriteConcernError, and to consolidate error label addition in MongoWriteConcernException
=> Remove deprecated methods in WriteConcernError class

driver-core/src/main/com/mongodb/internal/connection/AsynchronousChannelStream.java, driver-core/src/main/com/mongodb/internal/connection/FutureAsyncCompletionHandler.java, driver-core/src/main/com/mongodb/internal/connection/netty/NettyStream.java
Somehow we ended up with three nearly identical classes, all of which were unnecessarily complicated.
Remove two of them and simplify the remaining one to use CompletableFuture.
=> Simplify async Stream implementations

driver-core/src/main/com/mongodb/connection/ClusterSettings.java, driver-core/src/test/unit/com/mongodb/connection/ClusterSettingsSpecification.groovy
This is a new incarnation of https://github.com/mongodb/mongo-java-driver/pull/1261. The original PR was automatically closed when the target branch named `5.x` was deleted.
JAVA-5088
=> `ClusterSettings` does not compute `ClusterConnectionMode` consistently

.evergreen/.evg.yml
=> Install legacy shell

driver-sync/src/test/functional/com/mongodb/client/AbstractRetryableWritesTest.java
Skipping this test is justified because every server version prior to 4.4 is already EOL.
Note that the target branch for this PR is the master branch plus the PR already approved for JAVA-5153.
JAVA-5153
=> Skip test on MongoDB releases prior to 4.4.

driver-core/src/main/com/mongodb/MongoBulkWriteException.java, driver-core/src/main/com/mongodb/MongoWriteConcernException.java, driver-core/src/main/com/mongodb/MongoWriteException.java, driver-core/src/main/com/mongodb/bulk/WriteConcernError.java, driver-core/src/main/com/mongodb/internal/connection/BulkWriteBatchCombiner.java, driver-core/src/main/com/mongodb/internal/operation/FindAndModifyHelper.java, driver-core/src/main/com/mongodb/internal/operation/WriteConcernHelper.java, driver-core/src/test/unit/com/mongodb/MongoWriteExceptionTest.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/MongoOperationPublisher.java, driver-sync/src/main/com/mongodb/client/internal/MongoCollectionImpl.java, driver-sync/src/test/functional/com/mongodb/client/AbstractRetryableWritesTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTestValidator.java
JAVA-5153
This has already been reviewed in https://github.com/mongodb/mongo-java-driver/pull/1257 and https://github.com/mongodb/mongo-java-driver/pull/1269.  This PR is just to merge it into master.
=> Remove deprecated methods in WriteConcernError class 

bson/src/main/org/bson/BsonDecimal128.java, bson/src/main/org/bson/BsonValue.java, bson/src/test/unit/org/bson/BsonValueSpecification.groovy, config/codenarc/codenarc.xml
* Change implementation of BsonDecimal128#intValue/longValue/doubleValue to just call the corresponding methods in Decimal128, which handle infinity and NaN similarly to JDK classes
* Change BsonValue#isNumber/asNumber to treat BsonDecimal128 as a number
JAVA-5265
=> Improve BsonNumber support for Decimal128

driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/BatchCursorFlux.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/unified/ClientSideOperationTimeoutTest.java
Caused by using `doOnError` rather than using `subscribe` and passing the handler in there.
JAVA-5266
=> Fix `onErrorDropped` logged message

driver-core/src/main/com/mongodb/connection/SocketSettings.java, driver-core/src/test/unit/com/mongodb/connection/SocketSettingsSpecification.groovy, driver-core/src/test/unit/com/mongodb/connection/SocketSettingsTest.java
=> Accept `long` instead of `int` in `SocketSettings.Builder.connectTimeout`/`readTimeout`

driver-core/src/main/com/mongodb/client/model/Filters.java, driver-core/src/main/com/mongodb/client/model/search/VectorSearchOptions.java, driver-core/src/test/functional/com/mongodb/client/model/search/AggregatesSearchIntegrationTest.java, driver-core/src/test/unit/com/mongodb/client/model/FiltersSpecification.groovy, driver-scala/src/main/scala/org/mongodb/scala/model/Filters.scala, driver-scala/src/test/scala/org/mongodb/scala/model/FiltersSpec.scala
=> Remove `Filters.eqFull`

driver-core/src/main/com/mongodb/internal/connection/CommandHelper.java, driver-core/src/main/com/mongodb/internal/connection/DefaultClusterableServerFactory.java, driver-core/src/main/com/mongodb/internal/connection/DefaultServerMonitor.java, driver-core/src/test/functional/com/mongodb/internal/connection/CommandHelperSpecification.groovy, driver-core/src/test/functional/com/mongodb/internal/connection/ServerMonitorSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/DefaultServerMonitorSpecification.groovy
JAVA-5256
The driver is compliant with https://github.com/mongodb/specifications/blob/master/source/sessions/driver-sessions.rst#gossipping-the-cluster-time, but in the case reported, the driver connects to a member of a different replica set and by the time it realizes that the server should be discarded it's too late.  We can address this by not gossiping cluster time from monitoring connections.
=> Don't gossip cluster time from monitoring connections

driver-scala/src/integration/scala/org/mongodb/scala/documentation/DocumentationTransactionsExampleSpec.scala, driver-scala/src/main/scala/org/mongodb/scala/AggregateObservable.scala, driver-scala/src/main/scala/org/mongodb/scala/ClientSessionImplicits.scala, driver-scala/src/main/scala/org/mongodb/scala/MapReduceObservable.scala, driver-scala/src/main/scala/org/mongodb/scala/MongoCollection.scala, driver-scala/src/main/scala/org/mongodb/scala/MongoDatabase.scala, driver-scala/src/main/scala/org/mongodb/scala/Observable.scala, driver-scala/src/main/scala/org/mongodb/scala/ObservableImplicits.scala, driver-scala/src/main/scala/org/mongodb/scala/Observer.scala, driver-scala/src/main/scala/org/mongodb/scala/SingleObservable.scala, driver-scala/src/main/scala/org/mongodb/scala/gridfs/GridFSBucket.scala, driver-scala/src/main/scala/org/mongodb/scala/gridfs/package.scala, driver-scala/src/main/scala/org/mongodb/scala/internal/UnitObservable.scala, driver-scala/src/test/scala/org/mongodb/scala/ObservableImplicitsToGridFSUploadPublisherUnitSpec.scala, driver-scala/src/test/scala/org/mongodb/scala/gridfs/GridFSUploadPublisherSpec.scala, driver-scala/src/test/scala/org/mongodb/scala/internal/UnitObservableSpec.scala
This PR is a proof that even a single ape typing behind a keyboard can produce a PR that compiles. Vigilance from reviewers is especially needed here.
JAVA-4303
=> Expose `Observable[Unit]` instead of `Observable[Void]`

driver-core/src/main/com/mongodb/connection/ConnectionId.java, driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java, driver-core/src/main/com/mongodb/internal/connection/DescriptionHelper.java, driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnectionInitializer.java, driver-core/src/test/unit/com/mongodb/connection/ConnectionIdSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/AbstractConnectionPoolTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/InternalStreamConnectionInitializerSpecification.groovy, driver-sync/src/test/functional/com/mongodb/client/unified/Entities.java, driver-sync/src/test/functional/com/mongodb/client/unified/EventMatcher.java
The corresponding spec change: https://github.com/mongodb/specifications/commit/1f272b30a2e9714578b71a02b2836d5a0bd853f8.
JAVA-4846
=> Make `ConnectionId.serverValue`/`localValue` of the `Long`/`long` type

driver-core/src/main/com/mongodb/event/ConnectionCheckOutFailedEvent.java, driver-core/src/main/com/mongodb/event/ConnectionCheckedOutEvent.java, driver-core/src/main/com/mongodb/event/ConnectionReadyEvent.java, driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java
The spec change: https://github.com/mongodb/specifications/commit/c6621d01b37df9c7a9ae2036f10d0b6597047bc3.
JAVA-5121
=> Account the time to deliver connection pool events as part of the reported duration

driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/BatchCursorFlux.java
Caused by using `doOnError` rather than using `subscribe` and passing the handler in there.
JAVA-5284 JAVA-5266
=> Fix `onErrorDropped` logged message (#1281)

driver-core/src/main/com/mongodb/internal/connection/ZlibCompressor.java
Reclaim native memory quicker by overriding `close()` to invoke `end()` on the deflater, since by supplying a deflater to the constructor of `DeflaterOutputStream` `usesDefaultDeflater` is set to `false` and therefore `end()` is not invoked in [DeflaterOutputStream#close](https://github.com/openjdk/jdk/blob/2a59243cbaf3e7d5d1bfc9f247d28bc648687ea5/src/java.base/share/classes/java/util/zip/DeflaterOutputStream.java#L241).
This is related to [JDK-4797189]( https://bugs.openjdk.org/browse/JDK-4797189) bug/feature (marked as Won't Fix)
See the following blog post for more information: https://medium.com/swlh/native-memory-the-silent-jvm-killer-595913cba8e7
JAVA-5280
=> Reclaim native memory quicker when using ZlibCompressor

bson-kotlin/src/main/kotlin/org/bson/codecs/kotlin/DataClassCodec.kt, bson-kotlin/src/test/kotlin/org/bson/codecs/kotlin/DataClassCodecProviderTest.kt, bson-kotlin/src/test/kotlin/org/bson/codecs/kotlin/samples/DataClasses.kt
It has been observed that the Kotlin can behave
differently during reflection and return Type<Object> where normally it would report the correct type.
Checking for erasure allows the bson-kotlin library to handle these cases and return the expected type.
JAVA-5292
=> Handle kotlin / JVM erasure of types

bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/KotlinSerializerCodecProvider.kt, bson-kotlinx/src/test/kotlin/org/bson/codecs/kotlinx/KotlinSerializerCodecProviderTest.kt
Allow configuration to be set on the KotlinSerializerCodecProvider
JAVA-5276
=> Simplify customization of bson-kotlinx

driver-core/src/main/com/mongodb/internal/connection/ClientMetadataHelper.java, driver-core/src/main/com/mongodb/internal/connection/FaasEnvironment.java
Move FaasEnvironment enum and related static methods to a top-level class, in preparation for use in DefaultServerMonitor.
JAVA-4936
=> Refactor FaaS support in ClientMetadataHelper

driver-core/src/main/com/mongodb/connection/ClusterSettings.java
While working on https://jira.mongodb.org/browse/HELP-55236 I noticed a few things we may improve, and did the changes in this PR.
=> Do minor improvements to method docs in `ClusterSettings`

driver-core/src/main/com/mongodb/assertions/Assertions.java, driver-core/src/main/com/mongodb/connection/AsyncCompletionHandler.java, driver-core/src/main/com/mongodb/internal/async/AsyncConsumer.java, driver-core/src/main/com/mongodb/internal/async/AsyncFunction.java, driver-core/src/main/com/mongodb/internal/async/AsyncRunnable.java, driver-core/src/main/com/mongodb/internal/async/AsyncSupplier.java, driver-core/src/main/com/mongodb/internal/async/SingleResultCallback.java, driver-core/src/main/com/mongodb/internal/async/function/RetryingAsyncCallbackSupplier.java, driver-core/src/test/functional/com/mongodb/client/TestListener.java, driver-core/src/test/unit/com/mongodb/internal/async/AsyncFunctionsTest.java
JAVA-5082
This is https://github.com/mongodb/mongo-java-driver/pull/1234, but with demo refactoring removed (that is, this is just the async API, with no other changes).
The first commit, "Add async functions", was reviewed as part of https://github.com/mongodb/mongo-java-driver/pull/1134 , but can be further reviewed. Other commits are all new non-reviewed code.
=> Add async API (2)

driver-core/src/test/functional/com/mongodb/client/test/CollectionHelper.java, driver-sync/src/test/functional/com/mongodb/client/unified/Entities.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java
Advance cluster time on all session entities in unified tests to one after the initial data is created
JAVA-5334
=> Fix test failures on 8.0 sharded clusters

driver-core/src/main/com/mongodb/ConnectionString.java, driver-core/src/main/com/mongodb/MongoCredential.java, driver-core/src/main/com/mongodb/internal/connection/OidcAuthenticator.java, driver-core/src/test/unit/com/mongodb/AuthConnectionStringTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/Entities.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedAuthTest.java, driver-sync/src/test/functional/com/mongodb/internal/connection/OidcAuthenticationProseTests.java
JAVA-5328
Note that two marked prose tests are omitted, awaiting DRIVERS-2836
Otherwise, everything is [passing on evergreen.](https://spruce.mongodb.com/version/65d68e8ee3c331e9b31fc329/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
=> Add Human OIDC Workflow

driver-sync/src/test/functional/com/mongodb/client/AbstractSessionsProseTest.java
There are two tests in AbstractSessionsProseTest that rely on a running mongocryptd process.  Each test starts and destroys the process, and it appears that occasionally the destruction in the first test interferes with the starting in the second test, and the second test fails to connect to the mongocryptd process.
This commit attempts to work around this by starting a single mongocryptd process and use it for both tests. Note that AbstractSessionsProseTest has two subclasses and therefore the mongocryptd process is still actually started and destroyed twice, it doesn't seem to be a problem in practice because the two subclasses are in different modules and there is enough time between their execution that there is interference.
JAVA-4998
Note: I ran a patch build of the 40 4.2+ …
=> Fix timing-related test failure in SessionsProseTest

.evergreen/.evg.yml, .evergreen/javaConfig.bash, .evergreen/run-scala-tests.sh, .evergreen/run-tests.sh, build.gradle, driver-core/src/test/functional/com/mongodb/internal/connection/SocketStreamHelperSpecification.groovy, driver-reactive-streams/build.gradle, driver-scala/src/integration/scala/org/mongodb/scala/TestMongoClientHelper.scala, gradle.properties
This PR builds up on https://github.com/mongodb/mongo-java-driver/pull/1242.
* Add JDK 21 to Gradle configuration
* Add JDK 21 to the test matrix
* Replace JDK 17 with JDK 21 for tasks that are ony run using latest JDK
* Update dependencies (some now have to be conditional)
* Update `run-scala-tests.sh` to use `JAVA_VERSION`
* Run the `scala-tests` task with JDK 8, 17, 21 similarly to `kotlin-tests`
* Fix test code that assumed Java SE 9+
JAVA-5164
=> Test on Java 21

driver-core/src/test/functional/com/mongodb/client/test/CollectionHelper.java
JAVA-5352
I've observed this failure a few times since migrating more unified tests.  Appears to happen only on 4.0 sharded clusters.  I ran a patch of all those variants twice and was able to trigger the new retry logic in one of the eight runs, and it looks like the Interrupted error happens just once and the next drop execution succeeds.  So the change is effective.
=> Retry drop on Interrupted server error

driver-core/src/main/com/mongodb/internal/bulk/DeleteRequest.java, driver-core/src/main/com/mongodb/internal/bulk/UpdateRequest.java, driver-core/src/main/com/mongodb/internal/connection/SplittablePayload.java, driver-core/src/main/com/mongodb/internal/operation/BaseFindAndModifyOperation.java, driver-core/src/main/com/mongodb/internal/operation/FindAndDeleteOperation.java, driver-core/src/main/com/mongodb/internal/operation/FindAndReplaceOperation.java, driver-core/src/main/com/mongodb/internal/operation/FindAndUpdateOperation.java, driver-core/src/main/com/mongodb/internal/operation/Operations.java
Unlike every other instance of Bson in the CRUD API, the hint option for write operations was not converted to a BsonDocument prior to passing it down to the operation layer.  This is a problem because the operation layer doesn't have a CodecRegistry available, and so can not properly due the conversion.
In this commit, all hint options are converted to BsonDocument in the same place as all the other Bson options, where a CodecRegistry is available to properly do the conversion.
JAVA-5357
Note that no additional tests have been added.  The coverage for hint is the same as for all the other Bson-typed options (e.g. filter, projection).
=> Convert Bson to BsonDocument for hint

driver-core/src/main/com/mongodb/internal/operation/MapReduceToCollectionOperation.java, driver-core/src/main/com/mongodb/internal/operation/MapReduceWithInlineResultsOperation.java, driver-core/src/test/functional/com/mongodb/internal/operation/MapReduceToCollectionOperationSpecification.groovy, driver-core/src/test/functional/com/mongodb/internal/operation/MapReduceWithInlineResultsOperationSpecification.groovy
The server accepts both but new unified spec tests require the latter.
JAVA-5363
=> Change mapreduce to mapReduce

driver-core/src/test/functional/com/mongodb/ClusterFixture.java
JAVA-5311
Note that a lot more tests are running now and a lot more are failing on latest, as expected.
=> Fix ClusterFixture#hasEncryptionTestsEnabled to correctly detect env vars

bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/BsonDecoder.kt, bson-kotlinx/src/test/kotlin/org/bson/codecs/kotlinx/KotlinSerializerCodecProviderTest.kt, bson-kotlinx/src/test/kotlin/org/bson/codecs/kotlinx/KotlinSerializerCodecTest.kt, bson-kotlinx/src/test/kotlin/org/bson/codecs/kotlinx/samples/DataClasses.kt
=> Support discriminators not being the first field when decoding

driver-core/src/main/com/mongodb/MongoClientSettings.java, driver-core/src/main/com/mongodb/internal/connection/ServerAddressHelper.java, driver-core/src/main/resources/META-INF/native-image/org.mongodb/bson/native-image.properties, driver-core/src/main/resources/META-INF/native-image/resource-config.json, driver-core/src/test/unit/com/mongodb/connection/ServerAddressHelperTest.java
This is a backport of https://github.com/mongodb/mongo-java-driver/pull/1353.
The changes made to the `:graalvm-native-image-app` Gradle project were not included, neither were the API documentation changes made to `MongoClientSettings`, the rest of the changes was taken as is.
JAVA-5390
=> Use `InetAddressResolverProvider` and add tests

driver-core/src/test/functional/com/mongodb/internal/operation/ChangeStreamOperationSpecification.groovy
=> Force unique clusterTime values by splitting insert into two commands

driver-kotlin-coroutine/build.gradle.kts, driver-kotlin-coroutine/src/integration/kotlin/com/mongodb/kotlin/client/coroutine/SmokeTests.kt, driver-kotlin-sync/src/integration/kotlin/com/mongodb/kotlin/client/SmokeTests.kt, driver-kotlin-sync/src/main/kotlin/com/mongodb/kotlin/client/DistinctIterable.kt, driver-kotlin-sync/src/main/kotlin/com/mongodb/kotlin/client/MongoCollection.kt, driver-kotlin-sync/src/main/kotlin/com/mongodb/kotlin/client/MongoCursor.kt, driver-kotlin-sync/src/main/kotlin/com/mongodb/kotlin/client/MongoIterable.kt
Allow for nullable types in those scenarios.
JAVA-5358
=> Expand bounds for distinct and MongoIterable#map

.evergreen/.evg.yml
=> Replace sh with bash

driver-core/src/test/resources/unified-test-format/command-logging/unacknowledged-write.json, driver-core/src/test/resources/unified-test-format/command-monitoring/unacknowledgedBulkWrite.json, driver-sync/src/test/functional/com/mongodb/client/unified/LogMatcher.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java
This will force completion of the w: 0 write, which addresses a TCP-based race condition in the tests
JAVA-5398
=> Follow unacknowledged write with a find in spec tests

gradle/javadoc.gradle, gradle/publish.gradle
Tested by manually doing the following:
- `rm -r ~/.m2/repository/org/mongodb`
- `rm -r ./build/docs`
- `./gradlew clean docs publishToMavenLocal -x signMavenJavaPublication`
- - check that `./build/docs/bson` exists and `./build/docs/graalvm-native-image-app` does not.
- check that `~/.m2/repository/org/mongodb/bson` exists and `~/.m2/repository/org/mongodb/graalvm-native-image-app` does not.
JAVA-5414
=> Exclude `:graalvm-native-image-app` from being published

.evergreen/.evg.yml, gradle/publish.gradle
This commit adds papertrail tracing on release to all modules we release. This tracing will run on every snapshot and release.
=> JAVA-5415: add artifact tracing on publish

driver-core/src/main/com/mongodb/WriteConcern.java, driver-core/src/main/com/mongodb/assertions/Assertions.java, driver-core/src/main/com/mongodb/internal/async/function/RetryState.java, driver-core/src/main/com/mongodb/internal/operation/AbortTransactionOperation.java, driver-core/src/main/com/mongodb/internal/operation/AsyncOperations.java, driver-core/src/main/com/mongodb/internal/operation/CommitTransactionOperation.java, driver-core/src/main/com/mongodb/internal/operation/SyncOperations.java, driver-core/src/main/com/mongodb/internal/operation/TransactionOperation.java, driver-core/src/main/com/mongodb/internal/operation/WriteConcernHelper.java, driver-core/src/main/com/mongodb/internal/session/BaseClientSessionImpl.java, driver-core/src/test/functional/com/mongodb/internal/connection/TestCommandListener.java, driver-core/src/test/resources/unified-test-format/client-side-operation-timeout/deprecated-options.json, driver-core/src/test/unit/com/mongodb/internal/async/function/RetryStateTest.java, driver-core/src/test/unit/com/mongodb/internal/operation/WriteConcernHelperTest.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/ClientSessionPublisherImpl.java, driver-sync/src/main/com/mongodb/client/internal/ClientSessionImpl.java, driver-sync/src/test/functional/com/mongodb/client/AbstractClientSideOperationsTimeoutProseTest.java, driver-sync/src/test/functional/com/mongodb/client/ClientSideOperationTimeoutTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudHelper.java, driver-sync/src/test/unit/com/mongodb/client/gridfs/GridFSBucketsSpecification.groovy, driver-sync/src/test/unit/com/mongodb/client/internal/MongoCollectionSpecification.groovy, driver-sync/src/test/unit/com/mongodb/client/internal/MongoDatabaseSpecification.groovy
=> CSOT: Ignore wTimeoutMS 

driver-core/src/test/resources/connection-monitoring-and-pooling/cmap-format/pool-checkin-make-available.json, driver-core/src/test/resources/connection-monitoring-and-pooling/cmap-format/pool-checkout-connection.json, driver-core/src/test/resources/connection-monitoring-and-pooling/cmap-format/pool-checkout-error-closed.json, driver-core/src/test/resources/connection-monitoring-and-pooling/cmap-format/pool-checkout-maxConnecting-timeout.json, driver-core/src/test/resources/connection-monitoring-and-pooling/cmap-format/pool-clear-clears-waitqueue.json, driver-core/src/test/resources/connection-monitoring-and-pooling/cmap-format/pool-clear-ready.json, driver-core/src/test/resources/connection-monitoring-and-pooling/cmap-format/pool-ready.json, driver-core/src/test/resources/connection-monitoring-and-pooling/cmap-format/wait-queue-timeout.json, driver-core/src/test/unit/com/mongodb/internal/connection/AbstractConnectionPoolTest.java
=> Test that durations are included on relevant pool events

.evergreen/.evg.yml, .evergreen/run-mongodb-oidc-test.sh, driver-core/src/main/com/mongodb/ConnectionString.java, driver-core/src/main/com/mongodb/MongoCredential.java, driver-core/src/main/com/mongodb/internal/Locks.java, driver-core/src/main/com/mongodb/internal/authentication/AzureCredentialHelper.java, driver-core/src/main/com/mongodb/internal/authentication/CredentialInfo.java, driver-core/src/main/com/mongodb/internal/authentication/GcpCredentialHelper.java, driver-core/src/main/com/mongodb/internal/connection/OidcAuthenticator.java, driver-core/src/test/resources/auth/legacy/connection-string.json, driver-core/src/test/resources/unified-test-format/auth/mongodb-oidc-no-retry.json, driver-core/src/test/unit/com/mongodb/ConnectionStringSpecification.groovy, driver-core/src/test/unit/com/mongodb/ConnectionStringUnitTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/Entities.java, driver-sync/src/test/functional/com/mongodb/client/unified/RunOnRequirementsMatcher.java, driver-sync/src/test/functional/com/mongodb/internal/connection/OidcAuthenticationProseTests.java
JAVA-5353 API naming
JAVA-5395 Atlas testing
JAVA-4834 Azure
JAVA-4932 GCP
=> OIDC Add remaining environments (azure, gcp), evergreen testing, API naming updates

driver-core/src/main/com/mongodb/internal/TimeoutContext.java, driver-core/src/main/com/mongodb/internal/connection/CommandMessage.java, driver-core/src/main/com/mongodb/internal/connection/SocketStream.java, driver-core/src/main/com/mongodb/internal/connection/SocketStreamHelper.java, driver-core/src/main/com/mongodb/internal/connection/netty/NettyStream.java, driver-core/src/test/unit/com/mongodb/internal/TimeoutContextTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/CommandMessageTest.java
- Resolve regression where CSOT exception is exposed despite CSOT being disabled.
- Correct premature decrease in connect timeout before connection initiation.
- Encapsulating logic within TimeoutContext.
JAVA-5439
=> Fix regression in timeout handling.

driver-sync/src/main/com/mongodb/client/internal/ClientSessionImpl.java, driver-sync/src/test/functional/com/mongodb/client/AbstractClientSideOperationsTimeoutProseTest.java, driver-sync/src/test/functional/com/mongodb/client/ClientSideOperationTimeoutTest.java
=> Ensure TimeoutContext is present for a subsequent commit operation.

.evergreen/.evg.yml
JAVA-5450 (part)
[Logs](https://evergreen.mongodb.com/task_log_raw/mongo_java_driver_testgcpoidc_variant_oidc_auth_test_gcp_330d3b172edad4d9072552127937bd51493e1365_24_05_03_14_22_30/0?type=T#L2891). Intended to resolve `git` exiting with 1 when on master. Cannot test until it is on master. Passes when [not on master](https://spruce.mongodb.com/version/663953cf3a5c0f000746ed63/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC). 
```
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
```
=> Allow empty commits for OIDC evergreen script

sbom.json
My current best understanding of why we are adding this and how it will be used is in this [comment](https://jira.mongodb.org/browse/JAVA-5449?focusedCommentId=6346320&focusedId=6346320&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-6346320).
JAVA-5449
=> Add empty SBOM Lite

driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnection.java
=> Remove RTT check before reading a response from the server.

bson/src/main/org/bson/types/ObjectId.java, config/spotbugs/exclude.xml
To get the rank data, I had enabled SpotBugs XML reports, then was commenting out parts of `exclude.xml` and manually get the rank data from the XML reports.
JAVA-5431
=> Augment `config/spotbugs/exclude.xml` with finding status and rank

build.gradle, config/spotbugs/exclude.xml, driver-core/src/main/com/mongodb/internal/connection/AbstractMultiServerCluster.java
* Exclude CT_CONSTRUCTOR_THROW
* Exclude PA_PUBLIC_PRIMITIVE_ATTRIBUTE
* Add assertion to handle NP warning
JAVA-5480
=> Upgrade to Spotbugs 6.0.15

.evergreen/ssdlc-report.sh, build.gradle
In the future this script may do more work for us.
JAVA-5431
=> Add `ssdlc-report.sh` that uses SpotBugs to create SARIF files

.evergreen/run-mongodb-oidc-test.sh, driver-sync/src/test/functional/com/mongodb/client/unified/Entities.java, driver-sync/src/test/functional/com/mongodb/internal/connection/OidcAuthenticationProseTests.java
Fixes failing tests: reverts removal of admin credentials for OIDC tests, and corrects a typo in a validation test.
JAVA-5450
=> OIDC admin credentials

.evergreen/.evg.yml, .evergreen/run-mongodb-aws-test.sh
The legacy shell was only used in AWS authentication tests, so updating those gets rid of the last remaining use of the legacy shell.
JAVA-4791
=> Remove legacy shell from test scripts

driver-sync/src/main/com/mongodb/client/gridfs/GridFSBucketImpl.java, driver-sync/src/main/com/mongodb/client/gridfs/GridFSDownloadStreamImpl.java, driver-sync/src/main/com/mongodb/client/gridfs/GridFSUploadStreamImpl.java, driver-sync/src/test/unit/com/mongodb/client/gridfs/GridFSBucketSpecification.groovy, driver-sync/src/test/unit/com/mongodb/client/gridfs/GridFSDownloadStreamSpecification.groovy, driver-sync/src/test/unit/com/mongodb/client/gridfs/GridFSUploadStreamSpecification.groovy
This PR introduces performance improvement in the GridFS implementation of the sync Java driver, specifically targeting the `GridFSDownloadStream` and `GridFSUploadStream` classes. It was identified that byte arrays are cloned twice internally via the `Binary` class, which impacts throughput.
Modified `GridFSDownloadStream` and `GridFSUploadStream` to use `BsonDocument `instead of `Document.` The `BsonDocument` implementation avoids the unnecessary copying in the `BsonBinary` class, thus enhancing performance.
**GridFS Download:**
Stable Region Mean on main branch = 769.21 MBps
Perf result mean = 1030.63 MBps
Improvement: Approximately 34.02% increase in throughput
**GridFS Upload:**
Stable Region Mean on main branch = 450.62 MBps
Perf result mean = 515.84 MBps
Improvement: Approximately …
=> Optimize GridFS throughput by removing redundant byte array cloning.

driver-core/src/main/com/mongodb/ConnectionString.java, driver-core/src/main/com/mongodb/MongoCredential.java, driver-core/src/test/resources/auth/legacy/connection-string.json, driver-core/src/test/resources/connection-string/valid-options.json, driver-core/src/test/resources/connection-string/valid-warnings.json, driver-core/src/test/unit/com/mongodb/ConnectionStringUnitTest.java, driver-sync/src/test/functional/com/mongodb/internal/connection/OidcAuthenticationProseTests.java
=> Disallow comma character in authMechanismProperties

driver-core/src/main/com/mongodb/internal/connection/OidcAuthenticator.java, driver-core/src/test/resources/unified-test-format/auth/mongodb-oidc-no-retry.json, driver-sync/src/test/functional/com/mongodb/internal/connection/OidcAuthenticationProseTests.java
JAVA-5350
Backport.
See (#1380)
=> ALLOWED_HOSTS validation, 1 minute machine timeout

build.gradle, driver-core/src/main/com/mongodb/client/model/vault/DataKeyOptions.java, driver-core/src/test/resources/client-side-encryption/legacy/azureKMS.json, driver-core/src/test/resources/client-side-encryption/legacy/gcpKMS.json, driver-core/src/test/resources/client-side-encryption/legacy/kmipKMS.json, driver-core/src/test/resources/unified-test-format/client-side-encryption/createDataKey.json, driver-core/src/test/resources/unified-test-format/client-side-encryption/rewrapManyDataKey.json
JAVA-5300
Copies tests, updates docs, and uses the (erroneously named) 1.8.0-SNAPSHOT which has the `delegated` feature available.
See also, update/fix in: https://github.com/mongodb/specifications/pull/1591
=> Add kmip tests, use mongoCrypt snapshot

driver-core/src/main/com/mongodb/ConnectionString.java, driver-core/src/test/resources/connection-string/invalid-uris.json, driver-core/src/test/resources/connection-string/valid-auth.json, driver-core/src/test/resources/connection-string/valid-options.json, driver-core/src/test/resources/connection-string/valid-unix_socket-absolute.json, driver-core/src/test/resources/connection-string/valid-unix_socket-relative.json, driver-core/src/test/resources/connection-string/valid-warnings.json, driver-core/src/test/unit/com/mongodb/ConnectionStringSpecification.groovy, driver-core/src/test/unit/com/mongodb/ConnectionStringTest.java, driver-legacy/src/test/unit/com/mongodb/MongoClientURISpecification.groovy
=> Forward slash in connection string is optional 

.github/workflows/bump-and-tag.sh, .github/workflows/release.yml
This PR adds a GitHub Actions Workflow to create releases. The process is as follows:
* Users with write access trigger a new workflow run for the "Release new version" workflow, entering the version to be released
* The automation does some sanity checks on the branch name:
** Release `<major>.<minor>.0` must be released from the maintenance branch (i.e. `<major>.<minor>.x`) or the `master` branch. If the `master` branch is selected, the automation will attempt to create a new maintenance branch
** Release `<major>.<minor>.<patch>` must be released from the maintenance branch (i.e. `<major>.<minor>.x`) - releasing from any other branches is not allowed
* The automation then updates the build version to `<major>.<minor>.<patch>` in `build.gradle`, commits this change and creates a tag
* …
=> JAVA-5479: Add GitHub Actions based release automation

driver-core/src/main/com/mongodb/ConnectionString.java, driver-legacy/src/main/com/mongodb/MongoClientURI.java
=> Update Javadoc to reflect that forward slash is optional

driver-core/src/main/com/mongodb/internal/TimeoutContext.java, driver-core/src/main/com/mongodb/internal/async/function/RetryState.java, driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnection.java, driver-core/src/main/com/mongodb/internal/connection/SocketStream.java, driver-core/src/main/com/mongodb/internal/operation/MixedBulkWriteOperation.java, driver-core/src/test/unit/com/mongodb/internal/TimeoutContextTest.java, driver-core/src/test/unit/com/mongodb/internal/async/function/RetryStateTest.java
JAVA-5379
This removes `hasExpired`, and expiry checks in retries (retries rely exclusively on timeout exceptions being thrown by blocking operations, to signal that the retry should halt).
=> Remove hasExpired and expiry checks in retries

driver-core/src/main/com/mongodb/internal/connection/DomainNameUtils.java, driver-core/src/test/functional/com/mongodb/internal/connection/DomainNameUtilsTest.java
Modified the regex pattern to support top-level domain (TLD) lengths of up to 63 characters, in accordance with RFC 1034 standards.
This update ensures our regex can handle the 'internal' TLD used in EC2 guest OS hostnames, thus increasing the flexibility of TLD validation.
JAVA-5490
=> Extend Socks5 TLD regex validation to support up to 63 characters

.evergreen/.evg.yml, .evergreen/ssdlc-report.sh, .evergreen/template_ssdlc_compliance_report.md
This is a backport of https://github.com/mongodb/mongo-java-driver/pull/1426 to `5.1.x`.
JAVA-5500
=> Include links to the Evergreen build and to the driver security testing summary in the SSDLC report (#1426)

driver-core/src/main/com/mongodb/internal/connection/DomainNameUtils.java, driver-core/src/test/functional/com/mongodb/internal/connection/DomainNameUtilsTest.java
This is a backport of https://github.com/mongodb/mongo-java-driver/pull/1427
[JAVA-5490](https://jira.mongodb.org/browse/JAVA-5490)
=> Extend Socks5 TLD regex validation to support up to 63 characters 

bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/BsonEncoder.kt, bson-kotlinx/src/test/kotlin/org/bson/codecs/kotlinx/KotlinSerializerCodecTest.kt, bson-kotlinx/src/test/kotlin/org/bson/codecs/kotlinx/samples/DataClasses.kt
Encoding a generic class object with a nullable type parameter, like `DataClassWithNullableGeneric`, will fail with `org.bson.BsonInvalidOperationException: writeString can only be called when State is VALUE, not when State is NAME` or `org.bson.BsonInvalidOperationException: writeNull can only be called when State is VALUE, not when State is NAME` depending on whether `boxed` is null.
```kotlin
@Serializable data class Box<T>(val boxed: T)
@Serializable data class DataClassWithNullableGeneric(val box: Box<String?>)
```
JAVA-5342
=> JAVA-5342 Fix encoding nullable generics

bson-kotlin/src/test/kotlin/org/bson/codecs/kotlin/DataClassCodecTest.kt, bson-kotlin/src/test/kotlin/org/bson/codecs/kotlin/samples/DataClasses.kt
=> Ported tests from bson-kotlinx to bson-kotlin

driver-core/src/main/com/mongodb/internal/operation/MixedBulkWriteOperation.java, driver-core/src/test/unit/com/mongodb/internal/async/function/RetryStateTest.java
=> Enable ignored tests.

.evergreen/.evg.yml, .evergreen/ssdlc-report.sh
=> Fix for: Include links to the Evergreen build and to the driver security testing summary in the SSDLC report

bson/src/main/org/bson/codecs/pojo/LazyPropertyModelCodec.java, bson/src/main/org/bson/codecs/pojo/PojoCodecImpl.java, bson/src/main/org/bson/codecs/pojo/PojoCodecProvider.java, bson/src/test/unit/org/bson/codecs/pojo/PojoCustomTest.java, bson/src/test/unit/org/bson/codecs/pojo/PojoTestCase.java, bson/src/test/unit/org/bson/codecs/pojo/entities/BaseField.java, bson/src/test/unit/org/bson/codecs/pojo/entities/ConcreteField.java, bson/src/test/unit/org/bson/codecs/pojo/entities/ConcreteModel.java, bson/src/test/unit/org/bson/codecs/pojo/entities/GenericBaseModel.java
This change fixes a regression which prevents the driver from encoding and decoding concrete classes which extend generic base classes, when the base class is specified as the generic type of the MongoCollection.
JAVA-5173
=> Allow generic base classes for POJOs

.github/workflows/release.yml
With this change, commits made by the release automation and the git tag itself will be attributed to the user triggering the workflow. We can do so without knowing the email address of a user by using GitHub's anonymous email address format `<id>+<name>@users.noreply.github.com`.
This fixes the issue where the tag run in Evergreen does not know which employee created the release, which is relevant for the internal Papertrail service.
=> Attribute release commit and tag to user triggering the workflow

.github/workflows/bump-and-tag.sh, .github/workflows/bump-version.sh, .github/workflows/release.yml
This adds support for pre-releases in the release tooling. For now, this considers only alpha and beta versions, but release candidates can be added as well.
Differences between stable releases and pre-releases:
* For pre-releases, the GitHub Release is marked as such
* For pre-releases, the version in build.gradle is set back to a snapshot of said version, e.g. 5.3.0-beta1 => 5.3.0-snapshot
Branch checks are run on the version without pre-release markers, so a pre-release for a patch release can only be created from the corresponding maintenance branch. At the same time, pre-release versions of non-patch releases can be created from the master branch, and the tooling will create the maintenance branch.
Link to a run: https://github.com/alcaeus/mongo-java-driver/actions/runs/9596715534 …
=> Support pre-releases in release tooling

driver-core/src/test/functional/com/mongodb/ClusterFixture.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/ClientSideOperationTimeoutProseTest.java, driver-sync/src/test/functional/com/mongodb/client/AbstractClientSideOperationsTimeoutProseTest.java, driver-sync/src/test/functional/com/mongodb/client/ClientSideOperationTimeoutTest.java, driver-sync/src/test/functional/com/mongodb/client/csot/AbstractClientSideOperationsEncryptionTimeoutProseTest.java
=> Double timeouts in serverless mode to reduce test execution flakiness.

driver-core/src/main/com/mongodb/internal/operation/CursorResourceManager.java, driver-core/src/test/functional/com/mongodb/internal/operation/AsyncCommandBatchCursorFunctionalTest.java, driver-core/src/test/unit/com/mongodb/internal/operation/CursorResourceManagerTest.java
This PR is an alternative to https://github.com/mongodb/mongo-java-driver/pull/1439.
The commit https://github.com/mongodb/mongo-java-driver/pull/1440/commits/b7be8c856f8e500dcc10ca39757c8dccf33769c3 introduces a draft reproducer of the bug reported in JAVA-5516. Then the following commit fixes it. The reproducer is not guaranteed to reproduce the error, but usually does so in just a few attempts on my machine. With the fix I was unable to reproduce the error.
The commit https://github.com/mongodb/mongo-java-driver/pull/1440/commits/510548421e663d391a89557a9940afeacba2dc9c introduces a reproducer that we can actually check into the codebase.
JAVA-5516
=> Fix `CursorResourceManager.close`

driver-core/src/main/com/mongodb/internal/operation/CursorResourceManager.java, driver-core/src/test/unit/com/mongodb/internal/operation/CursorResourceManagerTest.java
This is a backport of https://github.com/mongodb/mongo-java-driver/pull/1440.
JAVA-5516
=> Fix `CursorResourceManager.close` (#1440)

driver-core/src/main/com/mongodb/internal/operation/CursorResourceManager.java, driver-core/src/test/unit/com/mongodb/internal/operation/CursorResourceManagerTest.java
This is a backport of https://github.com/mongodb/mongo-java-driver/pull/1440.
JAVA-5516
=> Fix CursorResourceManager.close (#1440)

bson/src/main/org/bson/assertions/Assertions.java, driver-core/src/main/com/mongodb/internal/TimeoutContext.java, driver-core/src/main/com/mongodb/internal/connection/BaseCluster.java, driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnection.java, driver-core/src/main/com/mongodb/internal/operation/AsyncChangeStreamBatchCursor.java, driver-core/src/main/com/mongodb/internal/operation/ChangeStreamBatchCursor.java, driver-core/src/main/com/mongodb/internal/operation/CursorResourceManager.java, driver-core/src/main/com/mongodb/internal/session/BaseClientSessionImpl.java, driver-core/src/main/com/mongodb/internal/time/Timeout.java, driver-core/src/test/functional/com/mongodb/ClusterFixture.java, driver-core/src/test/functional/com/mongodb/internal/operation/FindOperationSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/operation/ChangeStreamBatchCursorTest.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/crypt/KeyManagementService.java
=> Unify timeout checks in exception handling methods.

driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/OperationExecutorImpl.java
As ` clientSessionHelper.withClientSession` will always produce a session, there is no need for the `switchIfEmpty` branch.
=> Remove redundant switchIfEmptyStage

driver-core/src/main/com/mongodb/internal/connection/ByteBufBsonDocument.java, driver-core/src/main/com/mongodb/internal/connection/CommandMessage.java
=> Support any number of Document Sequence Sections in CommandMessage#getCommandDocument

driver-scala/src/main/scala/org/mongodb/scala/AggregateObservable.scala, driver-scala/src/main/scala/org/mongodb/scala/DistinctObservable.scala, driver-scala/src/main/scala/org/mongodb/scala/FindObservable.scala, driver-scala/src/main/scala/org/mongodb/scala/ListCollectionsObservable.scala, driver-scala/src/main/scala/org/mongodb/scala/ListDatabasesObservable.scala, driver-scala/src/main/scala/org/mongodb/scala/ListIndexesObservable.scala, driver-scala/src/main/scala/org/mongodb/scala/ListSearchIndexesObservable.scala, driver-scala/src/main/scala/org/mongodb/scala/MapReduceObservable.scala, driver-scala/src/main/scala/org/mongodb/scala/gridfs/GridFSBucket.scala
Correct Scaladoc references to methods and classes that were producing warnings.
=> Correct Scaladoc references to methods and classes.

bson-kotlin/src/test/kotlin/org/bson/codecs/kotlin/DataClassCodecTest.kt, bson-kotlin/src/test/kotlin/org/bson/codecs/kotlin/samples/DataClasses.kt, bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/BsonEncoder.kt, bson-kotlinx/src/test/kotlin/org/bson/codecs/kotlinx/KotlinSerializerCodecTest.kt, bson-kotlinx/src/test/kotlin/org/bson/codecs/kotlinx/samples/DataClasses.kt
Ensures that the `deferredElement` name is reset as it does in `encodeSerializableValue`. 
Test case ported to bson-kotlin
JAVA-5524
=> Fix bson-kotlinx `encodeNullableSerializableValue` null handling

bson-kotlin/src/main/kotlin/org/bson/codecs/kotlin/ArrayCodec.kt, bson-kotlin/src/main/kotlin/org/bson/codecs/kotlin/ArrayCodecProvider.kt, bson-kotlin/src/main/kotlin/org/bson/codecs/kotlin/DataClassCodec.kt, bson-kotlin/src/test/kotlin/org/bson/codecs/kotlin/DataClassCodecTest.kt, bson-kotlin/src/test/kotlin/org/bson/codecs/kotlin/samples/DataClasses.kt, driver-core/src/main/com/mongodb/KotlinCodecProvider.java
Adds Kotlin array support to the bson-kotlin library
JAVA-5122
=> Added Bson-Kotlin Array Codec

driver-core/src/main/com/mongodb/ConnectionString.java, driver-core/src/test/unit/com/mongodb/ConnectionStringUnitTest.java
Don't output the host and port information if the port is invalid. Reduces risk of leaking password information if the password has not been correctly urlencoded.
JAVA-5560
=> Connection String

driver-core/src/test/unit/com/mongodb/internal/connection/ProtocolHelperSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/operation/OperationUnitSpecification.groovy, driver-sync/src/test/functional/com/mongodb/client/AbstractClientSideEncryptionAwsCredentialFromEnvironmentTest.java
The following commit introduced many warnings https://github.com/mongodb/mongo-java-driver/commit/01aff5a0789f71b9d0b56190d4996e8ac5436827. Many of them were then fixed in https://github.com/mongodb/mongo-java-driver/commit/cd297a13d1868e6a22b88529016a17fda618363d. This PR fixes most of the ones that are still present.
=> Fix most of the build warnings

driver-core/src/main/com/mongodb/internal/connection/IdHoldingBsonWriter.java, driver-core/src/main/com/mongodb/internal/connection/SplittablePayload.java, driver-core/src/test/unit/com/mongodb/internal/connection/IdHoldingBsonWriterSpecification.groovy, driver-sync/src/test/functional/com/mongodb/client/CrudProseTest.java
This is a backport of https://github.com/mongodb/mongo-java-driver/pull/1482 to `4.11.x`
JAVA-5572
=> MixedBulkWriteOperation should generate inserted document IDs at most once per batch

driver-core/src/main/com/mongodb/internal/async/AsyncFunction.java, driver-core/src/main/com/mongodb/internal/async/AsyncRunnable.java, driver-core/src/main/com/mongodb/internal/async/AsyncSupplier.java, driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnection.java, driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnectionInitializer.java, driver-core/src/test/unit/com/mongodb/internal/async/AsyncFunctionsAbstractTest.java, driver-core/src/test/unit/com/mongodb/internal/async/AsyncFunctionsTestBase.java, driver-core/src/test/unit/com/mongodb/internal/async/SameThreadAsyncFunctionsTest.java, driver-core/src/test/unit/com/mongodb/internal/async/SeparateThreadAsyncFunctionsTest.java
- Resolve an issue where exceptions thrown during thenRun, thenSupply, and related operations in the asynchronous API were not properly propagated to the completion callback. This issue was addressed by replacing `unsafeFinish` with `finish`, ensuring that exceptions are caught and correctly passed to the completion callback when executed on different threads.
- Update existing Async API tests to ensure they simulate separate async thread execution.
JAVA-5562
=> Fix exception propagation in Async API methods

driver-core/src/main/com/mongodb/internal/async/AsyncFunction.java, driver-core/src/main/com/mongodb/internal/async/AsyncRunnable.java, driver-core/src/main/com/mongodb/internal/async/AsyncSupplier.java, driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnection.java, driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnectionInitializer.java, driver-core/src/test/unit/com/mongodb/internal/async/AsyncFunctionsAbstractTest.java, driver-core/src/test/unit/com/mongodb/internal/async/AsyncFunctionsTestBase.java, driver-core/src/test/unit/com/mongodb/internal/async/SameThreadAsyncFunctionsTest.java, driver-core/src/test/unit/com/mongodb/internal/async/SeparateThreadAsyncFunctionsTest.java
This PR is a partial backport of [PR #1479](https://github.com/mongodb/mongo-java-driver/pull/1479).
**CSOT-related logic is not included in this backport** as the 5.1.x branch does not support CSOT. Only code changes relevant to the functionality in 5.1.x are included.
- Exception handling in Async API:
Resolved an issue where exceptions thrown during thenRun, thenSupply, and related operations in the asynchronous API were not properly propagated to the completion callback. This was fixed by replacing unsafeFinish with finish, ensuring exceptions are caught and correctly passed to the completion callback, even when executed on different threads.
- Async API test updates:
Updated existing Async API tests to simulate execution on separate async threads, ensuring accurate testing of the …
=> [Backport] Fix exception propagation in Async API methods

driver-core/src/main/com/mongodb/internal/connection/tlschannel/async/AsynchronousTlsChannel.java, driver-core/src/main/com/mongodb/internal/connection/tlschannel/async/AsynchronousTlsChannelGroup.java
JAVA-5505
Mostly-automated refactoring to remove IDE nags. I've left unused methods like `getCurrentRegistrationCount` in `AsynchronousTlsChannelGroup`.
=> JAVA-5505 minor refactoring

.github/workflows/bump-and-tag.sh, .github/workflows/bump-version.sh, .github/workflows/release.yml
Backporting JAVA-5479 to the 4.11.x branch so we can use GH Actions for 4.11 patch releases.
=> JAVA-5479 backport

driver-core/src/main/com/mongodb/internal/operation/QueryBatchCursor.java, driver-core/src/test/unit/com/mongodb/internal/operation/QueryBatchCursorResourceManagerTest.java
This is a backport of https://github.com/mongodb/mongo-java-driver/pull/1440 to `4.11.x`.
JAVA-5516
=> Fix `QueryBatchCursor.ResourceManager.close` (#1440)

driver-core/src/main/com/mongodb/internal/TimeoutContext.java, driver-core/src/main/com/mongodb/internal/connection/CommandHelper.java, driver-core/src/main/com/mongodb/internal/operation/AggregateOperation.java, driver-core/src/main/com/mongodb/internal/operation/FindOperation.java, driver-core/src/main/com/mongodb/internal/operation/MapReduceToCollectionOperation.java, driver-core/src/main/com/mongodb/internal/operation/MapReduceWithInlineResultsOperation.java, driver-core/src/main/com/mongodb/internal/operation/OperationHelper.java, driver-sync/src/test/functional/com/mongodb/client/AbstractExplainTest.java
=> Set maxTimeMS explicitly for commands being explained

driver-core/src/main/com/mongodb/MongoUpdatedEncryptedFieldsException.java, driver-core/src/main/com/mongodb/client/model/CreateCollectionOptions.java, driver-core/src/main/com/mongodb/client/model/CreateEncryptedCollectionParams.java, driver-core/src/main/com/mongodb/client/model/DropCollectionOptions.java, driver-core/src/main/com/mongodb/client/model/vault/EncryptOptions.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/crypt/Crypt.java
Encrypted fields are used as part of Range encryption which is no longer in server preview.
JAVA-5441
=> Remove remaining beta annotations for encrypted fields.

bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/BsonDecoder.kt, bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/BsonEncoder.kt, bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/KotlinSerializerCodec.kt, bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/utils/BsonCodecUtils.kt, bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/utils/BsonEncoderDecoderUtils.kt
Made BsonEncoder / Decoder internal as part of the JsonElement support, however, this reduces the flexibility of the API and that change should be reverted
JAVA-5623
=> Revert making BsonEncoder / BsonDecoder internal

driver-core/build.gradle
`com.oracle.svm.core.annotate` comes from the `compileOnly "org.graalvm.sdk:graal-sdk:$graalSdkVersion"` dependency. This dependency is provided by the GraalVM runtime, and [Gradle instructs us to use the {{compileOnly}} configuration for provided dependencies](https://docs.gradle.org/current/userguide/migrating_from_maven.html#migmvn:migrating_deps).
JAVA-5632
=> Exclude `com.oracle.svm.core.annotate` from `Import-Package` for OSGi

config/spotbugs/exclude.xml, driver-kotlin-extensions/build.gradle.kts, driver-kotlin-extensions/src/main/kotlin/com/mongodb/kotlin/client/model/Projections.kt, driver-kotlin-extensions/src/main/kotlin/com/mongodb/kotlin/client/model/Properties.kt, driver-kotlin-extensions/src/test/kotlin/com/mongodb/kotlin/client/model/ExtensionsApiTest.kt, driver-kotlin-extensions/src/test/kotlin/com/mongodb/kotlin/client/model/KPropertiesTest.kt, driver-kotlin-extensions/src/test/kotlin/com/mongodb/kotlin/client/model/ProjectionTest.kt
Fixes JAVA-5603.
Based on kmongo-property with more tests and a bug fix in the path extension method throwing an NPE for calculated properties without a Kotlin backing field.
=> Adding Kotlin extensions methods for projection.

driver-core/src/test/resources/unified-test-format/client-side-operation-timeout/command-execution.json, driver-core/src/test/resources/unified-test-format/load-balancers/sdam-error-handling.json, driver-core/src/test/resources/unified-test-format/server-discovery-and-monitoring/hello-command-error.json, driver-core/src/test/resources/unified-test-format/server-discovery-and-monitoring/hello-network-error.json, driver-core/src/test/resources/unified-test-format/server-discovery-and-monitoring/minPoolSize-error.json
https://jira.mongodb.org/browse/JAVA-5445
I tested it locally with evergreen patch. The previously "skipped" tests are enabled and passed (for 4.4 build variants)
e.g. https://spruce.mongodb.com/task/mongo_java_driver_tests_jdk_secure__version~4.4_os~linux_topology~standalone_auth~auth_ssl~ssl_jdk~jdk17_test_patch_5ebeec89c47f747524554e7a64f58918ac559c16_66f9750c8ea18700077234d0_24_09_29_15_41_01?execution=0&page=0&sortBy=STATUS&sortDir=ASC&testname=hello-command-error
=> Enable tests that require failCommand with appName on initial handshake before 4.9

.evergreen/.evg.yml
Noticed this due to warning when validating the config file:
```
~/git/mongo-java-driver (main)$ evergreen validate .evergreen/.evg.yml
WARNING: strict unmarshalling YAML: load project error(s): error unmarshalling yaml strict: input fields may not match the command fields: yaml: unmarshal errors:
line 146: cannot unmarshal !!seq into struct { Function string "yaml:\"func,omitempty\" bson:\"func,omitempty\""; Type string "yaml:\"type,omitempty\" bson:\"type,omitempty\""; DisplayName string "yaml:\"display_name,omitempty\" bson:\"display_name,omitempty\""; Command string "yaml:\"command,omitempty\" bson:\"command,omitempty\""; Variants []string "yaml:\"variants,omitempty\" bson:\"variants,omitempty\""; TimeoutSecs int "yaml:\"timeout_secs,omitempty\" bson:\"timeout_secs,omitempty\""; …
```
=> Fix Evergreen config file error

driver-core/src/test/resources/unified-test-format/valid-fail/kmsProviders-missing_aws_kms_credentials.json, driver-core/src/test/resources/unified-test-format/valid-fail/kmsProviders-missing_azure_kms_credentials.json, driver-core/src/test/resources/unified-test-format/valid-fail/kmsProviders-missing_gcp_kms_credentials.json, driver-core/src/test/resources/unified-test-format/valid-fail/kmsProviders-no_kms.json, driver-core/src/test/resources/unified-test-format/valid-pass/collectionData-createOptions.json, driver-core/src/test/resources/unified-test-format/valid-pass/createEntities-operation.json, driver-core/src/test/resources/unified-test-format/valid-pass/entity-commandCursor.json, driver-core/src/test/resources/unified-test-format/valid-pass/entity-cursor-iterateOnce.json, driver-core/src/test/resources/unified-test-format/valid-pass/entity-find-cursor.json, driver-core/src/test/resources/unified-test-format/valid-pass/expectedEventsForClient-topologyDescriptionChangedEvent.json, driver-core/src/test/resources/unified-test-format/valid-pass/kmsProviders-explicit_kms_credentials.json, driver-core/src/test/resources/unified-test-format/valid-pass/kmsProviders-mixed_kms_credential_fields.json, driver-core/src/test/resources/unified-test-format/valid-pass/kmsProviders-placeholder_kms_credentials.json, driver-core/src/test/resources/unified-test-format/valid-pass/kmsProviders-unconfigured_kms.json, driver-core/src/test/resources/unified-test-format/valid-pass/matches-lte-operator.json, driver-core/src/test/resources/unified-test-format/valid-pass/poc-crud.json, driver-core/src/test/resources/unified-test-format/valid-pass/poc-retryable-writes.json, driver-core/src/test/resources/unified-test-format/valid-pass/poc-sessions.json, driver-core/src/test/resources/unified-test-format/valid-pass/poc-transactions-convenient-api.json, driver-core/src/test/resources/unified-test-format/valid-pass/poc-transactions-mongos-pin-auto.json, driver-core/src/test/resources/unified-test-format/valid-pass/poc-transactions.json, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTestValidator.java
=> Sync valid-pass/valid-fail tests from unified test specification

.evergreen/run-kotlin-tests.sh, .evergreen/static-checks.sh, bson-kotlin/build.gradle.kts, bson-kotlinx/build.gradle.kts, driver-kotlin-coroutine/build.gradle.kts, driver-kotlin-extensions/build.gradle.kts, driver-kotlin-sync/build.gradle.kts
=> Grouping static checks under the same task

config/spotbugs/exclude.xml, driver-kotlin-extensions/src/main/kotlin/com/mongodb/kotlin/client/model/Indexes.kt, driver-kotlin-extensions/src/test/kotlin/com/mongodb/kotlin/client/model/ExtensionsApiTest.kt, driver-kotlin-extensions/src/test/kotlin/com/mongodb/kotlin/client/model/IndexesTest.kt
=> Add extension methods for Indexes 

config/spotbugs/exclude.xml, driver-kotlin-extensions/src/main/kotlin/com/mongodb/kotlin/client/model/Sorts.kt, driver-kotlin-extensions/src/test/kotlin/com/mongodb/kotlin/client/model/ExtensionsApiTest.kt, driver-kotlin-extensions/src/test/kotlin/com/mongodb/kotlin/client/model/SortsTest.kt
=> Adding extension method for Sorts

bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/DateTimeSerializers.kt
LocalTime was added in kotlinx.datetime v0.4.0 and won't be available if older versions of kotlinx datetime are on the classpath.
JAVA-5641
=> Ensure kotlinx.datetime.LocalTime exists before adding the serializer

.evergreen/.evg.yml, build.gradle, gradle.properties
Updated to: 2.11.12, 2.12.20, 2.13.15
JAVA-5649
=> Bump Scala patch versions

mongodb-crypt/src/main/resources/META-INF/native-image/native-image.properties
Ideally, we could create a project that uses Quarkus, and test the solution. But I am not going to work on that now.
JAVA-5683
=> Make `CAPI`, `jna.Native`/`Structure` initializable at run time

mongodb-crypt/src/main/resources/META-INF/native-image/native-image.properties
This is a backport of https://github.com/mongodb/mongo-java-driver/pull/1553 to 5.2.x
JAVA-5683
=> Make CAPI, jna.Native/Structure initializable at run time (#1553)

bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/DateTimeSerializers.kt
Backport of: (#1530)
> LocalTime was added in kotlinx.datetime v0.4.0 and won't be available if older versions of kotlinx datetime are on the classpath.
JAVA-5641
=> Backport #1530

.evergreen/.evg.yml, .evergreen/run-mongodb-aws-test.sh
The legacy shell was only used in AWS authentication tests, so updating those gets rid of the last remaining use of the legacy shell.
Backport of (https://github.com/mongodb/mongo-java-driver/pull/1404)
JAVA-4791
=> Remove legacy shell from test scripts (#1404)

.evergreen/.evg.yml, driver-core/src/test/resources/atlas-data-lake/getMore.json
Updated ADL test batch size assertion to match Java driver behavioral change introduced in JAVA-5159
Backport of (#1274)
JAVA-5235
(cherry picked from commit 9286233d5a6bc33c3a022c524810f04368118851)
=> Pull mongohouse image from ADL ECR repo (#1274)

driver-core/src/test/resources/connection-monitoring-and-pooling/cmap-format/pool-checkout-returned-connection-maxConnecting.json
=> Update `pool-checkout-returned-connection-maxConnecting.json` to work with different pool implementations

driver-core/src/main/com/mongodb/ServerAddress.java, driver-core/src/main/com/mongodb/client/model/UnwindOptions.java, driver-kotlin-extensions/build.gradle.kts, driver-kotlin-extensions/src/main/kotlin/com/mongodb/kotlin/client/model/Accumulators.kt, driver-kotlin-extensions/src/main/kotlin/com/mongodb/kotlin/client/model/Aggregates.kt, driver-kotlin-extensions/src/test/kotlin/com/mongodb/kotlin/client/model/AggregatesTest.kt, driver-kotlin-extensions/src/test/kotlin/com/mongodb/kotlin/client/model/ExtensionsApiTest.kt, driver-sync/src/test/functional/com/mongodb/client/csot/AbstractClientSideOperationsEncryptionTimeoutProseTest.java
Fixes JAVA-5606 and  JAVA-5605
=> Adding extensions for Aggregators and Accumulators

driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTestFailureValidator.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTestModifications.java
In #1557, I neglected to push (optional) PR fixes before merging (naming, etc.). After merging, I saw I could move the assumption out of the API, which cleaned things up a bit.
=> Clean up TestDef API, clarify naming

.evergreen/run-kotlin-tests.sh, .evergreen/static-checks.sh, THIRD-PARTY-NOTICES, bson-kotlin/build.gradle.kts, bson-kotlinx/build.gradle.kts, config/spotbugs/exclude.xml, driver-core/src/main/com/mongodb/ServerAddress.java, driver-core/src/main/com/mongodb/client/model/UnwindOptions.java, driver-kotlin-coroutine/build.gradle.kts, driver-kotlin-extensions/build.gradle.kts, driver-kotlin-extensions/src/main/kotlin/com/mongodb/kotlin/client/model/Accumulators.kt, driver-kotlin-extensions/src/main/kotlin/com/mongodb/kotlin/client/model/Aggregates.kt, driver-kotlin-extensions/src/main/kotlin/com/mongodb/kotlin/client/model/Filters.kt, driver-kotlin-extensions/src/main/kotlin/com/mongodb/kotlin/client/model/Indexes.kt, driver-kotlin-extensions/src/main/kotlin/com/mongodb/kotlin/client/model/Projections.kt, driver-kotlin-extensions/src/main/kotlin/com/mongodb/kotlin/client/model/Properties.kt, driver-kotlin-extensions/src/main/kotlin/com/mongodb/kotlin/client/model/Sorts.kt, driver-kotlin-extensions/src/main/kotlin/com/mongodb/kotlin/client/model/Updates.kt, driver-kotlin-extensions/src/main/kotlin/com/mongodb/kotlin/client/property/KPropertyPath.kt, driver-kotlin-extensions/src/main/kotlin/kotlin/internal/OnlyInputTypes.kt, driver-kotlin-extensions/src/test/kotlin/com/mongodb/kotlin/client/model/AggregatesTest.kt, driver-kotlin-extensions/src/test/kotlin/com/mongodb/kotlin/client/model/ExtensionsApiTest.kt, driver-kotlin-extensions/src/test/kotlin/com/mongodb/kotlin/client/model/FiltersTest.kt, driver-kotlin-extensions/src/test/kotlin/com/mongodb/kotlin/client/model/IndexesTest.kt, driver-kotlin-extensions/src/test/kotlin/com/mongodb/kotlin/client/model/KPropertiesTest.kt, driver-kotlin-extensions/src/test/kotlin/com/mongodb/kotlin/client/model/ProjectionTest.kt, driver-kotlin-extensions/src/test/kotlin/com/mongodb/kotlin/client/model/SortsTest.kt, driver-kotlin-extensions/src/test/kotlin/com/mongodb/kotlin/client/model/UpdatesTest.kt, driver-kotlin-sync/build.gradle.kts, driver-sync/src/test/functional/com/mongodb/client/csot/AbstractClientSideOperationsEncryptionTimeoutProseTest.java
This completes the Epic in https://jira.mongodb.org/browse/JAVA-5624
=> Merging feature branch (Kotlin extensions) into main 

driver-core/src/main/com/mongodb/ClientBulkWriteException.java, driver-core/src/main/com/mongodb/internal/operation/OperationHelper.java, driver-sync/src/test/functional/com/mongodb/client/AbstractClientSideOperationsTimeoutProseTest.java
This PR addresses the following `BULK-TODO`: https://github.com/mongodb/mongo-java-driver/pull/1509#discussion_r1786649241.
=> Replace `ClientBulkWriteException.getError` with `getCause`

driver-core/src/main/com/mongodb/internal/operation/ClientBulkWriteOperation.java, driver-core/src/test/resources/unified-test-format/command-monitoring/unacknowledged-client-bulkWrite.json, driver-core/src/test/resources/unified-test-format/crud/client-bulkWrite-errors.json, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/CrudProseTest.java, driver-sync/src/test/functional/com/mongodb/client/CrudProseTest.java
=> Forbid ordered/verbose unacknowledged bulk writes

.evergreen/ssdlc-report.sh
=> Stop using the `kotlinCheck` Gradle task from `ssdlc-report.sh`

driver-core/src/main/com/mongodb/internal/Locks.java, driver-core/src/main/com/mongodb/internal/connection/ConcurrentPool.java, driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java
We are allowed to do this due to DRIVERS-3056.
JAVA-5680
=> Remove explicit fairness from `DefaultConnectionPool`

driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTestModifications.java
When `com.mongodb.client.unified.UnifiedTest` is used by `com.mongodb.workload.WorkloadExecutor` for running tests with Astrolabe, `TestDef` shouldn't be created.
JAVA-5716
=> Make sure `TestDef` is created and used only when there is enough data to do that

driver-core/src/main/com/mongodb/internal/operation/AsyncOperations.java, driver-core/src/main/com/mongodb/internal/operation/DistinctOperation.java, driver-core/src/main/com/mongodb/internal/operation/Operations.java, driver-core/src/main/com/mongodb/internal/operation/SyncOperations.java, driver-core/src/test/resources/unified-test-format/crud/distinct-hint.json, driver-kotlin-coroutine/src/integration/kotlin/com/mongodb/kotlin/client/coroutine/syncadapter/SyncDistinctIterable.kt, driver-kotlin-coroutine/src/main/kotlin/com/mongodb/kotlin/client/coroutine/DistinctFlow.kt, driver-kotlin-sync/src/integration/kotlin/com/mongodb/kotlin/client/syncadapter/SyncDistinctIterable.kt, driver-kotlin-sync/src/main/kotlin/com/mongodb/kotlin/client/DistinctIterable.kt, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/DistinctPublisher.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/DistinctPublisherImpl.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/syncadapter/SyncDistinctIterable.java, driver-scala/src/integration/scala/org/mongodb/scala/syncadapter/SyncDistinctIterable.scala, driver-scala/src/main/scala/org/mongodb/scala/DistinctObservable.scala, driver-sync/src/main/com/mongodb/client/DistinctIterable.java, driver-sync/src/main/com/mongodb/client/internal/DistinctIterableImpl.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudHelper.java
[JAVA-5686](https://jira.mongodb.org/browse/JAVA-5686?filter=-1)
This PR adds index hint support for `distinct` command for java, kotlin, and scala. It also syncs CRUD unified spec tests to [77b1f78458cf25b525cde2274e33acd5db2581d2](https://github.com/mongodb/specifications/commit/77b1f78458cf25b525cde2274e33acd5db2581d2).
=> Add index hint support for distinct command

config/detekt/detekt.yml, driver-kotlin-coroutine/src/integration/kotlin/com/mongodb/kotlin/client/coroutine/syncadapter/SyncMongoCluster.kt, driver-kotlin-coroutine/src/main/kotlin/com/mongodb/kotlin/client/coroutine/MongoCluster.kt, driver-kotlin-coroutine/src/test/kotlin/com/mongodb/kotlin/client/coroutine/MongoClientTest.kt, driver-kotlin-sync/src/integration/kotlin/com/mongodb/kotlin/client/syncadapter/SyncMongoCluster.kt, driver-kotlin-sync/src/main/kotlin/com/mongodb/kotlin/client/MongoCluster.kt, driver-kotlin-sync/src/test/kotlin/com/mongodb/kotlin/client/MongoClientTest.kt, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java
- Add sync and coroutine Bulk Write API.
- Enable unified spec tests.
Primary review: @katcharov 
Secondary (optional): @stIncMale 
JAVA-5532
=> Add Kotlin Bulk Write API

bson/src/main/org/bson/PackedBitVector.java, bson/src/main/org/bson/Vector.java, bson/src/main/org/bson/annotations/Beta.java, bson/src/main/org/bson/annotations/Reason.java, bson/src/main/org/bson/annotations/package-info.java
=> Mark PackedBitVector as Beta, aligning with binary quantization preview

driver-core/src/main/com/mongodb/client/model/bulk/BaseClientDeleteOptions.java, driver-core/src/main/com/mongodb/client/model/bulk/BaseClientUpsertableWriteModelOptions.java, driver-core/src/main/com/mongodb/client/model/bulk/BaseClientWriteModelOptions.java, driver-core/src/main/com/mongodb/client/model/bulk/ClientReplaceOneOptions.java, driver-core/src/main/com/mongodb/client/model/bulk/ClientUpdateOneOptions.java, driver-core/src/test/unit/com/mongodb/client/model/bulk/BaseClientUpsertableWriteModelOptionsTest.java, driver-core/src/test/unit/com/mongodb/client/model/bulk/BaseClientWriteModelOptionsTest.java
=> Add more `Base*` interfaces to better reflect the methods shared by different client write model options

driver-core/src/main/com/mongodb/internal/client/model/bulk/AbstractClientUpdateModel.java
=> Make `AbstractClientUpdateModel` implement `ClientWriteModel`

driver-scala/src/integration/scala/org/mongodb/scala/syncadapter/SyncMongoCluster.scala, driver-scala/src/test/scala/org/mongodb/scala/ApiAliasAndCompanionSpec.scala, driver-scala/src/test/scala/org/mongodb/scala/MongoClientSpec.scala
=> Tidy up BULK-TODOs

driver-kotlin-extensions/build.gradle.kts
=> Fixing default module name for kotlin-extensions

driver-sync/src/test/functional/com/mongodb/client/ClientSideEncryptionExternalKeyVaultTest.java, driver-sync/src/test/functional/com/mongodb/client/CrudProseTest.java
=> Fix test cleanup to prevent conflicts between tests.

driver-scala/src/integration/scala/org/mongodb/scala/syncadapter/SyncMongoCluster.scala, driver-scala/src/main/scala/org/mongodb/scala/MongoCluster.scala, driver-scala/src/main/scala/org/mongodb/scala/model/bulk/package.scala, driver-scala/src/main/scala/org/mongodb/scala/package.scala, driver-scala/src/test/scala/org/mongodb/scala/ApiAliasAndCompanionSpec.scala, driver-scala/src/test/scala/org/mongodb/scala/MongoClientSpec.scala, driver-scala/src/test/scala/org/mongodb/scala/ScalaPackageSpec.scala, driver-scala/src/test/scala/org/mongodb/scala/model/bulk/BulkModelSpec.scala
=> Add Scala Client Bulk Write API.

driver-kotlin-extensions/build.gradle.kts
Backport of https://github.com/mongodb/mongo-java-driver/pull/1602 to 5.3.1 release
=> Backport #5751 to 5.3.x

driver-core/src/main/com/mongodb/ConnectionString.java
Backport of (https://github.com/mongodb/mongo-java-driver/pull/1613)
JAVA-5770
=> Remove deprecation warnings. (#1613)

driver-core/src/main/com/mongodb/client/model/bulk/ClientReplaceOneOptions.java, driver-core/src/main/com/mongodb/client/model/bulk/ClientUpdateOneOptions.java, driver-core/src/main/com/mongodb/internal/client/model/bulk/ConcreteClientReplaceOneOptions.java, driver-core/src/main/com/mongodb/internal/client/model/bulk/ConcreteClientUpdateOneOptions.java, driver-core/src/main/com/mongodb/internal/connection/DefaultClusterableServerFactory.java, driver-core/src/main/com/mongodb/internal/operation/ClientBulkWriteOperation.java, driver-core/src/test/resources/unified-test-format/crud/client-bulkWrite-replaceOne-sort.json, driver-core/src/test/resources/unified-test-format/crud/client-bulkWrite-updateOne-sort.json, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudHelper.java
- Add sort option to updateOne.
- Add sort option to replaceOne.
JAVA-5723
=> Client Bulk Write sort option.

.evergreen/.evg.yml
=> Evergreen: Update to use stop-orchestration.sh

driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/gridfs/GridFSBucketImpl.java
=> Stop ignoring id parameter

driver-core/src/main/com/mongodb/internal/connection/ClientMetadataHelper.java, driver-core/src/main/com/mongodb/internal/connection/FaasEnvironment.java, driver-core/src/test/functional/com/mongodb/client/WithWrapper.java, driver-core/src/test/functional/com/mongodb/internal/connection/FaasEnvironmentAccessor.java
JAVA-5781
Fixes tests breaking due to `java.lang.reflect.InaccessibleObjectException`
=> JAVA-5781 Add env var override

driver-core/src/test/resources/unified-test-format/load-balancers/non-lb-connection-establishment.json
Sync `non-lb-connection-establishment` test to https://github.com/mongodb/specifications/commit/d05c33e0a6124ee7d1a9de665084d540b2ff06c5
Intended to proactively avoid tests failure once drivers start testing 8.1 builds. See DRIVERS-3108. Drivers are not-yet testing 8.1 (see [slack](https://mongodb.slack.com/archives/C72LB5RPV/p1739884710850709)).
JAVA-5791
=> JAVA-5791 Sync `non-lb-connection-establishment`

driver-core/src/test/resources/client-side-encryption-data/lookup/key-doc.json, driver-core/src/test/resources/client-side-encryption-data/lookup/schema-csfle.json, driver-core/src/test/resources/client-side-encryption-data/lookup/schema-csfle2.json, driver-core/src/test/resources/client-side-encryption-data/lookup/schema-qe.json, driver-core/src/test/resources/client-side-encryption-data/lookup/schema-qe2.json, driver-core/src/test/unit/com/mongodb/client/model/bulk/BaseClientDeleteOptionsTest.java, driver-core/src/test/unit/com/mongodb/client/model/bulk/BaseClientUpdateOptionsTest.java, driver-core/src/test/unit/com/mongodb/client/model/bulk/BaseClientUpsertableWriteModelOptionsTest.java, driver-core/src/test/unit/com/mongodb/client/model/bulk/BaseClientWriteModelOptionsTest.java, driver-core/src/test/unit/com/mongodb/testing/MongoAssertions.java, driver-core/src/test/unit/com/mongodb/testing/MongoBaseInterfaceAssertions.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/crypt/CollectionInfoRetriever.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/crypt/Crypt.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/ClientSideEncryption25Lookup.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/ClientSideEncryption25LookupProseTests.java, driver-sync/src/main/com/mongodb/client/internal/CollectionInfoRetriever.java, driver-sync/src/main/com/mongodb/client/internal/Crypt.java, driver-sync/src/test/functional/com/mongodb/client/ClientSideEncryption25Lookup.java, driver-sync/src/test/functional/com/mongodb/client/ClientSideEncryption25LookupProseTests.java, driver-sync/src/test/functional/com/mongodb/internal/connection/OidcAuthenticationProseTests.java, mongodb-crypt/build.gradle.kts, mongodb-crypt/src/main/com/mongodb/internal/crypt/capi/CAPI.java, mongodb-crypt/src/main/com/mongodb/internal/crypt/capi/MongoCryptImpl.java
JAVA-5767
Draft due to [failing tests](https://spruce.mongodb.com/task/mongo_java_driver_tests_jdk8_unsecure__version~latest_os~linux_topology~replicaset_auth~noauth_ssl~nossl_jdk~jdk8_test_sync_patch_fb3f30b79aecfa5b17404c33a29fb1f5fb6f4ffb_67bcebb804d4f40007c54213_25_02_24_21_59_29?execution=0&sortBy=STATUS&sortDir=ASC) (4 and 6).
=> JAVA-5767 Support $lookup in CSFLE and QE

driver-kotlin-extensions/src/main/kotlin/com/mongodb/kotlin/client/model/Properties.kt
As mentioned in JAVA-5776, I think this function should be public so custom functions can use the same path cache and name resolution as those provided by the driver.
=> JAVA-5776 Make KProperty<T>.path() public

driver-core/src/main/com/mongodb/assertions/Assertions.java, driver-kotlin-coroutine/src/integration/kotlin/com/mongodb/kotlin/client/coroutine/UnifiedCrudTest.kt, driver-kotlin-sync/src/integration/kotlin/com/mongodb/kotlin/client/UnifiedCrudTest.kt, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/unified/ClientSideOperationTimeoutTest.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/unified/UnifiedReactiveStreamsTest.java, driver-sync/src/test/functional/com/mongodb/client/AbstractClientSideOperationsTimeoutProseTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedSyncTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTestFailureValidator.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTestModifications.java, driver-workload-executor/src/main/com/mongodb/workload/WorkloadExecutor.java
JAVA-5795
See [WRITING-28651](https://jira.mongodb.org/browse/WRITING-28651)
This creates N copies (attempts) of the unified tests, and places a try-catch around shouldPassAllOutcomes. If an attempt passes, ensuing attempts are ignored. Failures are ignored, except the last attempt.
This is not intended to fully resolve the issue, but is a low-cost fix that should reduce failing tests.
=> Retry flaky unified tests

THIRD-PARTY-NOTICES, bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/BsonConfiguration.kt, bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/BsonDecoder.kt, bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/BsonEncoder.kt, bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/JsonBsonDecoder.kt, bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/JsonBsonEncoder.kt, bson-kotlinx/src/main/kotlin/org/bson/codecs/kotlinx/utils/BsonCodecUtils.kt, bson-kotlinx/src/test/kotlin/org/bson/codecs/kotlinx/KotlinSerializerCodecTest.kt, bson-kotlinx/src/test/kotlin/org/bson/codecs/kotlinx/samples/DataClasses.kt
Fixes Java-5736 
This PR adds some refactoring to https://github.com/mongodb/mongo-java-driver/pull/1589
=> JAVA-5736 Add bsonNamingStrategy option to support snake_case

driver-core/src/main/com/mongodb/internal/TimeoutContext.java, driver-core/src/test/resources/unified-test-format/client-side-operation-timeout/tailable-awaitData.json, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTestModifications.java
=> Adjust maxAwaitTimeMS by remaining timeout.

driver-core/src/main/com/mongodb/internal/connection/StreamFactoryHelper.java, driver-legacy/src/main/com/mongodb/MongoClient.java, driver-legacy/src/test/unit/com/mongodb/MongoClientSpecification.groovy, driver-sync/src/main/com/mongodb/client/MongoClients.java, driver-sync/src/main/com/mongodb/client/internal/Clusters.java, driver-sync/src/main/com/mongodb/client/internal/MongoClientImpl.java, driver-sync/src/test/functional/com/mongodb/client/MongoClientTest.java, driver-sync/src/test/unit/com/mongodb/client/MongoClientSpecification.groovy
=> Fix Netty event loop resource leak on MongoClient close.

driver-core/src/main/com/mongodb/ReadPreference.java, driver-core/src/main/com/mongodb/ReadPreferenceHedgeOptions.java, driver-core/src/main/com/mongodb/TaggableReadPreference.java
=> Deprecate read preference hedge options

driver-scala/build.gradle.kts
`[Warn] : While parsing annotations in .../mongo-java-driver/driver-core/build/libs/mongodb-driver-core-5.5.0-SNAPSHOT.jar(com/mongodb/lang/Nullable.class), could not find MAYBE in enum <none>.
This is likely due to an implementation restriction: an annotation argument cannot refer to a member of the annotated class (scala/bug#7014).`
=> Fix warnings

driver-core/src/test/resources/unified-test-format/crud/findOne.json, driver-kotlin-coroutine/src/integrationTest/kotlin/com/mongodb/kotlin/client/coroutine/UnifiedCrudTest.kt, driver-kotlin-coroutine/src/integrationTest/kotlin/com/mongodb/kotlin/client/coroutine/UnifiedTest.kt, driver-kotlin-sync/src/integrationTest/kotlin/com/mongodb/kotlin/client/UnifiedCrudTest.kt, driver-kotlin-sync/src/integrationTest/kotlin/com/mongodb/kotlin/client/UnifiedTest.kt, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/unified/UnifiedReactiveStreamsTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudHelper.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedSyncTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTestModifications.java
https://jira.mongodb.org/browse/JAVA-5666
=> Ensure findOne does not set batchSize=1

bom/build.gradle.kts
Snapshot build POM:
https://oss.sonatype.org/content/repositories/snapshots/org/mongodb/mongodb-driver-bom/5.5.0-SNAPSHOT/mongodb-driver-bom-5.5.0-20250331.210512-14.pom
JAVA-5825
=> Add Kotlin Extensions to BOM

driver-core/src/main/com/mongodb/internal/operation/ChangeStreamBatchCursorHelper.java, driver-core/src/main/com/mongodb/internal/operation/CommandOperationHelper.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTestModifications.java
This closes JAVA-5224 by adding `ReadConcernMajorityNotAvailableYet` (134) to retryable error codes list.
=> [JAVA-5224] Make ReadConcernMajorityNotAvailableYet a retryable error

bson/src/main/org/bson/json/JsonMode.java, bson/src/main/org/bson/types/Decimal128.java, driver-core/src/main/com/mongodb/internal/connection/Cluster.java, driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java, driver-core/src/main/com/mongodb/internal/connection/SdamServerDescriptionManager.java, driver-core/src/main/com/mongodb/internal/connection/Server.java, driver-core/src/test/functional/com/mongodb/internal/connection/ClientMetadataHelperProseTest.java, driver-core/src/test/functional/com/mongodb/internal/operation/ChangeStreamOperationProseTestSpecification.groovy, driver-core/src/test/resources/client-side-encryption/README.rst, driver-core/src/test/unit/com/mongodb/internal/connection/AbstractConnectionPoolTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/ConnectionPoolAsyncTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/ConnectionPoolTest.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/AtlasSearchIndexManagementProseTest.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/RetryableWritesProseTest.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/WriteConcernProseTest.java, driver-sync/src/test/functional/com/mongodb/client/AbstractServerSelectionProseTest.java, driver-sync/src/test/functional/com/mongodb/client/AbstractSessionsProseTest.java, driver-sync/src/test/functional/com/mongodb/client/AtlasSearchIndexManagementProseTest.java, driver-sync/src/test/functional/com/mongodb/client/ChangeStreamProseTest.java, driver-sync/src/test/functional/com/mongodb/client/ClientSideOperationTimeoutProseTest.java, driver-sync/src/test/functional/com/mongodb/client/RetryableWritesProseTest.java, driver-sync/src/test/functional/com/mongodb/client/ServerDiscoveryAndMonitoringProseTests.java, driver-sync/src/test/functional/com/mongodb/client/Socks5ProseTest.java, driver-sync/src/test/functional/com/mongodb/client/TransactionProseTest.java, driver-sync/src/test/functional/com/mongodb/client/WithTransactionProseTest.java
=> Update specifications links in source comments

bson/src/main/org/bson/BsonBinaryWriter.java, bson/src/test/unit/org/bson/BsonBinaryWriterTest.java
Instead of caching precomputed `String` values, we now cache their corresponding **byte[] representations**. This avoids repeated ASCII string decoding. 
The single contiguous buffer approach provides better cache locality in loops, reduced memory overhead and better performance. 
The array index caching implementation consumes approximately `12 KB of memory in total`:
```
ARRAY_INDEXES_BUFFER: ~3,890 bytes
Numbers 0-9: 10 × (1 byte + null terminator) = 20 bytes
Numbers 10-99: 90 × (2 byte + null terminator) = 270 bytes
Numbers 100-999: 900 × (3 bytes + null terminator) = 3,600 bytes
```
```
ARRAY_INDEXES_OFFSETS: 4,000 bytes
1,000 integers × 4 bytes per int = 4,000 bytes
```
```
ARRAY_INDEXES_LENGTHS: 4,000 bytes
1,000 integers × 4 bytes per int = 4,000 bytes
```
`Array object headers: …
=> Optimize BsonArray Index encoding

.evergreen/.evg.yml
=> Increase perf task timeout.

driver-core/src/main/com/mongodb/internal/connection/ByteBufferBsonOutput.java
The PR improves buffer handling by introducing a `currentByteBuffer` field to cache the current `ByteBuf`, reducing direct list access which is costly because of bounds checking. Additionally, caching `currentByteBuffer` helps with JIT (Just-In-Time) inlining based on compilation profiling. By making the buffer access more predictable and, the JIT compiler can better inline the `getCurrentByteBuffer` method, leading to improved runtime performance.
Test Name | Base Mean | Compare Mean | Perf Diff Percent | Z-Score
-- | -- | -- | -- | --
Deep BSON Encoding | 62.2417 | 71.5916 | 15.02% | 6.7074
Flat BSON Encoding | 133.9693 | 172.8321 | 29.01% | 10.3677
Full BSON Encoding | 139.8435 | 172.5080 | 23.36% | 20.1526
Large doc Client BulkWrite insert | 56.1605 | 62.9421 | 13.57% | 12.0393
Large …
=> Enhance buffer handling to reduce direct list access.

driver-core/src/main/com/mongodb/internal/connection/ByteBufferBsonOutput.java
PR #1651 missed changes introduced in PR #1675, leading to incorrect buffer handling in `ByteBufferBsonOutput`.
This PR merges both changes to resolve the issue.
- Replaced `getNextByteBuffer` with `getCurrentByteBuffer` in `writeOnBuffers` to correct buffer state management, because  `getNextByteBuffer` failed to update `currentByteBuffer`, causing encoding errors.
JAVA-5816
=> Fix ByteBufferBsonOutput buffer caching logic.

driver-core/src/test/functional/com/mongodb/internal/operation/AggregateOperationSpecification.groovy, driver-core/src/test/functional/com/mongodb/internal/operation/ChangeStreamOperationSpecification.groovy
=> Ignore collectionUUID field if present in change stream tests

bom/build.gradle.kts
=> Updated the bom validation to ensure it runs.

driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTestModifications.java, driver-sync/src/test/functional/com/mongodb/client/unified/ValueMatcher.java
=> Added regression tests for "number" alias in $$type operator.

.github/dependabot.yml
=> Added dependabot.yml to test updating git submodules.

driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudHelper.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTestModifications.java
=> Tests: Add support for crud tests bypassDocumentationValidation.json

driver-core/src/main/com/mongodb/AutoEncryptionSettings.java, driver-core/src/main/com/mongodb/ClientEncryptionSettings.java, driver-core/src/main/com/mongodb/internal/capi/MongoCryptHelper.java, driver-core/src/test/functional/com/mongodb/internal/capi/MongoCryptHelperTest.java, driver-sync/src/test/functional/com/mongodb/client/AbstractClientSideEncryptionTest.java, driver-sync/src/test/functional/com/mongodb/client/JsonPoweredCrudTestHelper.java, driver-sync/src/test/functional/com/mongodb/client/unified/Entities.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedClientEncryptionHelper.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java, mongodb-crypt/src/main/com/mongodb/internal/crypt/capi/CAPI.java, mongodb-crypt/src/main/com/mongodb/internal/crypt/capi/MongoCryptImpl.java, mongodb-crypt/src/main/com/mongodb/internal/crypt/capi/MongoCryptOptions.java
Added the `AutoEncryptionSettings.Builder#keyExpiration` method and `ClientEncryptionSettings.Builder#keyExpiration` method to configure the cache expiration time for data encryption keys.
JAVA-5547
=> Added option to configure DEK cache lifetime

driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTestModifications.java
Related to: 6bd6a19 and DRIVERS-2868 - I think there was an additional test that was missing an ignore.
JAVA-5720
=> Added extra test to ignore for reactive streams

driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTestModifications.java
The batchSize is larger than expected.
Added JAVA-5861 to investigate
=> Add non compliance skip for Atlas Data Lake getMore test

driver-kotlin-coroutine/src/main/kotlin/com/mongodb/kotlin/client/coroutine/AggregateFlow.kt, driver-kotlin-coroutine/src/main/kotlin/com/mongodb/kotlin/client/coroutine/MapReduceFlow.kt, driver-kotlin-coroutine/src/test/kotlin/com/mongodb/kotlin/client/coroutine/AggregateFlowTest.kt, driver-kotlin-coroutine/src/test/kotlin/com/mongodb/kotlin/client/coroutine/MapReduceFlowTest.kt, driver-kotlin-sync/src/main/kotlin/com/mongodb/kotlin/client/AggregateIterable.kt, driver-kotlin-sync/src/test/kotlin/com/mongodb/kotlin/client/AggregateIterableTest.kt, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/AggregatePublisher.java, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/MapReducePublisher.java, driver-scala/src/main/scala/org/mongodb/scala/AggregateObservable.scala, driver-scala/src/main/scala/org/mongodb/scala/MapReduceObservable.scala, driver-sync/src/main/com/mongodb/client/AggregateIterable.java, driver-sync/src/main/com/mongodb/client/MapReduceIterable.java, driver-sync/src/main/com/mongodb/client/MongoIterable.java
@rozza is the primary reviewer (chosen automatically), @katcharov is the secondary one (chosen manually based on the GitHub suggestion).
JAVA-5833
=> Improve the `toCollection` and related API documentation

driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedCrudHelper.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTestModifications.java
The reason this test fails is due to a unified test runner bug, in which a view is created only when a pipeline is specified.
JAVA-5769
=> Enable test of nsType with a collection view

.evergreen/.evg.yml
The perf.send functionality in evergreen is no longer maintained and is not the preferred method of sending performance data to the signal processing service. This PR updates the evergreen yaml file to instead send the data down stream using the preferred `performance-monitoring-api.corp.mongodb.com/raw_perf_results/cedar_report` end point.
Changes were tested in [this patch](https://spruce.mongodb.com/task/mongo_java_driver_perf_perf_patch_3e95e0d0815ef33743b330680a8f1426d5be8791_67f8294bde5b6400075f9e97_25_04_10_20_37_02/trend-charts?execution=0) and data was confirmed to be sending correctly.
JAVA-5864
DEVPROD-16438
=> DEVPROD-16438 - migrate perf.send to cedar_report endpoint

.github/workflows/release.yml
The changes have been tested in a forked repository.
Commits on main: [View commits](https://github.com/vbabanin/mongo-java-driver/commits/main)
5.5.x branch was created by GitHub Actions: [View branches](https://github.com/vbabanin/mongo-java-driver/branches)
Successful execution of the 5.5.0 GitHub Action: [View run](https://github.com/vbabanin/mongo-java-driver/actions/runs/14805885730)
Validation failures occurred as expected, since `release.yml` enforces version alignment with `5.6.0-SNAPSHOT` after  bumping to 5.6.0-SNAPSHOT. Tested the following versions:
5.5.7: [View run](https://github.com/vbabanin/mongo-java-driver/actions/runs/14805891719)
5.7.0: [View run](https://github.com/vbabanin/mongo-java-driver/actions/runs/14805899578)
JAVA-5867
=> Fix validation in release.yml

buildSrc/src/main/kotlin/conventions/publishing.gradle.kts, gradle.properties
Log a warning if the signing keys are missing.
JAVA-5872
=> Gradle: Ensure maven artifacts are signed.

driver-core/src/main/com/mongodb/ConnectionString.java, driver-core/src/test/unit/com/mongodb/UriOptionsTest.java
Duplicates are not permitted, where as elsewhere in the connection string they are.
JAVA-5834
=> Ensure socks5 proxy option parsing is to specification

.evergreen/.evg.yml, .evergreen/git-archive.sh
Ensure all submodules are included into the archive.
JAVA-5882
=> Evergreen added shell script to create a git archive

driver-core/src/main/com/mongodb/internal/connection/InternalStreamConnectionInitializer.java, driver-core/src/test/unit/com/mongodb/internal/connection/InternalStreamConnectionInitializerSpecification.groovy
=> Remove code that won't execute on supported server releases

driver-kotlin-extensions/src/main/kotlin/com/mongodb/kotlin/client/model/Properties.kt, driver-kotlin-extensions/src/main/kotlin/com/mongodb/kotlin/client/property/KPropertyPath.kt, driver-kotlin-extensions/src/test/kotlin/com/mongodb/kotlin/client/model/KPropertiesTest.kt
Backport of https://github.com/mongodb/mongo-java-driver/pull/1710
The `pathCache` utilised the string representation of the KProperty instance. The custom implementations didn't include the calculated `path` value, this can lead to naming collisions in the `pathCache` key.
This commit adds `hashCode` and `equals` methods to ensure the `name` value is included in our custom implementations of `KProperty1`. Finally, the cache key now uses the `hashCode` for the cacheKey.
JAVA-5868
=> Ensure custom KProperty include the name in the hashcode

.evergreen/.evg.yml
Backport of https://github.com/mongodb/mongo-java-driver/pull/1720 and #1703
[JAVA-5885](https://github.com/vbabanin/mongo-java-driver/tree/JAVA-5885)
=> Fix datalake and k8s test failures

driver-core/src/main/com/mongodb/internal/connection/Authenticator.java, driver-core/src/main/com/mongodb/internal/connection/OidcAuthenticator.java
Backport of https://github.com/mongodb/mongo-java-driver/pull/1733
No conflicts.
JAVA-5880
=> Use OperationContext with NOOP Session (#1733)

build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/settings.gradle.kts, buildSrc/src/main/kotlin/conventions/bnd.gradle.kts, buildSrc/src/main/kotlin/conventions/detekt.gradle.kts, buildSrc/src/main/kotlin/conventions/dokka.gradle.kts, buildSrc/src/main/kotlin/conventions/publishing.gradle.kts, buildSrc/src/main/kotlin/conventions/spotbugs.gradle.kts, buildSrc/src/main/kotlin/conventions/spotless.gradle.kts, buildSrc/src/main/kotlin/conventions/testing-base.gradle.kts, buildSrc/src/main/kotlin/project/kotlin.gradle.kts, buildSrc/src/main/kotlin/project/scala.gradle.kts, gradle/libs.versions.toml
The first commit simplifies use of plugins in buildSrc by upgrading the `dev.panuszewski.typesafe-conventions` plugin to: `0.7.3`.
The second commit introduces the `nexus-publish` to handle publishing to sonatype. Once the migration to central.sonatype.com it should be a case of updating the username and password.
JAVA-5899
=> Added nexus-publish plugin

buildSrc/src/main/kotlin/conventions/publishing.gradle.kts
When migrating to the nexus-publish plugin I changed the dependency to just use `publishSonatype` this stopped the local build artifacts being created and tracing artifacts in evergreen relies on them.
JAVA-5904
=> Ensure local build artifacts are created

driver-core/src/main/com/mongodb/client/model/changestream/NamespaceType.java
This PR addresses build warnings introduced by https://github.com/mongodb/mongo-java-driver/pull/1736.
JAVA-5769
=> Add JavaDoc to NamespaceType.

driver-core/src/main/com/mongodb/MongoTimeoutException.java, driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java
=> Improve `MongoTimeoutException` thrown by `DefaultConnectionPool`

driver-sync/src/test/functional/com/mongodb/client/CrudProseTest.java
Previously, for a parameterized test like
CrudProseTest::testBulkWriteHandlesWriteErrorsAcrossBatches, the test cases in the tests results XML output (and therefore the Evergreen UI) appear as 
```
<testcase name="[1] false" classname="com.mongodb.reactivestreams.client.CrudProseTest""/>
<testcase name="[2] true" classname="com.mongodb.reactivestreams.client.CrudProseTest"/>
```
Making it quite confusing to figure out which test it actually is.
After this change, they will appear as
```
<testcase name="6. MongoClient.bulkWrite handles individual WriteErrors across batches--ordered:false" classname="com.mongodb.reactivestreams.client.CrudProseTest"/>
<testcase name="6. MongoClient.bulkWrite handles individual WriteErrors across batches--ordered:true" …
```
=> Fix parameterized test names in CrudProseTest

driver-core/src/main/com/mongodb/internal/connection/AsynchronousClusterEventListener.java, driver-core/src/main/com/mongodb/internal/connection/BaseCluster.java, driver-core/src/main/com/mongodb/internal/connection/DefaultConnectionPool.java, driver-core/src/main/com/mongodb/internal/connection/DefaultDnsSrvRecordMonitor.java, driver-core/src/main/com/mongodb/internal/connection/DefaultServerMonitor.java, driver-core/src/main/com/mongodb/internal/connection/LoadBalancedCluster.java, driver-core/src/main/com/mongodb/internal/connection/PowerOfTwoBufferPool.java, driver-core/src/main/com/mongodb/internal/connection/TlsChannelStreamFactoryFactory.java, driver-legacy/src/main/com/mongodb/MongoClient.java
Hello dear mongo-java-driver maintainers,
Please allow me to contribute this bugfix. The problem with Throwable in this line is that
it catches errors (OutOfMemoryError in particular) and doesn't let JVM crash leaving it
in zombie state - unable to recover, unable to exit.
JAVA-5913
=> Properly handle exceptions in threads created by MongoClient

driver-core/src/main/com/mongodb/internal/connection/CommandHelper.java, driver-core/src/main/com/mongodb/internal/connection/CommandMessage.java, driver-core/src/main/com/mongodb/internal/connection/CommandProtocolImpl.java, driver-core/src/main/com/mongodb/internal/connection/DefaultServerMonitor.java, driver-core/src/main/com/mongodb/internal/connection/LoggingCommandEventSender.java, driver-core/src/main/com/mongodb/internal/connection/RequestMessage.java, driver-core/src/test/unit/com/mongodb/internal/connection/CommandMessageSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/CommandMessageTest.java, driver-core/src/test/unit/com/mongodb/internal/connection/InternalStreamConnectionSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/LoggingCommandEventSenderSpecification.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/StreamHelper.groovy, driver-core/src/test/unit/com/mongodb/internal/connection/UsageTrackingConnectionSpecification.groovy, driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/internal/MongoOperationPublisher.java, driver-reactive-streams/src/test/unit/com/mongodb/reactivestreams/client/internal/MongoOperationPublisherTest.java, driver-sync/src/main/com/mongodb/client/internal/AggregateIterableImpl.java, driver-sync/src/main/com/mongodb/client/internal/ChangeStreamIterableImpl.java, driver-sync/src/main/com/mongodb/client/internal/MongoDatabaseImpl.java, driver-sync/src/test/unit/com/mongodb/client/MongoClientSpecification.groovy, driver-sync/src/test/unit/com/mongodb/client/internal/MongoClusterSpecification.groovy, driver-sync/src/test/unit/com/mongodb/client/internal/MongoDatabaseSpecification.groovy
This removes a remnant of the pre-OP_MSG wire protocol, which required a synthetic collection name for most commands.  It's no longer needed, except for the last remaining bit where the driver uses OP_QUERY for the first message in the connection handshake.
JAVA-5939
=> Remove internal use of MongoNamespace.COMMAND_COLLECTION_NAME

driver-core/src/main/com/mongodb/MongoNamespace.java
=> Deprecate MongoNamespace#COMMAND_COLLECTION_NAME

driver-core/src/test/functional/com/mongodb/internal/connection/TestCommandListener.java, driver-sync/src/test/functional/com/mongodb/client/unified/ContextElement.java, driver-sync/src/test/functional/com/mongodb/client/unified/EventMatcher.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTestModifications.java
=> Add support for awaiting CommandStartedEvent in Unified Test Runner.

driver-core/src/main/com/mongodb/ClientBulkWriteException.java, driver-core/src/main/com/mongodb/MongoBulkWriteException.java, driver-core/src/main/com/mongodb/MongoCommandException.java, driver-core/src/main/com/mongodb/MongoWriteException.java, driver-core/src/test/unit/com/mongodb/MongoCommandExceptionSpecification.groovy, driver-core/src/test/unit/com/mongodb/MongoWriteExceptionTest.java, driver-legacy/src/main/com/mongodb/BulkWriteException.java, driver-sync/src/test/functional/com/mongodb/internal/connection/OidcAuthenticationProseTests.java
This PR improves the clarity of error messages when a Command fails on a server.
Error messages now explicitly indicate that the exception originated from the server, not the driver, reducing ambiguity when diagnosing failures.
JAVA-5905
=> Improve error message clarity in MongoCommandException.

driver-core/src/main/com/mongodb/internal/operation/AsyncCommandBatchCursor.java, driver-core/src/main/com/mongodb/internal/operation/BatchCursor.java, driver-core/src/main/com/mongodb/internal/operation/CommandBatchCursor.java, driver-core/src/main/com/mongodb/internal/operation/CommandCursorResult.java, driver-sync/src/main/com/mongodb/client/internal/MongoBatchCursorAdapter.java, driver-sync/src/main/com/mongodb/client/internal/MongoChangeStreamCursorImpl.java, driver-sync/src/test/unit/com/mongodb/client/gridfs/GridFSFindIterableSpecification.groovy, driver-sync/src/test/unit/com/mongodb/client/internal/AggregateIterableSpecification.groovy, driver-sync/src/test/unit/com/mongodb/client/internal/ChangeStreamIterableSpecification.groovy, driver-sync/src/test/unit/com/mongodb/client/internal/DistinctIterableSpecification.groovy, driver-sync/src/test/unit/com/mongodb/client/internal/FindIterableSpecification.groovy, driver-sync/src/test/unit/com/mongodb/client/internal/ListCollectionsIterableSpecification.groovy, driver-sync/src/test/unit/com/mongodb/client/internal/ListDatabasesIterableSpecification.groovy, driver-sync/src/test/unit/com/mongodb/client/internal/ListIndexesIterableSpecification.groovy, driver-sync/src/test/unit/com/mongodb/client/internal/MapReduceIterableSpecification.groovy, driver-sync/src/test/unit/com/mongodb/client/internal/MongoBatchCursorAdapterSpecification.groovy, driver-sync/src/test/unit/com/mongodb/client/internal/MongoChangeStreamCursorSpecification.groovy
=> Clear CommandCursorResult.results after next()/tryNext().

driver-core/src/main/com/mongodb/client/model/vault/EncryptOptions.java, driver-core/src/main/com/mongodb/client/model/vault/TextOptions.java, driver-core/src/main/com/mongodb/internal/client/vault/EncryptOptionsHelper.java, driver-core/src/test/functional/com/mongodb/ClusterFixture.java, driver-core/src/test/functional/com/mongodb/client/test/CollectionHelper.java, driver-reactive-streams/src/test/functional/com/mongodb/reactivestreams/client/ClientEncryptionTextExplicitEncryptionTest.java, driver-sync/src/test/functional/com/mongodb/client/AbstractClientEncryptionTextExplicitEncryptionTest.java, driver-sync/src/test/functional/com/mongodb/client/ClientEncryptionTextExplicitEncryptionTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/Entities.java, driver-sync/src/test/functional/com/mongodb/client/unified/RunOnRequirementsMatcher.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedClientEncryptionHelper.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java, driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTestModifications.java, mongodb-crypt/build.gradle.kts, mongodb-crypt/src/main/com/mongodb/internal/crypt/capi/CAPI.java, mongodb-crypt/src/main/com/mongodb/internal/crypt/capi/MongoCryptContext.java, mongodb-crypt/src/main/com/mongodb/internal/crypt/capi/MongoCryptContextImpl.java, mongodb-crypt/src/main/com/mongodb/internal/crypt/capi/MongoCryptImpl.java, mongodb-crypt/src/main/com/mongodb/internal/crypt/capi/MongoExplicitEncryptOptions.java, mongodb-crypt/src/test/java/com/mongodb/crypt/capi/MongoCryptTest.java
Added TextPreview support for Prefix/Suffix/Substring Indexes
JAVA-5851
JAVA-5903
JAVA-5924
=> Support text indexes with encryption

driver-core/src/main/com/mongodb/MongoDriverInformation.java, driver-core/src/main/com/mongodb/annotations/Internal.java, driver-core/src/main/com/mongodb/internal/client/DriverInformation.java, driver-core/src/main/com/mongodb/internal/client/DriverInformationHelper.java, driver-core/src/main/com/mongodb/internal/client/package-info.java, driver-core/src/main/com/mongodb/internal/connection/ClientMetadata.java, driver-core/src/test/functional/com/mongodb/internal/connection/ClientMetadataTest.java, driver-core/src/test/unit/com/mongodb/MongoDriverInformationSpecification.groovy, driver-scala/src/test/scala/org/mongodb/scala/MongoDriverInformationSpec.scala, driver-sync/src/test/functional/com/mongodb/client/AbstractClientMetadataProseTest.java
Avoid appending duplicate metadata
JAVA-5955
=> ClientMetaData refactoring
